export const DESIGN_SYSTEM = {
  COLORS: {
    PRIMARY: '#00FF41',
    PRIMARY_GLOW: 'rgba(0, 255, 65, 0.9)',
    PRIMARY_MUTED: 'rgba(0, 255, 65, 0.15)',
    PRIMARY_STARK: '#FFFFFF',
    BLACK: '#000000',
    ZINC_50: '#fafafa',
    ZINC_100: '#f4f4f5',
    ZINC_200: '#e4e4e7',
    ZINC_300: '#d4d4d8',
    ZINC_400: '#a1a1aa',
    ZINC_500: '#71717a',
    ZINC_600: '#52525b',
    ZINC_700: '#3f3f46',
    ZINC_800: '#27272a',
    ZINC_900: '#18181b',
    ZINC_950: '#09090b',
    NEUTRAL_600: '#525252',
    WHITE: '#FFFFFF',
    WHITE_GLOW: 'rgba(255, 255, 255, 0.7)',
  },
  SHAPES: {
    DIAMOND_CLIP: 'polygon(12% 0%, 88% 0%, 100% 50%, 88% 100%, 12% 100%, 0% 50%)',
    RECT_CLIP: 'polygon(0 0, 100% 0, 100% 100%, 0 100%)',
  },
  ANIMATION: {
    DURATION_BASE: 'duration-200',
    DURATION_SLOW: 'duration-300',
    DURATION_GLOW: 'duration-1000',
    EASING_CUBIC: 'cubic-bezier(0.87,0,0.13,1)',
  },
  TYPOGRAPHY: {
    TRACKING_DEFAULT: 'tracking-[0.4em]',
    TRACKING_XL: 'tracking-[0.5em]',
    TRACKING_2XL: 'tracking-[0.6em]',
  },
  EFFECTS: {
    MEDIA_OVERLAY: 'linear-gradient(to right, rgba(0,0,0,1) 0%, rgba(0,0,0,0.6) 50%, rgba(0,0,0,0) 100%)',
  }
}

export type SortFilterItem = {
  reverse: boolean
  slug: null | string
  title: string
}

export const defaultSort: SortFilterItem = {
  slug: null,
  reverse: false,
  title: 'Alphabetic A-Z',
}

export const sorting: SortFilterItem[] = [
  defaultSort,
  { slug: '-createdAt', reverse: true, title: 'Latest arrivals' },
  { slug: 'priceInUSD', reverse: false, title: 'Price: Low to high' }, // asc
  { slug: '-priceInUSD', reverse: true, title: 'Price: High to low' },
]

export type SelectFieldItems = {
  label: string
  value: string
}

export const partnerTypes: SelectFieldItems[] = [
  { label: 'Title Partner', value: 'title-partner' },
  { label: 'Premier Partner', value: 'premier-partner' },
  { label: 'Official Partner', value: 'official-partner' },
  { label: 'Technical Supplier', value: 'technical-supplier' },
  { label: 'Preferred Supplier', value: 'preferred-supplier' },
  { label: 'Standard Supplier', value: 'standard-supplier' },
  { label: 'Strategic Partner', value: 'strategic-partner' },
];

export const organizationTypes: SelectFieldItems[] = [
  { label: "Sponsors", value: "sponsors" },
  { label: "Investors", value: "investors" },
  { label: "Partners", value: "partners" },
  { label: "Supporters", value: "supporters" },
  { label: "Promoters", value: "promoters" },
  { label: "Organizers", value: "organizers" },
  { label: "Media", value: "media" },
  { label: "Government", value: "government" },
  { label: "NGO", value: "ngo" },
  { label: "Developers", value: "developers" },
  { label: "Distributors", value: "distributors" },
  { label: "Retailers", value: "retailers" },
  { label: "Manufacturers", value: "manufacturers" },
  { label: "Suppliers", value: "suppliers" },
  { label: "Service Providers", value: "service-providers" },
  { label: "Service Recipients", value: "service-recipients" },
  { label: 'Others', value: 'others' },
];

export const industries: SelectFieldItems[] = [
  { label: 'Aerospace', value: 'aerospace' },
  { label: 'Agriculture', value: 'agriculture' },
  { label: 'AI & Machine Learning', value: 'ai-machine-learning' },
  { label: 'Apparel & Fashion', value: 'apparel-fashion' },
  { label: 'Automotive', value: 'automotive' },
  { label: 'Banking & Finance', value: 'banking-finance' },
  { label: 'Betting & Gambling', value: 'betting-gambling' },
  { label: 'Blockchain & Crypto', value: 'blockchain-crypto' },
  { label: 'Chemicals', value: 'chemicals' },
  { label: 'Cloud Computing', value: 'cloud-computing' },
  { label: 'Construction', value: 'construction' },
  { label: 'Consulting', value: 'consulting' },
  { label: 'Cybersecurity', value: 'cybersecurity' },
  { label: 'Data Analytics', value: 'data-analytics' },
  { label: 'E-commerce', value: 'ecommerce' },
  { label: 'Education', value: 'education' },
  { label: 'Electronics', value: 'electronics' },
  { label: 'Energy & Utilities', value: 'energy-utilities' },
  { label: 'Engineering', value: 'engineering' },
  { label: 'Entertainment', value: 'entertainment' },
  { label: 'Environmental Services', value: 'environmental-services' },
  { label: 'Esports & Gaming', value: 'esports-gaming' },
  { label: 'Event Management', value: 'event-management' },
  { label: 'Fitness & Wellness', value: 'fitness-wellness' },
  { label: 'Food & Beverage', value: 'food-beverage' },
  { label: 'Government', value: 'government' },
  { label: 'Healthcare', value: 'healthcare' },
  { label: 'Hospitality', value: 'hospitality' },
  { label: 'Human Resources', value: 'human-resources' },
  { label: 'Insurance', value: 'insurance' },
  { label: 'Legal Services', value: 'legal-services' },
  { label: 'Logistics & Supply Chain', value: 'logistics-supply-chain' },
  { label: 'Lubricants', value: 'lubricants' },
  { label: 'Luxury Goods', value: 'luxury-goods' },
  { label: 'Manufacturing', value: 'manufacturing' },
  { label: 'Marketing & Advertising', value: 'marketing-advertising' },
  { label: 'Materials Science', value: 'materials-science' },
  { label: 'Media & Broadcasting', value: 'media-broadcasting' },
  { label: 'Mining', value: 'mining' },
  { label: 'Non-Profit', value: 'non-profit' },
  { label: 'Oil & Gas', value: 'oil-gas' },
  { label: 'Pharmaceuticals', value: 'pharmaceuticals' },
  { label: 'Printing & Publishing', value: 'printing-publishing' },
  { label: 'Property', value: 'property' },
  { label: 'Public Sector', value: 'public-sector' },
  { label: 'Railway', value: 'railway' },
  { label: 'Real Estate', value: 'real-estate' },
  { label: 'Retail', value: 'retail' },
  { label: 'Security', value: 'security' },
  { label: 'Shipping', value: 'shipping' },
  { label: 'Sports', value: 'sports' },
  { label: 'Telecommunications', value: 'telecommunications' },
  { label: 'Textiles', value: 'textiles' },
  { label: 'Tourism', value: 'tourism' },
  { label: 'Transportation', value: 'transportation' },
  { label: 'Utilities', value: 'utilities' },
]

export const countries: SelectFieldItems[] = [
  { label: 'All', value: 'all' },
  { label: 'Afghanistan', value: 'AF' },
  { label: 'Albania', value: 'AL' },
  { label: 'Algeria', value: 'DZ' },
  { label: 'American Samoa', value: 'AS' },
  { label: 'Andorra', value: 'AD' },
  { label: 'Angola', value: 'AO' },
  { label: 'Anguilla', value: 'AI' },
  { label: 'Antarctica', value: 'AQ' },
  { label: 'Antigua and Barbuda', value: 'AG' },
  { label: 'Argentina', value: 'AR' },
  { label: 'Armenia', value: 'AM' },
  { label: 'Aruba', value: 'AW' },
  { label: 'Australia', value: 'AU' },
  { label: 'Austria', value: 'AT' },
  { label: 'Azerbaijan', value: 'AZ' },
  { label: 'Bahamas', value: 'BS' },
  { label: 'Bahrain', value: 'BH' },
  { label: 'Bangladesh', value: 'BD' },
  { label: 'Barbados', value: 'BB' },
  { label: 'Belarus', value: 'BY' },
  { label: 'Belgium', value: 'BE' },
  { label: 'Belize', value: 'BZ' },
  { label: 'Benin', value: 'BJ' },
  { label: 'Bermuda', value: 'BM' },
  { label: 'Bhutan', value: 'BT' },
  { label: 'Bolivia', value: 'BO' },
  { label: 'Bosnia and Herzegovina', value: 'BA' },
  { label: 'Botswana', value: 'BW' },
  { label: 'Brazil', value: 'BR' },
  { label: 'Brunei', value: 'BN' },
  { label: 'Bulgaria', value: 'BG' },
  { label: 'Burkina Faso', value: 'BF' },
  { label: 'Burundi', value: 'BI' },
  { label: 'Cabo Verde', value: 'CV' },
  { label: 'Cambodia', value: 'KH' },
  { label: 'Cameroon', value: 'CM' },
  { label: 'Canada', value: 'CA' },
  { label: 'Cayman Islands', value: 'KY' },
  { label: 'Central African Republic', value: 'CF' },
  { label: 'Chad', value: 'TD' },
  { label: 'Chile', value: 'CL' },
  { label: 'China', value: 'CN' },
  { label: 'Christmas Island', value: 'CX' },
  { label: 'Cocos Islands', value: 'CC' },
  { label: 'Colombia', value: 'CO' },
  { label: 'Comoros', value: 'KM' },
  { label: 'Congo', value: 'CG' },
  { label: 'Congo (DRC)', value: 'CD' },
  { label: 'Cook Islands', value: 'CK' },
  { label: 'Costa Rica', value: 'CR' },
  { label: 'Croatia', value: 'HR' },
  { label: 'Cuba', value: 'CU' },
  { label: 'Curaçao', value: 'CW' },
  { label: 'Cyprus', value: 'CY' },
  { label: 'Czechia', value: 'CZ' },
  { label: 'Denmark', value: 'DK' },
  { label: 'Djibouti', value: 'DJ' },
  { label: 'Dominica', value: 'DM' },
  { label: 'Dominican Republic', value: 'DO' },
  { label: 'Ecuador', value: 'EC' },
  { label: 'Egypt', value: 'EG' },
  { label: 'El Salvador', value: 'SV' },
  { label: 'Equatorial Guinea', value: 'GQ' },
  { label: 'Eritrea', value: 'ER' },
  { label: 'Estonia', value: 'EE' },
  { label: 'Eswatini', value: 'SZ' },
  { label: 'Ethiopia', value: 'ET' },
  { label: 'Falkland Islands', value: 'FK' },
  { label: 'Faroe Islands', value: 'FO' },
  { label: 'Fiji', value: 'FJ' },
  { label: 'Finland', value: 'FI' },
  { label: 'France', value: 'FR' },
  { label: 'French Guiana', value: 'GF' },
  { label: 'French Polynesia', value: 'PF' },
  { label: 'Gabon', value: 'GA' },
  { label: 'Gambia', value: 'GM' },
  { label: 'Georgia', value: 'GE' },
  { label: 'Germany', value: 'DE' },
  { label: 'Ghana', value: 'GH' },
  { label: 'Gibraltar', value: 'GI' },
  { label: 'Greece', value: 'GR' },
  { label: 'Greenland', value: 'GL' },
  { label: 'Grenada', value: 'GD' },
  { label: 'Guadeloupe', value: 'GP' },
  { label: 'Guam', value: 'GU' },
  { label: 'Guatemala', value: 'GT' },
  { label: 'Guernsey', value: 'GG' },
  { label: 'Guinea', value: 'GN' },
  { label: 'Guinea-Bissau', value: 'GW' },
  { label: 'Guyana', value: 'GY' },
  { label: 'Haiti', value: 'HT' },
  { label: 'Honduras', value: 'HN' },
  { label: 'Hong Kong', value: 'HK' },
  { label: 'Hungary', value: 'HU' },
  { label: 'Iceland', value: 'IS' },
  { label: 'India', value: 'IN' },
  { label: 'Indonesia', value: 'ID' },
  { label: 'Iran', value: 'IR' },
  { label: 'Iraq', value: 'IQ' },
  { label: 'Ireland', value: 'IE' },
  { label: 'Isle of Man', value: 'IM' },
  { label: 'Israel', value: 'IL' },
  { label: 'Italy', value: 'IT' },
  { label: 'Jamaica', value: 'JM' },
  { label: 'Japan', value: 'JP' },
  { label: 'Jersey', value: 'JE' },
  { label: 'Jordan', value: 'JO' },
  { label: 'Kazakhstan', value: 'KZ' },
  { label: 'Kenya', value: 'KE' },
  { label: 'Kiribati', value: 'KI' },
  { label: 'Kuwait', value: 'KW' },
  { label: 'Kyrgyzstan', value: 'KG' },
  { label: 'Laos', value: 'LA' },
  { label: 'Latvia', value: 'LV' },
  { label: 'Lebanon', value: 'LB' },
  { label: 'Lesotho', value: 'LS' },
  { label: 'Liberia', value: 'LR' },
  { label: 'Libya', value: 'LY' },
  { label: 'Liechtenstein', value: 'LI' },
  { label: 'Lithuania', value: 'LT' },
  { label: 'Luxembourg', value: 'LU' },
  { label: 'Macau', value: 'MO' },
  { label: 'Madagascar', value: 'MG' },
  { label: 'Malawi', value: 'MW' },
  { label: 'Malaysia', value: 'MY' },
  { label: 'Maldives', value: 'MV' },
  { label: 'Mali', value: 'ML' },
  { label: 'Malta', value: 'MT' },
  { label: 'Marshall Islands', value: 'MH' },
  { label: 'Martinique', value: 'MQ' },
  { label: 'Mauritania', value: 'MR' },
  { label: 'Mauritius', value: 'MU' },
  { label: 'Mayotte', value: 'YT' },
  { label: 'Mexico', value: 'MX' },
  { label: 'Micronesia', value: 'FM' },
  { label: 'Moldova', value: 'MD' },
  { label: 'Monaco', value: 'MC' },
  { label: 'Mongolia', value: 'MN' },
  { label: 'Montenegro', value: 'ME' },
  { label: 'Montserrat', value: 'MS' },
  { label: 'Morocco', value: 'MA' },
  { label: 'Mozambique', value: 'MZ' },
  { label: 'Myanmar', value: 'MM' },
  { label: 'Namibia', value: 'NA' },
  { label: 'Nauru', value: 'NR' },
  { label: 'Nepal', value: 'NP' },
  { label: 'Netherlands', value: 'NL' },
  { label: 'New Caledonia', value: 'NC' },
  { label: 'New Zealand', value: 'NZ' },
  { label: 'Nicaragua', value: 'NI' },
  { label: 'Niger', value: 'NE' },
  { label: 'Nigeria', value: 'NG' },
  { label: 'Niue', value: 'NU' },
  { label: 'Norfolk Island', value: 'NF' },
  { label: 'North Korea', value: 'KP' },
  { label: 'North Macedonia', value: 'MK' },
  { label: 'Northern Mariana Islands', value: 'MP' },
  { label: 'Norway', value: 'NO' },
  { label: 'Oman', value: 'OM' },
  { label: 'Pakistan', value: 'PK' },
  { label: 'Palau', value: 'PW' },
  { label: 'Panama', value: 'PA' },
  { label: 'Papua New Guinea', value: 'PG' },
  { label: 'Paraguay', value: 'PY' },
  { label: 'Peru', value: 'PE' },
  { label: 'Philippines', value: 'PH' },
  { label: 'Pitcairn Islands', value: 'PN' },
  { label: 'Poland', value: 'PL' },
  { label: 'Portugal', value: 'PT' },
  { label: 'Puerto Rico', value: 'PR' },
  { label: 'Qatar', value: 'QA' },
  { label: 'Réunion', value: 'RE' },
  { label: 'Romania', value: 'RO' },
  { label: 'Russia', value: 'RU' },
  { label: 'Rwanda', value: 'RW' },
  { label: 'Saint Barthélemy', value: 'BL' },
  { label: 'Saint Helena', value: 'SH' },
  { label: 'Saint Kitts and Nevis', value: 'KN' },
  { label: 'Saint Lucia', value: 'LC' },
  { label: 'Saint Martin', value: 'MF' },
  { label: 'Saint Pierre and Miquelon', value: 'PM' },
  { label: 'Saint Vincent and the Grenadines', value: 'VC' },
  { label: 'Samoa', value: 'WS' },
  { label: 'San Marino', value: 'SM' },
  { label: 'Sao Tome and Principe', value: 'ST' },
  { label: 'Saudi Arabia', value: 'SA' },
  { label: 'Senegal', value: 'SN' },
  { label: 'Serbia', value: 'RS' },
  { label: 'Seychelles', value: 'SC' },
  { label: 'Sierra Leone', value: 'SL' },
  { label: 'Singapore', value: 'SG' },
  { label: 'Sint Maarten', value: 'SX' },
  { label: 'Slovakia', value: 'SK' },
  { label: 'Slovenia', value: 'SI' },
  { label: 'Solomon Islands', value: 'SB' },
  { label: 'Somalia', value: 'SO' },
  { label: 'South Africa', value: 'ZA' },
  { label: 'South Georgia', value: 'GS' },
  { label: 'South Korea', value: 'KR' },
  { label: 'South Sudan', value: 'SS' },
  { label: 'Spain', value: 'ES' },
  { label: 'Sri Lanka', value: 'LK' },
  { label: 'Sudan', value: 'SD' },
  { label: 'Suriname', value: 'SR' },
  { label: 'Svalbard and Jan Mayen', value: 'SJ' },
  { label: 'Sweden', value: 'SE' },
  { label: 'Switzerland', value: 'CH' },
  { label: 'Syria', value: 'SY' },
  { label: 'Taiwan', value: 'TW' },
  { label: 'Tajikistan', value: 'TJ' },
  { label: 'Tanzania', value: 'TZ' },
  { label: 'Thailand', value: 'TH' },
  { label: 'Timor-Leste', value: 'TL' },
  { label: 'Togo', value: 'TG' },
  { label: 'Tokelau', value: 'TK' },
  { label: 'Tonga', value: 'TO' },
  { label: 'Trinidad and Tobago', value: 'TT' },
  { label: 'Tunisia', value: 'TN' },
  { label: 'Turkey', value: 'TR' },
  { label: 'Turkmenistan', value: 'TM' },
  { label: 'Turks and Caicos Islands', value: 'TC' },
  { label: 'Tuvalu', value: 'TV' },
  { label: 'Uganda', value: 'UG' },
  { label: 'Ukraine', value: 'UA' },
  { label: 'United Arab Emirates', value: 'AE' },
  { label: 'United Kingdom', value: 'GB' },
  { label: 'United States', value: 'US' },
  { label: 'Uruguay', value: 'UY' },
  { label: 'Uzbekistan', value: 'UZ' },
  { label: 'Vanuatu', value: 'VU' },
  { label: 'Vatican City', value: 'VA' },
  { label: 'Venezuela', value: 'VE' },
  { label: 'Vietnam', value: 'VN' },
  { label: 'Wallis and Futuna', value: 'WF' },
  { label: 'Western Sahara', value: 'EH' },
  { label: 'Yemen', value: 'YE' },
  { label: 'Zambia', value: 'ZM' },
  { label: 'Zimbabwe', value: 'ZW' },
];

export const timezones = [
  { label: 'Universal Coordinated Time (UTC)', value: 'UTC' },
  { label: 'Greenwich Mean Time (GMT)', value: 'GMT' },
  { label: 'European Central Time (UTC+1)', value: 'ECT' },
  { label: 'Eastern European Time (UTC+2)', value: 'EET' },
  { label: 'Arabic Standard Time (UTC+3)', value: 'AST' },
  { label: 'Middle East Time (UTC+3:30)', value: 'MET' },
  { label: 'Near East Time (UTC+4)', value: 'NET' },
  { label: 'Pakistan Lahore Time (UTC+5)', value: 'PLT' },
  { label: 'India Standard Time (UTC+5:30)', value: 'IST' },
  { label: 'Bangladesh Standard Time (UTC+6)', value: 'BST' },
  { label: 'Vietnam Standard Time (UTC+7)', value: 'VST' },
  { label: 'China Taiwan Time (UTC+8)', value: 'CTT' },
  { label: 'Japan Standard Time (UTC+9)', value: 'JST' },
  { label: 'Australia Central Time (UTC+9:30)', value: 'ACT' },
  { label: 'Australia Eastern Time (UTC+10)', value: 'AET' },
  { label: 'New Zealand Standard Time (UTC+12)', value: 'NZST' },
  { label: 'Atlantic Standard Time (UTC-4)', value: 'AST_US' },
  { label: 'Eastern Standard Time (UTC-5)', value: 'EST' },
  { label: 'Central Standard Time (UTC-6)', value: 'CST' },
  { label: 'Mountain Standard Time (UTC-7)', value: 'MST' },
  { label: 'Pacific Standard Time (UTC-8)', value: 'PST' },
  { label: 'Alaska Standard Time (UTC-9)', value: 'AKST' },
  { label: 'Hawaii-Aleutian Standard Time (UTC-10)', value: 'HST' },
];

export const channels: SelectFieldItems[] = [
  { label: 'Instagram', value: 'instagram' },
  { label: 'Twitter', value: 'twitter' },
  { label: 'Threads', value: 'threads' },
  { label: 'Facebook', value: 'facebook' },
  { label: 'TikTok', value: 'tiktok' },
  { label: 'Reddit', value: 'reddit' },
  { label: 'Discord', value: 'discord' },
  { label: 'YouTube', value: 'youtube' },
  { label: 'Twitch', value: 'twitch' },
  { label: 'LinkedIn', value: 'linkedin' },
];

export const standardsLevels = [
  { label: 'Level 1 (Highest/International)', value: 'level_1' },
  { label: 'Level 2 (High/Continental)', value: 'level_2' },
  { label: 'Level 3 (Standard/National)', value: 'level_3' },
  { label: 'Level 4 (Entry/Regional)', value: 'level_4' },
  { label: 'Experimental/Provisional', value: 'experimental' },
];

export const standardsStatus = [
  { label: 'Fully Compliant', value: 'compliant' },
  { label: 'Pending Certification', value: 'pending' },
  { label: 'Under Review', value: 'review' },
  { label: 'Non-Compliant/Restricted', value: 'non_compliant' },
  { label: 'Exempted', value: 'exempted' },
];

export const regulationTypes = [
  { label: 'Sporting & Competition', value: 'sporting' },
  { label: 'Technical & Engineering', value: 'technical' },
  { label: 'Financial & Budgetary', value: 'financial' },
  { label: 'Safety & Medical', value: 'safety' },
  { label: 'Judicial & Disciplinary', value: 'judicial' },
  { label: 'Commercial & Media', value: 'commercial' },
];

export const regulationEnforcement = [
  { label: 'Live Scrutineering', value: 'live' },
  { label: 'Post-Event Inspection', value: 'post_event' },
  { label: 'Telemetry Monitoring', value: 'telemetry' },
  { label: 'Self-Declaration', value: 'declaration' },
  { label: 'Financial Audit', value: 'audit' },
];

export const technicalCategories = [
  { label: 'Power Unit / Engine', value: 'engine' },
  { label: 'Chassis & Aerodynamics', value: 'chassis' },
  { label: 'Drivetrain & Transmission', value: 'drivetrain' },
  { label: 'Suspension & Steering', value: 'mechanical' },
  { label: 'Electronic Systems / ECU', value: 'electronics' },
  { label: 'Tires & Wheels', value: 'wheels' },
  { label: 'Safety Equipment', value: 'safety_tech' },
  { label: 'Fuel & Lubricants', value: 'fluids' },
];

export const technicalUnits = [
  { label: 'Kilograms (kg)', value: 'kg' },
  { label: 'Millimeters (mm)', value: 'mm' },
  { label: 'Centimeters (cm)', value: 'cm' },
  { label: 'Liters (L)', value: 'liters' },
  { label: 'Cubic Centimeters (cc)', value: 'cc' },
  { label: 'Horsepower (hp)', value: 'hp' },
  { label: 'Kilowatts (kW)', value: 'kw' },
  { label: 'Newton-meters (Nm)', value: 'nm' },
  { label: 'Bar / PSI', value: 'pressure' },
  { label: 'Degrees Celsius (°C)', value: 'celsius' },
  { label: 'Revolutions Per Minute (RPM)', value: 'rpm' },
  { label: 'Percentage (%)', value: 'percent' },
];

export const featureTypes = [
  { label: 'Technical Innovation', value: 'tech' },
  { label: 'Sporting Format', value: 'format' },
  { label: 'Environmental/Sustainability', value: 'green' },
  { label: 'Geographical/Venue', value: 'venue' },
  { label: 'Legacy/Heritage', value: 'heritage' },
];

export const impactLevels = [
  { label: 'Low (Minor Detail)', value: 'low' },
  { label: 'Medium (Noticeable Influence)', value: 'medium' },
  { label: 'High (Core Identity)', value: 'high' },
  { label: 'Critical (Game Changer)', value: 'critical' },
];

export const engagementTypes = [
  { label: 'In-Person (Live)', value: 'live' },
  { label: 'Digital/Mobile', value: 'digital' },
  { label: 'Social Media', value: 'social' },
  { label: 'Broadcast/Streaming', value: 'broadcast' },
  { label: 'Gaming/Esports', value: 'gaming' },
  { label: 'Merchandising', value: 'retail' },
];

export const accessibilityLevels = [
  { label: 'Public (All Fans)', value: 'public' },
  { label: 'Ticket Holders Only', value: 'tickets' },
  { label: 'Premium/VIP', value: 'premium' },
  { label: 'Corporate/Partners', value: 'corporate' },
  { label: 'Invite Only', value: 'invite' },
];

export const safetyTiers = [
  { label: 'Tier 1: Life-Safety (Critical)', value: 'critical' },
  { label: 'Tier 2: Operational Protocol', value: 'operational' },
  { label: 'Tier 3: Precautionary / Medical', value: 'precautionary' },
  { label: 'Tier 4: Training & Simulation', value: 'training' },
];

export const equipmentRequirements = [
  { label: 'Specialized Medical Unit', value: 'medical_unit' },
  { label: 'Fire Suppression Systems', value: 'fire_suppression' },
  { label: 'Extraction / Recovery Vehicles', value: 'recovery_vehicles' },
  { label: 'Telemetry & Monitoring Systems', value: 'telemetry' },
  { label: 'PPE (Personal Protective Equipment)', value: 'ppe' },
  { label: 'Hazardous Material Handling', value: 'hazmat' },
];

export const sustainabilityTiers = [
  { label: 'ISO 20121 (Sustainable Events)', value: 'iso_20121' },
  { label: 'FIA 3-Star Environmental Accreditation', value: 'fia_3_star' },
  { label: 'Carbon Neutral / Net Zero', value: 'net_zero' },
  { label: 'Circular Economy Commitment', value: 'circular_economy' },
];

export const environmentalImpacts = [
  { label: 'Carbon Emissions & Footprint', value: 'carbon' },
  { label: 'Waste Management & Recycling', value: 'waste' },
  { label: 'Energy Efficiency & Renewables', value: 'energy' },
  { label: 'Water Conservation', value: 'water' },
  { label: 'Biodiversity & Land Use', value: 'biodiversity' },
  { label: 'Supply Chain Sustainability', value: 'supply_chain' },
];

export const sessionStatus = [
  { label: 'Upcoming', value: 'upcoming' },
  { label: 'In Progress', value: 'in_progress' },
  { label: 'Completed', value: 'completed' },
  { label: 'Red Flagged', value: 'red_flagged' },
  { label: 'Cancelled', value: 'cancelled' },
  { label: 'Postponed', value: 'postponed' },
];

export const trackStatus = [
  { label: 'Green (Clear)', value: 'green' },
  { label: 'Yellow (Hazard)', value: 'yellow' },
  { label: 'SC (Safety Car)', value: 'safety_car' },
  { label: 'VSC (Virtual Safety Car)', value: 'vsc' },
  { label: 'Red (Stopped)', value: 'red' },
  { label: 'Damp', value: 'damp' },
  { label: 'Wet', value: 'wet' },
];

export const sessionTypes = [
  { label: 'Practice', value: 'practice' },
  { label: 'Qualifying', value: 'qualifying' },
  { label: 'Race', value: 'race' },
  { label: 'Shootout', value: 'shootout' },
  { label: 'Test', value: 'test' },
  { label: 'Other', value: 'other' },
];

export const sessionFormats = [
  { label: 'Knockout', value: 'knockout' },
  { label: 'Single Lap', value: 'single_lap' },
  { label: 'Timed Duration', value: 'timed' },
  { label: 'Lap Count', value: 'laps' },
];

export const sessionPriority = [
  { label: 'P1: Main Event', value: 'high' },
  { label: 'P2: Supporting', value: 'medium' },
  { label: 'P3: Exhibition', value: 'low' },
];

export const entryStatus = [
  { label: 'Confirmed', value: 'confirmed' },
  { label: 'Withdrawn', value: 'withdrawn' },
  { label: 'DNS (Did Not Start)', value: 'did_not_start' },
  { label: 'DNQ (Did Not Qualify)', value: 'did_not_qualify' },
  { label: 'DSQ (Disqualified)', value: 'disqualified' },
];

export const eligibilityStatus = [
  { label: 'Full Eligibility', value: 'eligible' },
  { label: 'Under Technical Protest', value: 'protest' },
  { label: 'Probational', value: 'probation' },
  { label: 'Exhibition Only', value: 'exhibition' },
];

export const devices: SelectFieldItems[] = [
  {
    label: 'Mobile',
    value: 'mobile'
  },
  {
    label: 'Landline',
    value: 'landline'
  },
  {
    label: 'Fax',
    value: 'fax'
  },
  {
    label: 'Other',
    value: 'other'
  }
]

export const departments: SelectFieldItems[] = [
  {
    label: 'Engineering',
    value: 'engineering',
  },
  {
    label: 'Operations',
    value: 'operations',
  },
  {
    label: 'Marketing',
    value: 'marketing',
  },
  {
    label: 'Hospitality',
    value: 'hospitality',
  },
  {
    label: 'Logistics',
    value: 'logistics',
  },
  {
    label: 'Management',
    value: 'management',
  },
  {
    label: 'Technical',
    value: 'technical',
  },
  {
    label: 'Commercial',
    value: 'commercial',
  },
  {
    label: 'Sales',
    value: 'sales',
  },
];

export const designations: SelectFieldItems[] = [
  { label: 'Mr', value: 'mr' },
  { label: 'Mrs', value: 'mrs' },
  { label: 'Ms', value: 'ms' },
  { label: 'Dr', value: 'dr' },
  { label: 'Prof', value: 'prof' },
  { label: 'Rev', value: 'rev' },
];

export const roles: SelectFieldItems[] = [
  {
    label: 'Pit Crew',
    value: 'pit-crew',
  },
  {
    label: 'Engineer',
    value: 'engineer',
  },
  {
    label: 'Contracter',
    value: 'contracter',
  },
  {
    label: 'Staff',
    value: 'staff',
  },
  {
    label: 'Employee',
    value: 'employee',
  },
  {
    label: 'Cleaner',
    value: 'cleaner',
  },
  {
    label: 'Mechanic',
    value: 'mechanic',
  },
];

export const statuses: SelectFieldItems[] = [
  { label: 'Active', value: 'active' },
  { label: 'Reserve', value: 'reserve' },
  { label: 'Alumni', value: 'alumni' },
  { label: 'Junior', value: 'junior' },
  { label: 'Development', value: 'development' },
  { label: 'Injured', value: 'injured' },
  { label: 'Retired', value: 'retired' },
  { label: 'Other', value: 'other' },
];

export const shiftPatterns: SelectFieldItems[] = [
  { label: 'Day Shift', value: 'day_shift' },
  { label: 'Night Shift', value: 'night_shift' },
  { label: 'Evening Shift', value: 'evening_shift' },
  { label: 'Rotating Shift', value: 'rotating_shift' },
  { label: 'Flexible Shift', value: 'flexible_shift' },
  { label: 'Other', value: 'other' },
];

export const partnershipStatuses: SelectFieldItems[] = [
  { label: 'Active', value: 'active' },
  { label: 'Inactive', value: 'inactive' },
  { label: 'Pending', value: 'pending' },
  { label: 'Terminated', value: 'terminated' },
  { label: 'Other', value: 'other' },
];

export const preferences: SelectFieldItems[] = [
  { label: 'Not Important', value: 'not_important' },
  { label: 'Important', value: 'important' },
  { label: 'Very Important', value: 'very_important' },
  { label: 'Extremely Important', value: 'extremely_important' },
];

export const relations: SelectFieldItems[] = [
  { label: 'Members', value: 'members' },
  { label: 'Leaders', value: 'leaders' },
  { label: 'Drivers', value: 'drivers' },
  { label: 'Cars', value: 'cars' },
  { label: 'Events', value: 'events' },
  { label: 'Initiatives', value: 'initiatives' },
  { label: 'Celebrations', value: 'celebrations' },
  { label: 'Careers', value: 'careers' },
  { label: 'Series', value: 'series' },
  { label: 'Seasons', value: 'seasons' }
];

export const questionPurposes: SelectFieldItems[] = [
  { label: 'Contact', value: 'contact' },
  { label: 'Preference', value: 'preference' },
  { label: 'General Inquiry', value: 'general_inquiry' },
  { label: 'Technical Support', value: 'technical_support' },
  { label: 'Billing & Payments', value: 'billing_payments' },
  { label: 'Account Management', value: 'account_management' },
  { label: 'Membership', value: 'membership' },
  { label: 'Event Registration', value: 'event_registration' },
  { label: 'Sponsorship', value: 'sponsorship' },
  { label: 'Careers', value: 'careers' },
  { label: 'Other', value: 'other' },
];

export const proficiencyTypes: SelectFieldItems[] = [
  {
    label: 'Beginner',
    value: 'beginner',
  },
  {
    label: 'Intermediate',
    value: 'intermediate',
  },
  {
    label: 'Advanced',
    value: 'advanced',
  },
  {
    label: 'Expert',
    value: 'expert',
  },
];

export const seriesLevels: SelectFieldItems[] = [
  { label: "International", value: "international" },
  { label: "National", value: "national" },
  { label: "Regional", value: "regional" },
  { label: "Club/Amateur", value: "club" },
  { label: "Junior", value: "junior" },
  { label: "Professional", value: "professional" },
  { label: "Semi-Professional", value: "semi_professional" },
  { label: "Other", value: "other" }
];

export const seriesTypes: SelectFieldItems[] = [
  { label: "Formula Racing", value: "formula" },
  { label: "GT Racing", value: "gt" },
  { label: "Prototype/Sports Car Racing", value: "sports" },
  { label: "Touring Car Racing", value: "touring" },
  { label: "Single-Make Series", value: "single-make" },
  { label: "Endurance Racing", value: "endurance" },
  { label: "Sprint Racing", value: "sprint" },
  { label: "Rally/Rallycross", value: "rally" },
  { label: "Historic/Vintage Racing", value: "historic" },
  { label: "Club Racing", value: "club" },
];

export const seriesCodes: SelectFieldItems[] = [
  { label: "FIA Formula 1 World Championship", value: "f1" },
  { label: "FIA World Endurance Championship", value: "wec" },
  { label: "FIA World Rally Championship", value: "wrc" },
  { label: "Formula E", value: "fe" },
  { label: "IndyCar Series", value: "indycar" },
  { label: "NASCAR Cup Series", value: "nascar" },
  { label: "IMSA WeatherTech SportsCar Championship", value: "imsa" },
  { label: "GT World Challenge", value: "gtwc" },
  { label: "DTM", value: "dtm" },
  { label: "Super GT", value: "supergt" },
  { label: "Other", value: "other" }
];

export const raceFormats: SelectFieldItems[] = [
  { label: "Sprint", value: "sprint" },
  { label: "Endurance", value: "endurance" },
  { label: "Street Circuit", value: "street" },
  { label: "Road Course", value: "road" },
  { label: "Oval", value: "oval" },
  { label: "Rally Stage", value: "rally_stage" },
  { label: "Hill Climb", value: "hill_climb" },
  { label: "Drag Strip", value: "drag" },
  { label: "Mixed Surface", value: "mixed" },
  { label: "Other", value: "other" }
];

export const regions: SelectFieldItems[] = [
  { label: "Europe", value: "europe" },
  { label: "North America", value: "north_america" },
  { label: "Asia", value: "asia" },
  { label: "South America", value: "south_america" },
  { label: "Africa", value: "africa" },
  { label: "Oceania", value: "oceania" },
  { label: "Global", value: "global" },
  { label: "Middle East", value: "middle_east" },
  { label: "Asia-Pacific", value: "asia_pacific" },
  { label: "Other", value: "other" }
];

export const fastestLapConditions = [
  { label: 'None', value: 'none' },
  { label: 'Top 10 Finishers', value: 'top_10_finishers' },
  { label: 'Lead Lap Only', value: 'lead_lap_only' },
  { label: 'Finished Race', value: 'finished_race' },
];

export const penaltyCurrencies = [
  { label: 'US Dollar ($)', value: 'USD' },
  { label: 'Euro (€)', value: 'EUR' },
  { label: 'British Pound (£)', value: 'GBP' },
  { label: 'Swiss Franc (CHF)', value: 'CHF' },
];

export const penaltyResetPeriods = [
  { label: 'End of Season', value: 'season_end' },
  { label: 'Rolling 12 Months', value: 'rolling_12' },
  { label: 'Fixed Calendar Date', value: 'fixed_date' },
];

export const seasonUnits = [
  { label: 'Days', value: 'days' },
  { label: 'Weeks', value: 'weeks' },
  { label: 'Months', value: 'months' },
  { label: 'Years', value: 'years' },
];

export const frequencyUnits = [
  { label: 'Daily', value: 'daily' },
  { label: 'Weekly', value: 'weekly' },
  { label: 'Bi-Weekly', value: 'bi_weekly' },
  { label: 'Monthly', value: 'monthly' },
];

export const windowUnits = [
  { label: 'Minutes', value: 'minutes' },
  { label: 'Hours', value: 'hours' },
  { label: 'Days', value: 'days' },
];

export const carStatuses: SelectFieldItems[] = [
  { label: 'Active', value: 'active' },
  { label: 'Retired', value: 'retired' },
  { label: 'Prototype', value: 'prototype' },
  { label: 'Destroyed', value: 'destroyed' },
  { label: 'Museum', value: 'museum' },
  { label: 'Spare', value: 'spare' },
];

export const componentStatuses: SelectFieldItems[] = [
  { label: 'Good', value: 'good' },
  { label: 'Damaged', value: 'damaged' },
  { label: 'Broken', value: 'broken' },
  { label: 'Missing', value: 'missing' },
  { label: 'Other', value: 'other' },
];

export const componentCategories: SelectFieldItems[] = [
  { label: 'Engine', value: 'engine' },
  { label: 'Transmission', value: 'transmission' },
  { label: 'Suspension', value: 'suspension' },
  { label: 'Brakes', value: 'brakes' },
  { label: 'Exhaust', value: 'exhaust' },
  { label: 'Intake', value: 'intake' },
  { label: 'Cooling', value: 'cooling' },
  { label: 'Electronics', value: 'electronics' },
  { label: 'Other', value: 'other' },
];

export const languages: SelectFieldItems[] = [
  { label: "Afar", value: "afar" },
  { label: "Abkhazian", value: "abkhazian" },
  { label: "Avestan", value: "avestan" },
  { label: "Afrikaans", value: "afrikaans" },
  { label: "Akan", value: "akan" },
  { label: "Amharic", value: "amharic" },
  { label: "Aragonese", value: "aragonese" },
  { label: "Arabic", value: "arabic" },
  { label: "Assamese", value: "assamese" },
  { label: "Avaric", value: "avaric" },
  { label: "Aymara", value: "aymara" },
  { label: "Azerbaijani", value: "azerbaijani" },
  { label: "Bashkir", value: "bashkir" },
  { label: "Belarusian", value: "belarusian" },
  { label: "Bulgarian", value: "bulgarian" },
  { label: "Bihari", value: "bihari" },
  { label: "Bislama", value: "bislama" },
  { label: "Bambara", value: "bambara" },
  { label: "Bengali", value: "bengali" },
  { label: "Tibetan", value: "tibetan" },
  { label: "Breton", value: "breton" },
  { label: "Bosnian", value: "bosnian" },
  { label: "Catalan", value: "catalan" },
  { label: "Chechen", value: "chechen" },
  { label: "Chamorro", value: "chamorro" },
  { label: "Corsican", value: "corsican" },
  { label: "Cree", value: "cree" },
  { label: "Czech", value: "czech" },
  { label: "Church Slavic", value: "church-slavic" },
  { label: "Chuvash", value: "chuvash" },
  { label: "Welsh", value: "welsh" },
  { label: "Danish", value: "danish" },
  { label: "German", value: "german" },
  { label: "Maldivian", value: "maldivian" },
  { label: "Dzongkha", value: "dzongkha" },
  { label: "Ewe", value: "ewe" },
  { label: "Greek", value: "greek" },
  { label: "English", value: "english" },
  { label: "Esperanto", value: "esperanto" },
  { label: "Spanish", value: "spanish" },
  { label: "Estonian", value: "estonian" },
  { label: "Basque", value: "basque" },
  { label: "Persian", value: "persian" },
  { label: "Fulah", value: "fulah" },
  { label: "Finnish", value: "finnish" },
  { label: "Fijian", value: "fijian" },
  { label: "Faroese", value: "faroese" },
  { label: "French", value: "french" },
  { label: "Western Frisian", value: "western-frisian" },
  { label: "Irish", value: "irish" },
  { label: "Gaelic", value: "gaelic" },
  { label: "Galician", value: "galician" },
  { label: "Guarani", value: "guarani" },
  { label: "Gujarati", value: "gujarati" },
  { label: "Manx", value: "manx" },
  { label: "Hausa", value: "hausa" },
  { label: "Hebrew", value: "hebrew" },
  { label: "Hindi", value: "hindi" },
  { label: "Hiri Motu", value: "hiri-motu" },
  { label: "Croatian", value: "croatian" },
  { label: "Haitian", value: "haitian" },
  { label: "Hungarian", value: "hungarian" },
  { label: "Armenian", value: "armenian" },
  { label: "Herero", value: "herero" },
  { label: "Interlingua", value: "interlingua" },
  { label: "Indonesian", value: "indonesian" },
  { label: "Interlingue", value: "interlingue" },
  { label: "Igbo", value: "igbo" },
  { label: "Sichuan Yi", value: "sichuan-yi" },
  { label: "Inupiaq", value: "inupiaq" },
  { label: "Ido", value: "ido" },
  { label: "Icelandic", value: "icelandic" },
  { label: "Italian", value: "italian" },
  { label: "Inuktitut", value: "inuktitut" },
  { label: "Japanese", value: "japanese" },
  { label: "Javanese", value: "javanese" },
  { label: "Georgian", value: "georgian" },
  { label: "Kongo", value: "kongo" },
  { label: "Kikuyu", value: "kikuyu" },
  { label: "Kuanyama", value: "kuanyama" },
  { label: "Kazakh", value: "kazakh" },
  { label: "Kalaallisut", value: "kalaallisut" },
  { label: "Central Khmer", value: "central-khmer" },
  { label: "Kannada", value: "kannada" },
  { label: "Korean", value: "korean" },
  { label: "Kanuri", value: "kanuri" },
  { label: "Kashmiri", value: "kashmiri" },
  { label: "Kurdish", value: "kurdish" },
  { label: "Komi", value: "komi" },
  { label: "Cornish", value: "cornish" },
  { label: "Kirghiz", value: "kirghiz" },
  { label: "Latin", value: "latin" },
  { label: "Luxembourgish", value: "luxembourgish" },
  { label: "Ganda", value: "ganda" },
  { label: "Limburgan", value: "limburgan" },
  { label: "Lingala", value: "lingala" },
  { label: "Lao", value: "lao" },
  { label: "Lithuanian", value: "lithuanian" },
  { label: "Luba-Katanga", value: "katanga" },
  { label: "Latvian", value: "latvian" },
  { label: "Malagasy", value: "malagasy" },
  { label: "Marshallese", value: "marshallese" },
  { label: "Maori", value: "maori" },
  { label: "Macedonian", value: "macedonian" },
  { label: "Malayalam", value: "malayalam" },
  { label: "Mongolian", value: "mongolian" },
  { label: "Marathi", value: "marathi" },
  { label: "Malay", value: "malay" },
  { label: "Maltese", value: "maltese" },
  { label: "Burmese", value: "burmese" },
  { label: "Nauru", value: "nauru" },
  { label: "Norwegian", value: "norwegian" },
  { label: "North Ndebele", value: "north-ndebele" },
  { label: "Nepali", value: "nepali" },
  { label: "Ndonga", value: "ndonga" },
  { label: "Dutch", value: "dutch" },
  { label: "South Ndebele", value: "south-ndebele" },
  { label: "Navajo", value: "navajo" },
  { label: "Chichewa", value: "chichewa" },
  { label: "Occitan", value: "occitan" },
  { label: "Ojibwa", value: "ojibwa" },
  { label: "Oromo", value: "oromo" },
  { label: "Oriya", value: "oriya" },
  { label: "Ossetic", value: "ossetic" },
  { label: "Panjabi", value: "panjabi" },
  { label: "Pali", value: "pali" },
  { label: "Polish", value: "polish" },
  { label: "Pushto", value: "pushto" },
  { label: "Portuguese", value: "portuguese" },
  { label: "Quechua", value: "quechua" },
  { label: "Romansh", value: "romansh" },
  { label: "Rundi", value: "rundi" },
  { label: "Romanian", value: "romanian" },
  { label: "Russian", value: "russian" },
  { label: "Kinyarwanda", value: "kinyarwanda" },
  { label: "Sanskrit", value: "sanskrit" },
  { label: "Sardinian", value: "sardinian" },
  { label: "Sindhi", value: "sindhi" },
  { label: "Northern Sami", value: "northern-sami" },
  { label: "Sango", value: "sango" },
  { label: "Sinhala", value: "sinhala" },
  { label: "Slovak", value: "slovak" },
  { label: "Slovenian", value: "slovenian" },
  { label: "Samoan", value: "samoan" },
  { label: "Shona", value: "shona" },
  { label: "Somali", value: "somali" },
  { label: "Albanian", value: "albanian" },
  { label: "Serbian", value: "serbian" },
  { label: "Swati", value: "swati" },
  { label: "Sotho, Southern", value: "sotho-southern" },
  { label: "Sundanese", value: "sundanese" },
  { label: "Swedish", value: "swedish" },
  { label: "Swahili", value: "swahili" },
  { label: "Tamil", value: "tamil" },
  { label: "Telugu", value: "telugu" },
  { label: "Tajik", value: "tajik" },
  { label: "Thai", value: "thai" },
  { label: "Tigrinya", value: "tigrinya" },
  { label: "Turkmen", value: "turkmen" },
  { label: "Tagalog", value: "tagalog" },
  { label: "Tswana", value: "tswana" },
  { label: "Tonga", value: "tonga" },
  { label: "Turkish", value: "turkish" },
  { label: "Tsonga", value: "tsonga" },
  { label: "Tatar", value: "tatar" },
  { label: "Twi", value: "twi" },
  { label: "Tahitian", value: "tahitian" },
  { label: "Uighur", value: "uighur" },
  { label: "Ukrainian", value: "ukrainian" },
  { label: "Urdu", value: "urdu" },
  { label: "Uzbek", value: "uzbek" },
  { label: "Venda", value: "venda" },
  { label: "Vietnamese", value: "vietnamese" },
  { label: "Volapük", value: "volapük" },
  { label: "Walloon", value: "walloon" },
  { label: "Wolof", value: "wolof" },
  { label: "Xhosa", value: "xhosa" },
  { label: "Yiddish", value: "yiddish" },
  { label: "Yoruba", value: "yoruba" },
  { label: "Zhuang", value: "zhuang" },
  { label: "Chinese", value: "chinese" },
  { label: "Zulu", value: "zulu" },
];