export const ORGANIZATION_TYPE = [
  'Sponsors',
  'Investors',
  'Partners',
  'Supporters',
  'Promoters',
  'Organizers',
  'Media',
  'Government',
  'NGO',
  'Developers',
  'Distributors',
  'Retailers',
  'Manufacturers',
  'Suppliers',
  'Providers',
  'Recipients',
  'Others'
]

export const ORGANIZATION_INDUSTRY = [
  'Aerospace',
  'Agriculture',
  'AI & Machine Learning',
  'Apparel & Fashion',
  'Automotive',
  'Banking & Finance',
  'Betting & Gambling',
  'Blockchain & Crypto',
  'Chemicals',
  'Cloud Computing',
  'Construction',
  'Consulting',
  'Cybersecurity',
  'Data Analytics',
  'E-commerce',
  'Education',
  'Electronics',
  'Energy & Utilities',
  'Engineering',
  'Entertainment',
  'Environmental Services',
  'Esports & Gaming',
  'Event Management',
  'Fitness & Wellness',
  'Food & Beverage',
  'Government',
  'Healthcare',
  'Hospitality',
  'Human Resources',
  'Insurance',
  'Legal Services',
  'Logistics & Supply Chain',
  'Lubricants',
  'Luxury Goods',
  'Manufacturing',
  'Marketing & Advertising',
  'Materials Science',
  'Media & Broadcasting',
  'Mining',
  'Non-Profit',
  'Oil & Gas',
  'Pharmaceuticals',
  'Printing & Publishing',
  'Property',
  'Public Sector',
  'Railway',
  'Real Estate',
  'Retail',
  'Security',
  'Shipping',
  'Sports',
  'Telecommunications',
  'Textiles',
  'Tourism',
  'Transportation',
  'Utilities',
]


export const ORGANIZATION_PRESTIGE = [
  'Unknown',
  'Emerging',
  'Established',
  'Prestigious',
  'Iconic'
]

export const ORGANIZATION_IMPACT = [
  'Low',
  'Medium',
  'Deep',
  'Heavy',
  'Profound',
  'Rare',
  'Catastrophic',
  'Moderate',
  'Minor',
  'Negligible',
  'Major',
  'Severe',
  'Permanent',
  'Temporary'
]

export const SOCIAL_PLATFORMS = [
  'Twitter',
  'Instagram',
  'Facebook',
  'LinkedIn',
  'TikTok',
  'YouTube',
  'Twitch',
  'Discord',
  'Telegram',
  'WhatsApp'
]
