export const PRELOAD_CAR = (categoriesIds: number[]) => [
  {
    name: 'Red Bull Racing RB20 - 2024 Formula 1 Championship Car',
    toggle: 'advanced',
    type: categoriesIds[185],
    identifiers: {
      chassis: 'RB20',
      model: 'RB20',
      version: '2024.1',
      code: 'RBR-F1-2024',
    },
    basics: {
      enable: true,
      description: 'Ground-effect aerodynamic Formula 1 challenger featuring advanced hybrid powertrain, carbon fiber monocoque, and cutting-edge suspension geometry optimized for 2024 technical regulations.',
      visibility: { show: true },
    },
    details: {
      enable: true,
      visibility: { show: true },
    },
    traits: {
      enable: true,
      status: 'Active',
      visibility: { show: true },
    },
    assets: {
      enable: true,
      visibility: { show: true },
    },
    contexts: {
      enable: true,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'red-bull-racing-rb20-2024-formula-1-championship-car',
    visibility: { check_publish: true, check_featured: true, check_pinned: true },
  },
  {
    name: 'Mercedes-AMG F1 W15 E Performance - 2024 Championship Contender',
    toggle: 'advanced',
    type: categoriesIds[53],
    identifiers: {
      chassis: 'W15',
      model: 'W15 E Performance',
      version: '2024.2',
      code: 'MER-F1-2024',
    },
    basics: {
      enable: true,
      description: 'Zero-pod concept evolution featuring refined aerodynamic philosophy, optimized Mercedes-AMG F1 M15 E Performance power unit, and advanced driver cooling systems for competitive championship campaign.',
      visibility: { show: true },
    },
    details: {
      enable: true,
      visibility: { show: true },
    },
    traits: {
      enable: true,
      status: 'Active',
      visibility: { show: true },
    },
    assets: {
      enable: true,
      visibility: { show: true },
    },
    contexts: {
      enable: true,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'mercedes-amg-f1-w15-e-performance-2024-championship-contender',
    visibility: { check_publish: true, check_featured: true, check_pinned: false },
  },
  {
    name: 'Ferrari SF-24 - Scuderia Ferrari 2024 Formula 1 Car',
    toggle: 'advanced',
    type: categoriesIds[146],
    identifiers: {
      chassis: 'SF-24',
      model: 'SF-24',
      version: '2024.1',
      code: 'FER-F1-2024',
    },
    basics: {
      enable: true,
      description: 'Italian-engineered Formula 1 challenger featuring evolved sidepod concept, Ferrari 066/12 hybrid power unit, and refined aerodynamic package targeting championship contention at Maranello.',
      visibility: { show: true },
    },
    details: {
      enable: true,
      visibility: { show: true },
    },
    traits: {
      enable: true,
      status: 'Active',
      visibility: { show: true },
    },
    assets: {
      enable: true,
      visibility: { show: true },
    },
    contexts: {
      enable: true,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'ferrari-sf-24-scuderia-ferrari-2024-formula-1-car',
    visibility: { check_publish: true, check_featured: true, check_pinned: false },
  },
  {
    name: 'Porsche 963 LMDh - Factory WEC Hypercar Entry',
    toggle: 'advanced',
    type: categoriesIds[123],
    identifiers: {
      chassis: '963-001',
      model: '963 LMDh',
      version: '2024.Evo',
      code: 'POR-WEC-2024',
    },
    basics: {
      enable: true,
      description: 'Le Mans Daytona hybrid prototype featuring Porsche 9RD V8 twin-turbo engine, Bosch MGU system, and Multimatic chassis optimized for FIA WEC Hypercar class competition and IMSA GTP racing.',
      visibility: { show: true },
    },
    details: {
      enable: true,
      visibility: { show: true },
    },
    traits: {
      enable: true,
      status: 'Active',
      visibility: { show: true },
    },
    assets: {
      enable: true,
      visibility: { show: true },
    },
    contexts: {
      enable: true,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'porsche-963-lmdh-factory-wec-hypercar-entry',
    visibility: { check_publish: true, check_featured: true, check_pinned: false },
  },
  {
    name: 'Toyota GR010 Hybrid - Gazoo Racing WEC Hypercar',
    toggle: 'advanced',
    type: categoriesIds[38],
    identifiers: {
      chassis: 'GR010-03',
      model: 'GR010 Hybrid',
      version: '2024.Spec',
      code: 'TOY-WEC-2024',
    },
    basics: {
      enable: true,
      description: 'Japanese-engineered hybrid prototype featuring 3.5L V6 twin-turbo engine, front-axle MGU, and advanced energy management systems targeting Le Mans 24 Hours victory and WEC championship success.',
      visibility: { show: true },
    },
    details: {
      enable: true,
      visibility: { show: true },
    },
    traits: {
      enable: true,
      status: 'Active',
      visibility: { show: true },
    },
    assets: {
      enable: true,
      visibility: { show: true },
    },
    contexts: {
      enable: true,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'toyota-gr010-hybrid-gazoo-racing-wec-hypercar',
    visibility: { check_publish: true, check_featured: true, check_pinned: false },
  },
  {
    name: 'Ford Mustang GT3 - Multimatic Factory Racing Entry',
    toggle: 'advanced',
    type: categoriesIds[122],
    identifiers: {
      chassis: 'GT3-2024',
      model: 'Mustang GT3',
      version: '2024.1',
      code: 'FOR-GT3-2024',
    },
    basics: {
      enable: true,
      description: 'FIA GT3-homologated racing variant featuring 5.4L V8 naturally aspirated engine, sequential racing gearbox, and advanced aerodynamic package for global GT3 competition including IMSA, GT World Challenge, and Nürburgring 24h.',
      visibility: { show: true },
    },
    details: {
      enable: true,
      visibility: { show: true },
    },
    traits: {
      enable: true,
      status: 'Active',
      visibility: { show: true },
    },
    assets: {
      enable: true,
      visibility: { show: true },
    },
    contexts: {
      enable: true,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'ford-mustang-gt3-multimatic-factory-racing-entry',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    name: 'Toyota GR Yaris Rally1 - WRC Factory Hybrid Rally Car',
    toggle: 'advanced',
    type: categoriesIds[17],
    identifiers: {
      chassis: 'Rally1-2024',
      model: 'GR Yaris Rally1',
      version: '2024.Evo',
      code: 'TOY-WRC-2024',
    },
    basics: {
      enable: true,
      description: 'FIA Rally1-homologated hybrid rally car featuring 1.6L turbocharged engine, 100kW MGU system, and advanced suspension geometry optimized for gravel, tarmac, and snow conditions across WRC championship calendar.',
      visibility: { show: true },
    },
    details: {
      enable: true,
      visibility: { show: true },
    },
    traits: {
      enable: true,
      status: 'Active',
      visibility: { show: true },
    },
    assets: {
      enable: true,
      visibility: { show: true },
    },
    contexts: {
      enable: true,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'toyota-gr-yaris-rally1-wrc-factory-hybrid-rally-car',
    visibility: { check_publish: true, check_featured: true, check_pinned: false },
  },
  {
    name: 'Porsche 99X Electric Gen3 - Formula E Factory Entry',
    toggle: 'advanced',
    type: categoriesIds[245],
    identifiers: {
      chassis: '99X-Gen3',
      model: '99X Electric',
      version: 'Gen3.2024',
      code: 'POR-FE-2024',
    },
    basics: {
      enable: true,
      description: 'FIA Formula E Gen3 electric single-seater featuring 350kW powertrain, regenerative braking system, and advanced battery management optimized for street circuit racing and sustainable motorsport competition.',
      visibility: { show: true },
    },
    details: {
      enable: true,
      visibility: { show: true },
    },
    traits: {
      enable: true,
      status: 'Active',
      visibility: { show: true },
    },
    assets: {
      enable: true,
      visibility: { show: true },
    },
    contexts: {
      enable: true,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'porsche-99x-electric-gen3-formula-e-factory-entry',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    name: 'McLaren 720S GT3 EVO - Customer Racing Platform',
    toggle: 'advanced',
    type: categoriesIds[243],
    identifiers: {
      chassis: 'GT3-EVO-2024',
      model: '720S GT3 EVO',
      version: '2024.1',
      code: 'MCL-GT3-2024',
    },
    basics: {
      enable: true,
      description: 'FIA GT3-homologated evolution featuring McLaren M840T 4.0L twin-turbo V8, revised aerodynamic package, and enhanced driver aids for global GT3 customer racing programs and endurance competition.',
      visibility: { show: true },
    },
    details: {
      enable: true,
      visibility: { show: true },
    },
    traits: {
      enable: true,
      status: 'Active',
      visibility: { show: true },
    },
    assets: {
      enable: true,
      visibility: { show: true },
    },
    contexts: {
      enable: true,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'mclaren-720s-gt3-evo-customer-racing-platform',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    name: 'Audi R8 LMS GT3 EVO II - Customer Racing Specification',
    toggle: 'advanced',
    type: categoriesIds[52],
    identifiers: {
      chassis: 'R8-LMS-EVO2',
      model: 'R8 LMS GT3 EVO II',
      version: '2024.Spec',
      code: 'AUD-GT3-2024',
    },
    basics: {
      enable: true,
      description: 'FIA GT3-homologated racing variant featuring Audi 5.2L V10 naturally aspirated engine, sequential racing transmission, and refined aerodynamics for global GT3 customer competition and endurance racing.',
      visibility: { show: true },
    },
    details: {
      enable: true,
      visibility: { show: true },
    },
    traits: {
      enable: true,
      status: 'Active',
      visibility: { show: true },
    },
    assets: {
      enable: true,
      visibility: { show: true },
    },
    contexts: {
      enable: true,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'audi-r8-lms-gt3-evo-ii-customer-racing-specification',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    name: 'Hyundai i20 N Rally1 - Shell Mobis WRC Factory Car',
    toggle: 'advanced',
    type: categoriesIds[215],
    identifiers: {
      chassis: 'Rally1-Hyundai',
      model: 'i20 N Rally1',
      version: '2024.Evo',
      code: 'HYU-WRC-2024',
    },
    basics: {
      enable: true,
      description: 'FIA Rally1-homologated hybrid rally car featuring 1.6L turbocharged engine, 100kW MGU system, and advanced suspension geometry optimized for mixed-surface WRC competition and manufacturer championship contention.',
      visibility: { show: true },
    },
    details: {
      enable: true,
      visibility: { show: true },
    },
    traits: {
      enable: true,
      status: 'Active',
      visibility: { show: true },
    },
    assets: {
      enable: true,
      visibility: { show: true },
    },
    contexts: {
      enable: true,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'hyundai-i20-n-rally1-shell-mobis-wrc-factory-car',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    name: 'BMW M Hybrid V8 - LMDh Factory WEC/IMSA Entry',
    toggle: 'advanced',
    type: categoriesIds[232],
    identifiers: {
      chassis: 'M-Hybrid-V8-01',
      model: 'M Hybrid V8',
      version: '2024.1',
      code: 'BMW-LMDH-2024',
    },
    basics: {
      enable: true,
      description: 'Le Mans Daytona hybrid prototype featuring BMW P66/3 4.0L twin-turbo V8, Bosch MGU system, and Dallara chassis optimized for FIA WEC Hypercar class and IMSA GTP championship competition.',
      visibility: { show: true },
    },
    details: {
      enable: true,
      visibility: { show: true },
    },
    traits: {
      enable: true,
      status: 'Active',
      visibility: { show: true },
    },
    assets: {
      enable: true,
      visibility: { show: true },
    },
    contexts: {
      enable: true,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'bmw-m-hybrid-v8-lmdh-factory-wec-imsa-entry',
    visibility: { check_publish: true, check_featured: true, check_pinned: false },
  },
  {
    name: 'Cadillac V-Series.R - LMDh Factory WEC/IMSA Entry',
    toggle: 'advanced',
    type: categoriesIds[107],
    identifiers: {
      chassis: 'V-R-001',
      model: 'V-Series.R',
      version: '2024.Spec',
      code: 'CAD-LMDH-2024',
    },
    basics: {
      enable: true,
      description: 'American-engineered LMDh prototype featuring Cadillac 5.5L naturally aspirated V8, Bosch MGU system, and Dallara chassis targeting Le Mans 24 Hours victory and IMSA WeatherTech SportsCar Championship success.',
      visibility: { show: true },
    },
    details: {
      enable: true,
      visibility: { show: true },
    },
    traits: {
      enable: true,
      status: 'Active',
      visibility: { show: true },
    },
    assets: {
      enable: true,
      visibility: { show: true },
    },
    contexts: {
      enable: true,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'cadillac-v-series-r-lmdh-factory-wec-imsa-entry',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    name: 'Alpine A424 - LMDh Factory WEC Hypercar Entry',
    toggle: 'advanced',
    type: categoriesIds[126],
    identifiers: {
      chassis: 'A424-001',
      model: 'A424',
      version: '2024.1',
      code: 'ALP-LMDH-2024',
    },
    basics: {
      enable: true,
      description: 'French-engineered LMDh prototype featuring Alpine 3.5L V6 twin-turbo engine, Bosch MGU system, and Oreca chassis optimized for FIA WEC Hypercar class competition and Le Mans 24 Hours championship campaign.',
      visibility: { show: true },
    },
    details: {
      enable: true,
      visibility: { show: true },
    },
    traits: {
      enable: true,
      status: 'Active',
      visibility: { show: true },
    },
    assets: {
      enable: true,
      visibility: { show: true },
    },
    contexts: {
      enable: true,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'alpine-a424-lmdh-factory-wec-hypercar-entry',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    name: 'Lamborghini Huracán GT3 EVO2 - Squadra Corse Factory Entry',
    toggle: 'advanced',
    type: categoriesIds[41],
    identifiers: {
      chassis: 'GT3-EVO2-Lambo',
      model: 'Huracán GT3 EVO2',
      version: '2024.1',
      code: 'LAM-GT3-2024',
    },
    basics: {
      enable: true,
      description: 'FIA GT3-homologated racing variant featuring Lamborghini 5.2L V10 naturally aspirated engine, sequential racing gearbox, and advanced aerodynamic package for global GT3 customer racing and endurance competition.',
      visibility: { show: true },
    },
    details: {
      enable: true,
      visibility: { show: true },
    },
    traits: {
      enable: true,
      status: 'Active',
      visibility: { show: true },
    },
    assets: {
      enable: true,
      visibility: { show: true },
    },
    contexts: {
      enable: true,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'lamborghini-huracan-gt3-evo2-squadra-corse-factory-entry',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    name: 'Ferrari 296 GT3 - AF Corse Customer Racing Platform',
    toggle: 'advanced',
    type: categoriesIds[9],
    identifiers: {
      chassis: '296-GT3-2024',
      model: '296 GT3',
      version: '2024.Spec',
      code: 'FER-GT3-2024',
    },
    basics: {
      enable: true,
      description: 'FIA GT3-homologated racing variant featuring Ferrari 3.0L twin-turbo V6 hybrid powertrain, sequential racing transmission, and refined aerodynamics for global GT3 customer competition and endurance racing.',
      visibility: { show: true },
    },
    details: {
      enable: true,
      visibility: { show: true },
    },
    traits: {
      enable: true,
      status: 'Active',
      visibility: { show: true },
    },
    assets: {
      enable: true,
      visibility: { show: true },
    },
    contexts: {
      enable: true,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'ferrari-296-gt3-af-corse-customer-racing-platform',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    name: 'McLaren MCL38 - 2024 Formula 1 Development Car',
    toggle: 'advanced',
    type: categoriesIds[105],
    identifiers: {
      chassis: 'MCL38-DEV',
      model: 'MCL38',
      version: '2024.Dev',
      code: 'MCL-F1-DEV-2024',
    },
    basics: {
      enable: true,
      description: 'Formula 1 development mule featuring experimental aerodynamic components, test power unit configurations, and data acquisition systems for 2025 regulation research and performance optimization.',
      visibility: { show: true },
    },
    details: {
      enable: true,
      visibility: { show: true },
    },
    traits: {
      enable: true,
      status: 'Development',
      visibility: { show: true },
    },
    assets: {
      enable: true,
      visibility: { show: true },
    },
    contexts: {
      enable: true,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'mclaren-mcl38-2024-formula-1-development-car',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    name: 'Porsche 911 GT3 R Rennsport - Historic Racing Specification',
    toggle: 'advanced',
    type: categoriesIds[118],
    identifiers: {
      chassis: 'GT3R-Historic',
      model: '911 GT3 R Rennsport',
      version: 'Historic.Spec',
      code: 'POR-HIST-2024',
    },
    basics: {
      enable: true,
      description: 'Historic racing specification featuring period-correct 4.0L naturally aspirated flat-six, sequential racing gearbox, and authentic aerodynamic package for vintage endurance events and classic racing series.',
      visibility: { show: true },
    },
    details: {
      enable: true,
      visibility: { show: true },
    },
    traits: {
      enable: true,
      status: 'Museum',
      visibility: { show: true },
    },
    assets: {
      enable: true,
      visibility: { show: true },
    },
    contexts: {
      enable: true,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'porsche-911-gt3-r-rennsport-historic-racing-specification',
    visibility: { check_publish: true, check_featured: true, check_pinned: false },
  },
  {
    name: 'Mercedes-AMG ONE - Hypercar Road-Legal Prototype',
    toggle: 'advanced',
    type: categoriesIds[27],
    identifiers: {
      chassis: 'ONE-Prototype',
      model: 'AMG ONE',
      version: 'Prototype.2024',
      code: 'MER-CONCEPT-2024',
    },
    basics: {
      enable: true,
      description: 'Road-legal hypercar prototype featuring Formula 1-derived 1.6L turbocharged V6 hybrid powertrain, active aerodynamics, and advanced chassis technology representing pinnacle of Mercedes-AMG engineering.',
      visibility: { show: true },
    },
    details: {
      enable: true,
      visibility: { show: true },
    },
    traits: {
      enable: true,
      status: 'Prototype',
      visibility: { show: true },
    },
    assets: {
      enable: true,
      visibility: { show: true },
    },
    contexts: {
      enable: true,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'mercedes-amg-one-hypercar-road-legal-prototype',
    visibility: { check_publish: true, check_featured: true, check_pinned: false },
  },
  {
    name: 'Safety Car: Mercedes-AMG GT Black Series - F1 Official Vehicle',
    toggle: 'advanced',
    type: categoriesIds[166],
    identifiers: {
      chassis: 'SC-GT-Black',
      model: 'AMG GT Black Series',
      version: 'F1.SC.2024',
      code: 'MER-SC-F1-2024',
    },
    basics: {
      enable: true,
      description: 'Official Formula 1 Safety Car featuring Mercedes-AMG 4.0L twin-turbo V8, FIA-mandated safety equipment, and distinctive livery for track incident management and race control procedures during Grand Prix events.',
      visibility: { show: true },
    },
    details: {
      enable: true,
      visibility: { show: true },
    },
    traits: {
      enable: true,
      status: 'Active',
      visibility: { show: true },
    },
    assets: {
      enable: true,
      visibility: { show: true },
    },
    contexts: {
      enable: true,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'safety-car-mercedes-amg-gt-black-series-f1-official-vehicle',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
] as const
