// FILE: src/collections/Entities/Leader/seeders/preload.ts
export const PRELOAD_LEADER = [
  {
    first: 'Toto',
    middle: '',
    last: 'Wolff',
    alias: 'The Boss',
    toggle: 'advanced',
    type: 1,
    basics: {
      enable: true,
      description: 'CEO and Team Principal of Mercedes-AMG Petronas F1 Team',
      identifier: {
        designation: 'Team Principal',
        title: 'CEO',
        code: 'TW',
      },
      identity: {
        gender: 'Male',
        pronouns: 'he/him',
        age: '53',
        nationality: 'Austrian',
      },
      chronology: {
        birth: '1972-01-12',
        debut: '2013-01-01',
        retirement: null,
      },
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'toto-wolff',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    first: 'Zak',
    middle: '',
    last: 'Brown',
    alias: 'ZB',
    toggle: 'advanced',
    type: 2,
    basics: {
      enable: true,
      description: 'CEO of McLaren Racing',
      identifier: {
        designation: 'CEO',
        title: 'Chief Executive Officer',
        code: 'ZB',
      },
      identity: {
        gender: 'Male',
        pronouns: 'he/him',
        age: '52',
        nationality: 'American',
      },
      chronology: {
        birth: '1971-11-07',
        debut: '2016-11-01',
        retirement: null,
      },
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'zak-brown',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    first: 'Stefano',
    middle: '',
    last: 'Domenicali',
    alias: 'SD',
    toggle: 'advanced',
    type: 3,
    basics: {
      enable: true,
      description: 'President and CEO of Formula 1 Group',
      identifier: {
        designation: 'President',
        title: 'CEO',
        code: 'SD',
      },
      identity: {
        gender: 'Male',
        pronouns: 'he/him',
        age: '58',
        nationality: 'Italian',
      },
      chronology: {
        birth: '1965-05-14',
        debut: '2021-01-01',
        retirement: null,
      },
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'stefano-domenicali',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
] as const
