// FILE: src/collections/Entities/Individual/seeders/preload.ts
export const PRELOAD_INDIVIDUAL = [
  {
    first: 'Adrian',
    middle: '',
    last: 'Newey',
    alias: 'The Genius',
    toggle: 'advanced',
    type: 1,
    basics: {
      enable: true,
      description: 'Legendary F1 car designer',
      identifier: {
        nickname: 'Ady',
        code: 'AN',
        number: '',
      },
      identity: {
        gender: 'Male',
        pronouns: 'he/him',
        age: '65',
        nationality: 'British',
      },
      visibility: { show: true },
    },
    details: {
      enable: true,
      background: 'Chief Technical Officer at Red Bull Racing, designed multiple championship-winning cars.',
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'adrian-newey',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    first: 'Ross',
    middle: '',
    last: 'Brawn',
    alias: '',
    toggle: 'advanced',
    type: 2,
    basics: {
      enable: true,
      description: 'Former F1 team principal and technical director',
      identifier: {
        nickname: 'Ross',
        code: 'RB',
        number: '',
      },
      identity: {
        gender: 'Male',
        pronouns: 'he/him',
        age: '70',
        nationality: 'British',
      },
      visibility: { show: true },
    },
    details: {
      enable: true,
      background: 'Led Brawn GP to championship in 2009, former F1 managing director.',
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'ross-brawn',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    first: 'Christian',
    middle: '',
    last: 'Horner',
    alias: 'CH',
    toggle: 'advanced',
    type: 3,
    basics: {
      enable: true,
      description: 'Red Bull Racing team principal',
      identifier: {
        nickname: 'Chris',
        code: 'CH',
        number: '',
      },
      identity: {
        gender: 'Male',
        pronouns: 'he/him',
        age: '50',
        nationality: 'British',
      },
      visibility: { show: true },
    },
    details: {
      enable: true,
      background: 'Youngest team principal in F1 history, led Red Bull to multiple titles.',
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'christian-horner',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
] as const
