// FILE: src/collections/Entities/Individual/seeders/preload.ts
export const PRELOAD_INDIVIDUAL = (categoriesIds: number[]) => [
  {
    first: 'Adrian',
    middle: '',
    last: 'Newey',
    alias: 'The Genius',
    toggle: 'advanced',
    type: categoriesIds[185],
    basics: {
      enable: true,
      description: 'Legendary Formula 1 aerodynamicist and car designer with multiple championship-winning designs.',
      identifier: { nickname: 'Ady', code: 'AN-DES', number: '' },
      identity: { gender: 'Male', pronouns: 'he/him', age: '65', nationality: 'British' },
      visibility: { show: true }
    },
    details: { enable: true, background: 'Chief Technical Officer with career spanning Williams, McLaren, and Red Bull Racing. Designed championship-winning cars across multiple decades and regulatory eras.', interests: [], visibility: { show: true } },
    traits: { enable: true, channels: [], influence: { reach: 'Global', authority: 'High', network: 'Extensive' }, benefits: [], visibility: { show: true } },
    assets: { enable: true, avatar: null, gallery: null, visibility: { show: true } },
    contexts: { enable: true, history: null, notes: [], visibility: { show: true } },
    seo: { title: 'Adrian Newey Profile | AF Motorsport', description: 'Profile of legendary F1 designer Adrian Newey' },
    generateSlug: false, slug: 'adrian-newey',
    visibility: { check_publish: true, check_featured: true, check_pinned: true }
  },
  {
    first: 'Martin',
    middle: '',
    last: 'Brundle',
    alias: 'The Commentator',
    toggle: 'advanced',
    type: categoriesIds[53],
    basics: {
      enable: true,
      description: 'Former Formula 1 driver and renowned motorsport commentator and journalist.',
      identifier: { nickname: 'Brundle', code: 'MB-JRN', number: '' },
      identity: { gender: 'Male', pronouns: 'he/him', age: '65', nationality: 'British' },
      visibility: { show: true }
    },
    details: { enable: true, background: 'Former F1 driver turned broadcaster. Known for grid walk interviews and insightful technical commentary across multiple racing series.', interests: [], visibility: { show: true } },
    traits: { enable: true, channels: [], influence: { reach: 'Global', authority: 'High', network: 'Extensive' }, benefits: [], visibility: { show: true } },
    assets: { enable: true, avatar: null, gallery: null, visibility: { show: true } },
    contexts: { enable: true, history: null, notes: [], visibility: { show: true } },
    seo: { title: 'Martin Brundle Profile | AF Motorsport', description: 'Profile of motorsport commentator and journalist Martin Brundle' },
    generateSlug: false, slug: 'martin-brundle',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    first: 'Susie',
    middle: '',
    last: 'Wolff',
    alias: 'The Leader',
    toggle: 'advanced',
    type: categoriesIds[146],
    basics: {
      enable: true,
      description: 'Former racing driver and influential motorsport executive advocating for diversity and inclusion.',
      identifier: { nickname: 'Susie', code: 'SW-INF', number: '' },
      identity: { gender: 'Female', pronouns: 'she/her', age: '41', nationality: 'Austrian' },
      visibility: { show: true }
    },
    details: { enable: true, background: 'Former DTM and Formula 3 driver. Managing Director of Williams F1 Team and founder of Dare to be Different initiative promoting women in motorsport.', interests: [], visibility: { show: true } },
    traits: { enable: true, channels: [], influence: { reach: 'Global', authority: 'High', network: 'Vast' }, benefits: [], visibility: { show: true } },
    assets: { enable: true, avatar: null, gallery: null, visibility: { show: true } },
    contexts: { enable: true, history: null, notes: [], visibility: { show: true } },
    seo: { title: 'Susie Wolff Profile | AF Motorsport', description: 'Profile of motorsport executive and diversity advocate Susie Wolff' },
    generateSlug: false, slug: 'susie-wolff',
    visibility: { check_publish: true, check_featured: true, check_pinned: true }
  },
  {
    first: 'David',
    middle: '',
    last: 'Coulthard',
    alias: 'DC',
    toggle: 'advanced',
    type: categoriesIds[123],
    basics: {
      enable: true,
      description: 'Former Formula 1 race winner and influential media personality and commentator.',
      identifier: { nickname: 'DC', code: 'DC-INF', number: '' },
      identity: { gender: 'Male', pronouns: 'he/him', age: '53', nationality: 'British' },
      visibility: { show: true }
    },
    details: { enable: true, background: '13-time Grand Prix winner with Williams and McLaren. Now prominent broadcaster, commentator, and motorsport ambassador across global media platforms.', interests: [], visibility: { show: true } },
    traits: { enable: true, channels: [], influence: { reach: 'Global', authority: 'High', network: 'Extensive' }, benefits: [], visibility: { show: true } },
    assets: { enable: true, avatar: null, gallery: null, visibility: { show: true } },
    contexts: { enable: true, history: null, notes: [], visibility: { show: true } },
    seo: { title: 'David Coulthard Profile | AF Motorsport', description: 'Profile of former F1 driver and media personality David Coulthard' },
    generateSlug: false, slug: 'david-coulthard',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    first: 'Mark',
    middle: '',
    last: 'Webber',
    alias: 'Webber',
    toggle: 'advanced',
    type: categoriesIds[38],
    basics: {
      enable: true,
      description: 'Former Formula 1 race winner and WEC champion, now influential commentator and ambassador.',
      identifier: { nickname: 'Marko', code: 'MW-INF', number: '' },
      identity: { gender: 'Male', pronouns: 'he/him', age: '48', nationality: 'Australian' },
      visibility: { show: true }
    },
    details: { enable: true, background: 'Nine-time Grand Prix winner with Red Bull Racing. Le Mans and WEC champion. Now F1 commentator and motorsport ambassador with global media presence.', interests: [], visibility: { show: true } },
    traits: { enable: true, channels: [], influence: { reach: 'Global', authority: 'High', network: 'Extensive' }, benefits: [], visibility: { show: true } },
    assets: { enable: true, avatar: null, gallery: null, visibility: { show: true } },
    contexts: { enable: true, history: null, notes: [], visibility: { show: true } },
    seo: { title: 'Mark Webber Profile | AF Motorsport', description: 'Profile of former F1 and WEC champion Mark Webber' },
    generateSlug: false, slug: 'mark-webber',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    first: 'Niki',
    middle: '',
    last: 'Lauda',
    alias: 'The Rat',
    toggle: 'advanced',
    type: categoriesIds[122],
    basics: {
      enable: true,
      description: 'Three-time Formula 1 World Champion and legendary figure in motorsport history.',
      identifier: { nickname: 'Niki', code: 'NL-LEG', number: '' },
      identity: { gender: 'Male', pronouns: 'he/him', age: '70', nationality: 'Austrian' },
      chronology: { birth: '1949-02-22', debut: null, retirement: '1985-11-03' },
      visibility: { show: true }
    },
    details: { enable: true, background: 'Three-time World Champion known for remarkable comeback after 1976 Nürburgring crash. Later served as Mercedes F1 non-executive chairman and aviation entrepreneur.', interests: [], visibility: { show: true } },
    traits: { enable: true, channels: [], influence: { reach: 'Global', authority: 'High', network: 'Vast' }, benefits: [], visibility: { show: true } },
    assets: { enable: true, avatar: null, gallery: null, visibility: { show: true } },
    contexts: { enable: true, history: null, notes: [], visibility: { show: true } },
    seo: { title: 'Niki Lauda Profile | AF Motorsport', description: 'Profile of three-time F1 World Champion and legend Niki Lauda' },
    generateSlug: false, slug: 'niki-lauda',
    visibility: { check_publish: true, check_featured: false, check_pinned: true }
  },
  {
    first: 'Murray',
    middle: '',
    last: 'Walker',
    alias: 'The Voice of F1',
    toggle: 'advanced',
    type: categoriesIds[17],
    basics: {
      enable: true,
      description: 'Iconic Formula 1 commentator whose voice defined generations of motorsport broadcasting.',
      identifier: { nickname: 'Murray', code: 'MW-COM', number: '' },
      identity: { gender: 'Male', pronouns: 'he/him', age: '97', nationality: 'British' },
      chronology: { birth: '1923-10-10', debut: null, retirement: '2001-10-14' },
      visibility: { show: true }
    },
    details: { enable: true, background: 'Commentated on Formula 1 for over four decades. Known for enthusiastic delivery and memorable "Murrayisms". Received OBE for services to motorsport broadcasting.', interests: [], visibility: { show: true } },
    traits: { enable: true, channels: [], influence: { reach: 'Global', authority: 'High', network: 'Extensive' }, benefits: [], visibility: { show: true } },
    assets: { enable: true, avatar: null, gallery: null, visibility: { show: true } },
    contexts: { enable: true, history: null, notes: [], visibility: { show: true } },
    seo: { title: 'Murray Walker Profile | AF Motorsport', description: 'Profile of iconic F1 commentator Murray Walker' },
    generateSlug: false, slug: 'murray-walker',
    visibility: { check_publish: true, check_featured: false, check_pinned: true }
  },
  {
    first: 'Bernie',
    middle: '',
    last: 'Ecclestone',
    alias: 'The Supremo',
    toggle: 'advanced',
    type: categoriesIds[245],
    basics: {
      enable: true,
      description: 'Former Formula 1 commercial rights holder who transformed the sport into a global entertainment phenomenon.',
      identifier: { nickname: 'Bernie', code: 'BE-EXE', number: '' },
      identity: { gender: 'Male', pronouns: 'he/him', age: '94', nationality: 'British' },
      visibility: { show: true }
    },
    details: { enable: true, background: 'Led Formula 1 commercial operations for four decades. Pioneered global broadcasting deals, calendar expansion, and commercial growth of the sport.', interests: [], visibility: { show: true } },
    traits: { enable: true, channels: [], influence: { reach: 'Global', authority: 'High', network: 'Vast' }, benefits: [], visibility: { show: true } },
    assets: { enable: true, avatar: null, gallery: null, visibility: { show: true } },
    contexts: { enable: true, history: null, notes: [], visibility: { show: true } },
    seo: { title: 'Bernie Ecclestone Profile | AF Motorsport', description: 'Profile of former F1 commercial chief Bernie Ecclestone' },
    generateSlug: false, slug: 'bernie-ecclestone',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    first: 'Jean',
    middle: '',
    last: 'Todt',
    alias: 'The Diplomat',
    toggle: 'advanced',
    type: categoriesIds[243],
    basics: {
      enable: true,
      description: 'Former FIA President and Ferrari team principal who shaped modern motorsport governance.',
      identifier: { nickname: 'Jean', code: 'JT-GOV', number: '' },
      identity: { gender: 'Male', pronouns: 'he/him', age: '78', nationality: 'French' },
      visibility: { show: true }
    },
    details: { enable: true, background: 'Led Ferrari to multiple championships as team principal. Served as FIA President implementing safety initiatives and global motorsport development programs.', interests: [], visibility: { show: true } },
    traits: { enable: true, channels: [], influence: { reach: 'Global', authority: 'High', network: 'Vast' }, benefits: [], visibility: { show: true } },
    assets: { enable: true, avatar: null, gallery: null, visibility: { show: true } },
    contexts: { enable: true, history: null, notes: [], visibility: { show: true } },
    seo: { title: 'Jean Todt Profile | AF Motorsport', description: 'Profile of former FIA President and Ferrari principal Jean Todt' },
    generateSlug: false, slug: 'jean-todt',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    first: 'Ross',
    middle: '',
    last: 'Brawn',
    alias: 'The Strategist',
    toggle: 'advanced',
    type: categoriesIds[52],
    basics: {
      enable: true,
      description: 'Championship-winning team principal and F1 Managing Director who shaped modern technical regulations.',
      identifier: { nickname: 'Ross', code: 'RB-EXE', number: '' },
      identity: { gender: 'Male', pronouns: 'he/him', age: '70', nationality: 'British' },
      visibility: { show: true }
    },
    details: { enable: true, background: 'Led Benetton, Ferrari, and Brawn GP to championships. Served as F1 Managing Director overseeing technical regulation development and sporting governance.', interests: [], visibility: { show: true } },
    traits: { enable: true, channels: [], influence: { reach: 'Global', authority: 'High', network: 'Extensive' }, benefits: [], visibility: { show: true } },
    assets: { enable: true, avatar: null, gallery: null, visibility: { show: true } },
    contexts: { enable: true, history: null, notes: [], visibility: { show: true } },
    seo: { title: 'Ross Brawn Profile | AF Motorsport', description: 'Profile of championship-winning strategist and F1 executive Ross Brawn' },
    generateSlug: false, slug: 'ross-brawn',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    first: 'Toto',
    middle: '',
    last: 'Wolff',
    alias: 'The Principal',
    toggle: 'advanced',
    type: categoriesIds[215],
    basics: {
      enable: true,
      description: 'Mercedes-AMG Petronas Team Principal and shareholder driving championship success.',
      identifier: { nickname: 'Toto', code: 'TW-PRN', number: '' },
      identity: { gender: 'Male', pronouns: 'he/him', age: '52', nationality: 'Austrian' },
      visibility: { show: true }
    },
    details: { enable: true, background: 'Former racing driver turned team principal. Led Mercedes to eight consecutive constructors championships. Influential voice in F1 governance and strategy.', interests: [], visibility: { show: true } },
    traits: { enable: true, channels: [], influence: { reach: 'Global', authority: 'High', network: 'Extensive' }, benefits: [], visibility: { show: true } },
    assets: { enable: true, avatar: null, gallery: null, visibility: { show: true } },
    contexts: { enable: true, history: null, notes: [], visibility: { show: true } },
    seo: { title: 'Toto Wolff Profile | AF Motorsport', description: 'Profile of Mercedes Team Principal and F1 executive Toto Wolff' },
    generateSlug: false, slug: 'toto-wolff',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    first: 'Christian',
    middle: '',
    last: 'Horner',
    alias: 'The Boss',
    toggle: 'advanced',
    type: categoriesIds[232],
    basics: {
      enable: true,
      description: 'Red Bull Racing Team Principal leading multiple championship-winning campaigns.',
      identifier: { nickname: 'CH', code: 'CH-PRN', number: '' },
      identity: { gender: 'Male', pronouns: 'he/him', age: '51', nationality: 'British' },
      visibility: { show: true }
    },
    details: { enable: true, background: 'Longest-serving team principal in current F1 grid. Led Red Bull to multiple constructors and drivers championships. Influential voice in technical regulation discussions.', interests: [], visibility: { show: true } },
    traits: { enable: true, channels: [], influence: { reach: 'Global', authority: 'High', network: 'Extensive' }, benefits: [], visibility: { show: true } },
    assets: { enable: true, avatar: null, gallery: null, visibility: { show: true } },
    contexts: { enable: true, history: null, notes: [], visibility: { show: true } },
    seo: { title: 'Christian Horner Profile | AF Motorsport', description: 'Profile of Red Bull Racing Team Principal Christian Horner' },
    generateSlug: false, slug: 'christian-horner',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    first: 'Frederic',
    middle: '',
    last: 'Vasseur',
    alias: 'The Revitalizer',
    toggle: 'advanced',
    type: categoriesIds[107],
    basics: {
      enable: true,
      description: 'Ferrari Team Principal leading the iconic team\'s championship resurgence.',
      identifier: { nickname: 'Fred', code: 'FV-PRN', number: '' },
      identity: { gender: 'Male', pronouns: 'he/him', age: '56', nationality: 'French' },
      visibility: { show: true }
    },
    details: { enable: true, background: 'Former ART Grand Prix and Alfa Romeo team principal. Appointed Ferrari Team Principal to lead technical and organizational revitalization program.', interests: [], visibility: { show: true } },
    traits: { enable: true, channels: [], influence: { reach: 'Global', authority: 'High', network: 'Extensive' }, benefits: [], visibility: { show: true } },
    assets: { enable: true, avatar: null, gallery: null, visibility: { show: true } },
    contexts: { enable: true, history: null, notes: [], visibility: { show: true } },
    seo: { title: 'Frederic Vasseur Profile | AF Motorsport', description: 'Profile of Ferrari Team Principal Frederic Vasseur' },
    generateSlug: false, slug: 'frederic-vasseur',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    first: 'Zak',
    middle: '',
    last: 'Brown',
    alias: 'The CEO',
    toggle: 'advanced',
    type: categoriesIds[126],
    basics: {
      enable: true,
      description: 'McLaren Racing CEO driving organizational transformation and competitive resurgence.',
      identifier: { nickname: 'Zak', code: 'ZB-CEO', number: '' },
      identity: { gender: 'Male', pronouns: 'he/him', age: '53', nationality: 'American' },
      visibility: { show: true }
    },
    details: { enable: true, background: 'Former marketing executive turned racing CEO. Led McLaren\'s organizational restructuring and competitive revival across multiple racing series.', interests: [], visibility: { show: true } },
    traits: { enable: true, channels: [], influence: { reach: 'Global', authority: 'High', network: 'Extensive' }, benefits: [], visibility: { show: true } },
    assets: { enable: true, avatar: null, gallery: null, visibility: { show: true } },
    contexts: { enable: true, history: null, notes: [], visibility: { show: true } },
    seo: { title: 'Zak Brown Profile | AF Motorsport', description: 'Profile of McLaren Racing CEO Zak Brown' },
    generateSlug: false, slug: 'zak-brown',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    first: 'Guenther',
    middle: '',
    last: 'Steiner',
    alias: 'The Straight Talker',
    toggle: 'advanced',
    type: categoriesIds[41],
    basics: {
      enable: true,
      description: 'Former Haas F1 Team Principal known for candid leadership and reality TV fame.',
      identifier: { nickname: 'Guenther', code: 'GS-PRN', number: '' },
      identity: { gender: 'Male', pronouns: 'he/him', age: '59', nationality: 'Italian-American' },
      visibility: { show: true }
    },
    details: { enable: true, background: 'Led Haas F1 Team from founding through competitive midfield campaigns. Gained global recognition through Drive to Survive documentary series.', interests: [], visibility: { show: true } },
    traits: { enable: true, channels: [], influence: { reach: 'Global', authority: 'Medium', network: 'Extensive' }, benefits: [], visibility: { show: true } },
    assets: { enable: true, avatar: null, gallery: null, visibility: { show: true } },
    contexts: { enable: true, history: null, notes: [], visibility: { show: true } },
    seo: { title: 'Guenther Steiner Profile | AF Motorsport', description: 'Profile of former Haas F1 Team Principal Guenther Steiner' },
    generateSlug: false, slug: 'guenther-steiner',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    first: 'Claire',
    middle: '',
    last: 'Williams',
    alias: 'The Deputy',
    toggle: 'advanced',
    type: categoriesIds[9],
    basics: {
      enable: true,
      description: 'Former Williams F1 Deputy Team Principal and motorsport governance advocate.',
      identifier: { nickname: 'Claire', code: 'CW-DEP', number: '' },
      identity: { gender: 'Female', pronouns: 'she/her', age: '42', nationality: 'British' },
      visibility: { show: true }
    },
    details: { enable: true, background: 'Led Williams F1 Team through challenging competitive period. Advocate for diversity and inclusion in motorsport. Member of F1 Strategy Group.', interests: [], visibility: { show: true } },
    traits: { enable: true, channels: [], influence: { reach: 'Global', authority: 'Medium', network: 'Extensive' }, benefits: [], visibility: { show: true } },
    assets: { enable: true, avatar: null, gallery: null, visibility: { show: true } },
    contexts: { enable: true, history: null, notes: [], visibility: { show: true } },
    seo: { title: 'Claire Williams Profile | AF Motorsport', description: 'Profile of former Williams F1 Deputy Team Principal Claire Williams' },
    generateSlug: false, slug: 'claire-williams',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    first: 'Monisha',
    middle: '',
    last: 'Kaltenborn',
    alias: 'The Pioneer',
    toggle: 'advanced',
    type: categoriesIds[105],
    basics: {
      enable: true,
      description: 'Former Sauber F1 Team Principal and first female team principal in Formula 1 history.',
      identifier: { nickname: 'Monisha', code: 'MK-PRN', number: '' },
      identity: { gender: 'Female', pronouns: 'she/her', age: '53', nationality: 'Austrian-Indian' },
      visibility: { show: true }
    },
    details: { enable: true, background: 'First female team principal in Formula 1. Led Sauber through multiple competitive campaigns. Advocate for women in motorsport leadership roles.', interests: [], visibility: { show: true } },
    traits: { enable: true, channels: [], influence: { reach: 'Global', authority: 'Medium', network: 'Extensive' }, benefits: [], visibility: { show: true } },
    assets: { enable: true, avatar: null, gallery: null, visibility: { show: true } },
    contexts: { enable: true, history: null, notes: [], visibility: { show: true } },
    seo: { title: 'Monisha Kaltenborn Profile | AF Motorsport', description: 'Profile of former Sauber F1 Team Principal Monisha Kaltenborn' },
    generateSlug: false, slug: 'monisha-kaltenborn',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    first: 'Otmar',
    middle: '',
    last: 'Szafnauer',
    alias: 'The Operator',
    toggle: 'advanced',
    type: categoriesIds[118],
    basics: {
      enable: true,
      description: 'Experienced F1 executive with leadership roles across multiple championship-winning teams.',
      identifier: { nickname: 'Otmar', code: 'OS-EXE', number: '' },
      identity: { gender: 'Male', pronouns: 'he/him', age: '60', nationality: 'American-Austrian' },
      visibility: { show: true }
    },
    details: { enable: true, background: 'Led operational functions at Jordan, Midland, Force India, Racing Point, and Aston Martin. Known for organizational efficiency and resource optimization.', interests: [], visibility: { show: true } },
    traits: { enable: true, channels: [], influence: { reach: 'Global', authority: 'Medium', network: 'Extensive' }, benefits: [], visibility: { show: true } },
    assets: { enable: true, avatar: null, gallery: null, visibility: { show: true } },
    contexts: { enable: true, history: null, notes: [], visibility: { show: true } },
    seo: { title: 'Otmar Szafnauer Profile | AF Motorsport', description: 'Profile of experienced F1 executive Otmar Szafnauer' },
    generateSlug: false, slug: 'otmar-szafnauer',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    first: 'Andreas',
    middle: '',
    last: 'Seidl',
    alias: 'The Engineer',
    toggle: 'advanced',
    type: categoriesIds[27],
    basics: {
      enable: true,
      description: 'Former McLaren Team Principal and current Porsche Motorsport executive.',
      identifier: { nickname: 'Andreas', code: 'AS-EXE', number: '' },
      identity: { gender: 'Male', pronouns: 'he/him', age: '48', nationality: 'German' },
      visibility: { show: true }
    },
    details: { enable: true, background: 'Led McLaren F1 Team organizational transformation. Former Porsche LMP1 team principal. Now leading Porsche\'s motorsport strategy and technical development.', interests: [], visibility: { show: true } },
    traits: { enable: true, channels: [], influence: { reach: 'Global', authority: 'High', network: 'Extensive' }, benefits: [], visibility: { show: true } },
    assets: { enable: true, avatar: null, gallery: null, visibility: { show: true } },
    contexts: { enable: true, history: null, notes: [], visibility: { show: true } },
    seo: { title: 'Andreas Seidl Profile | AF Motorsport', description: 'Profile of Porsche Motorsport executive and former McLaren principal Andreas Seidl' },
    generateSlug: false, slug: 'andreas-seidl',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    first: 'James',
    middle: '',
    last: 'Allison',
    alias: 'The Technical Director',
    toggle: 'advanced',
    type: categoriesIds[166],
    basics: {
      enable: true,
      description: 'Championship-winning technical director and aerodynamicist across multiple F1 teams.',
      identifier: { nickname: 'James', code: 'JA-TD', number: '' },
      identity: { gender: 'Male', pronouns: 'he/him', age: '56', nationality: 'British' },
      visibility: { show: true }
    },
    details: { enable: true, background: 'Led technical departments at Ferrari, Lotus, and Mercedes to multiple championships. Renowned for aerodynamic innovation and technical leadership.', interests: [], visibility: { show: true } },
    traits: { enable: true, channels: [], influence: { reach: 'Global', authority: 'High', network: 'Extensive' }, benefits: [], visibility: { show: true } },
    assets: { enable: true, avatar: null, gallery: null, visibility: { show: true } },
    contexts: { enable: true, history: null, notes: [], visibility: { show: true } },
    seo: { title: 'James Allison Profile | AF Motorsport', description: 'Profile of championship-winning technical director James Allison' },
    generateSlug: false, slug: 'james-allison',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  }
] as const;
