// FILE: src/collections/Entities/Member/seeders/preload.ts
export const PRELOAD_MEMBER = [
  {
    first: 'James',
    middle: '',
    last: 'Allison',
    alias: 'JA',
    toggle: 'advanced',
    type: 1,
    basics: {
      enable: true,
      description: 'Mercedes Technical Director',
      identifier: {
        number: '001',
        nickname: 'J',
        callsign: '',
        badge: 'TD',
      },
      identity: {
        gender: 'Male',
        pronouns: 'he/him',
        age: '55',
        nationality: 'British',
      },
      chronology: {
        birth: '1968-02-22',
        debut: '2017-03-01',
        retirement: null,
      },
      visibility: { show: true },
    },
    details: {
      enable: true,
      background: 'Former Ferrari chassis director, joined Mercedes in 2017.',
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'james-allison',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    first: 'Andrew',
    middle: '',
    last: 'Shovlin',
    alias: 'Shov',
    toggle: 'advanced',
    type: 2,
    basics: {
      enable: true,
      description: 'Mercedes Trackside Engineering Director',
      identifier: {
        number: '002',
        nickname: 'Shov',
        callsign: '',
        badge: 'TED',
      },
      identity: {
        gender: 'Male',
        pronouns: 'he/him',
        age: '50',
        nationality: 'British',
      },
      chronology: {
        birth: '1973-11-04',
        debut: '2000-01-01',
        retirement: null,
      },
      visibility: { show: true },
    },
    details: {
      enable: true,
      background: 'Long-time Mercedes engineer, leads trackside operations.',
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'andrew-shovlin',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    first: 'Günther',
    middle: '',
    last: 'Steiner',
    alias: 'GS',
    toggle: 'advanced',
    type: 3,
    basics: {
      enable: true,
      description: 'Former Haas F1 Team Principal',
      identifier: {
        number: '003',
        nickname: 'Gunther',
        callsign: '',
        badge: 'TP',
      },
      identity: {
        gender: 'Male',
        pronouns: 'he/him',
        age: '58',
        nationality: 'Italian',
      },
      chronology: {
        birth: '1965-04-07',
        debut: '2016-01-01',
        retirement: '2024-01-10',
      },
      visibility: { show: true },
    },
    details: {
      enable: true,
      background: 'Founded Haas F1 Team and led it from 2016 to 2024.',
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'gunther-steiner',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
] as const
