// FILE: src/collections/Competition/Session/seeders/preload.ts
export const PRELOAD_SESSION = (categoriesIds: number[]) => [
  {
    name: 'Free Practice Session - Standard Format',
    alias: 'FP',
    code: 'FP-STD',
    toggle: 'advanced',
    type: categoriesIds[185],
    basics: { enable: true, description: 'Standard free practice session format for driver acclimatization and setup development.', status: 'Completed', access: 'Public', visibility: { show: true } },
    details: { enable: true, event: 1, format: { segment: 'Practice', duration: 60, interval: 0, specification: 'Standard FP session with unlimited tire sets' }, classifications: [], features: [], protocols: [], strategies: [], visibility: { show: true } },
    traits: { enable: true, constraints: [], parameters: [], specifications: [], visibility: { show: true } },
    metrics: { enable: true, quantifiers: { laps: 30, distance: '150 km', duration: '60 min' }, visibility: { show: true } },
    assets: { enable: true, gallery: null, playlist: null, visibility: { show: true } },
    contexts: { enable: true, highlights: [], incidents: [], authorities: [], participants: [], crews: [], entities: [], insights: [], visibility: { show: true } },
    seo: { title: 'Free Practice Session Template | AF Motorsport', description: 'Standard free practice session format for motorsport events' },
    generateSlug: false, slug: 'free-practice-session-standard',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Qualifying Session - Knockout Format',
    alias: 'Q',
    code: 'Q-KO',
    toggle: 'advanced',
    type: categoriesIds[53],
    basics: { enable: true, description: 'Knockout-style qualifying session determining grid positions.', status: 'Completed', access: 'Public', visibility: { show: true } },
    details: { enable: true, event: 1, format: { segment: 'Qualifying', duration: 45, interval: 15, specification: 'Q1/Q2/Q3 elimination format' }, classifications: [], features: [], protocols: [], strategies: [], visibility: { show: true } },
    traits: { enable: true, constraints: [], parameters: [], specifications: [], visibility: { show: true } },
    metrics: { enable: true, quantifiers: { laps: 12, distance: '60 km', duration: '45 min' }, visibility: { show: true } },
    assets: { enable: true, gallery: null, playlist: null, visibility: { show: true } },
    contexts: { enable: true, highlights: [], incidents: [], authorities: [], participants: [], crews: [], entities: [], insights: [], visibility: { show: true } },
    seo: { title: 'Qualifying Knockout Session | AF Motorsport', description: 'Knockout-style qualifying format for grid position determination' },
    generateSlug: false, slug: 'qualifying-session-knockout',
    visibility: { check_publish: true, check_featured: true, check_pinned: true }
  },
  {
    name: 'Race Session - Grand Prix Format',
    alias: 'RACE',
    code: 'R-GP',
    toggle: 'advanced',
    type: categoriesIds[146],
    basics: { enable: true, description: 'Standard Grand Prix race session with fixed distance or time limit.', status: 'Completed', access: 'Public', visibility: { show: true } },
    details: { enable: true, event: 1, format: { segment: 'Race', duration: 120, interval: 0, specification: 'Fixed lap count or 2-hour maximum duration' }, classifications: [], features: [], protocols: [], strategies: [], visibility: { show: true } },
    traits: { enable: true, constraints: [], parameters: [], specifications: [], visibility: { show: true } },
    metrics: { enable: true, quantifiers: { laps: 58, distance: '305 km', duration: '90-120 min' }, visibility: { show: true } },
    assets: { enable: true, gallery: null, playlist: null, visibility: { show: true } },
    contexts: { enable: true, highlights: [], incidents: [], authorities: [], participants: [], crews: [], entities: [], insights: [], visibility: { show: true } },
    seo: { title: 'Grand Prix Race Session | AF Motorsport', description: 'Standard Grand Prix race format with fixed distance or time limit' },
    generateSlug: false, slug: 'race-session-grand-prix',
    visibility: { check_publish: true, check_featured: true, check_pinned: true }
  },
  {
    name: 'Sprint Race Session - Short Format',
    alias: 'SPRINT',
    code: 'S-SHF',
    toggle: 'advanced',
    type: categoriesIds[123],
    basics: { enable: true, description: 'Short-format sprint race determining additional championship points and grid positions.', status: 'Completed', access: 'Public', visibility: { show: true } },
    details: { enable: true, event: 1, format: { segment: 'Sprint', duration: 30, interval: 0, specification: '100 km distance or 30-minute maximum' }, classifications: [], features: [], protocols: [], strategies: [], visibility: { show: true } },
    traits: { enable: true, constraints: [], parameters: [], specifications: [], visibility: { show: true } },
    metrics: { enable: true, quantifiers: { laps: 17, distance: '100 km', duration: '25-30 min' }, visibility: { show: true } },
    assets: { enable: true, gallery: null, playlist: null, visibility: { show: true } },
    contexts: { enable: true, highlights: [], incidents: [], authorities: [], participants: [], crews: [], entities: [], insights: [], visibility: { show: true } },
    seo: { title: 'Sprint Race Session | AF Motorsport', description: 'Short-format sprint race for additional championship points' },
    generateSlug: false, slug: 'sprint-race-session-short',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Warmup Session - Pre-Race Format',
    alias: 'WU',
    code: 'WU-PRF',
    toggle: 'advanced',
    type: categoriesIds[38],
    basics: { enable: true, description: 'Pre-race warmup session for final system checks and driver preparation.', status: 'Completed', access: 'Public', visibility: { show: true } },
    details: { enable: true, event: 1, format: { segment: 'Warmup', duration: 20, interval: 0, specification: 'Final systems check and tire preparation' }, classifications: [], features: [], protocols: [], strategies: [], visibility: { show: true } },
    traits: { enable: true, constraints: [], parameters: [], specifications: [], visibility: { show: true } },
    metrics: { enable: true, quantifiers: { laps: 8, distance: '40 km', duration: '20 min' }, visibility: { show: true } },
    assets: { enable: true, gallery: null, playlist: null, visibility: { show: true } },
    contexts: { enable: true, highlights: [], incidents: [], authorities: [], participants: [], crews: [], entities: [], insights: [], visibility: { show: true } },
    seo: { title: 'Warmup Session | AF Motorsport', description: 'Pre-race warmup session for final preparation' },
    generateSlug: false, slug: 'warmup-session-pre-race',
    visibility: { check_publish: true, check_featured: false, check_pinned: false }
  },
  {
    name: 'Test Session - Development Format',
    alias: 'TEST',
    code: 'T-DEV',
    toggle: 'advanced',
    type: categoriesIds[122],
    basics: { enable: true, description: 'Non-competitive testing session for vehicle development and driver evaluation.', status: 'Completed', access: 'Private', visibility: { show: true } },
    details: { enable: true, event: 1, format: { segment: 'Test', duration: 480, interval: 0, specification: 'Full-day testing with unlimited running' }, classifications: [], features: [], protocols: [], strategies: [], visibility: { show: true } },
    traits: { enable: true, constraints: [], parameters: [], specifications: [], visibility: { show: true } },
    metrics: { enable: true, quantifiers: { laps: 120, distance: '600 km', duration: '8 hours' }, visibility: { show: true } },
    assets: { enable: true, gallery: null, playlist: null, visibility: { show: true } },
    contexts: { enable: true, highlights: [], incidents: [], authorities: [], participants: [], crews: [], entities: [], insights: [], visibility: { show: true } },
    seo: { title: 'Test Session | AF Motorsport', description: 'Non-competitive testing session for development purposes' },
    generateSlug: false, slug: 'test-session-development',
    visibility: { check_publish: true, check_featured: false, check_pinned: false }
  },
  {
    name: 'Qualifying Session - Single-Lap Format',
    alias: 'Q1L',
    code: 'Q-1L',
    toggle: 'advanced',
    type: categoriesIds[17],
    basics: { enable: true, description: 'Single-lap qualifying format where each driver sets one timed lap.', status: 'Completed', access: 'Public', visibility: { show: true } },
    details: { enable: true, event: 1, format: { segment: 'Qualifying', duration: 30, interval: 0, specification: 'One flying lap per driver, reverse order' }, classifications: [], features: [], protocols: [], strategies: [], visibility: { show: true } },
    traits: { enable: true, constraints: [], parameters: [], specifications: [], visibility: { show: true } },
    metrics: { enable: true, quantifiers: { laps: 1, distance: '5.2 km', duration: '30 min' }, visibility: { show: true } },
    assets: { enable: true, gallery: null, playlist: null, visibility: { show: true } },
    contexts: { enable: true, highlights: [], incidents: [], authorities: [], participants: [], crews: [], entities: [], insights: [], visibility: { show: true } },
    seo: { title: 'Single-Lap Qualifying | AF Motorsport', description: 'Single-lap qualifying format for grid position determination' },
    generateSlug: false, slug: 'qualifying-session-single-lap',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Practice Session - Tire Evaluation Format',
    alias: 'FP-TIRE',
    code: 'FP-TE',
    toggle: 'advanced',
    type: categoriesIds[245],
    basics: { enable: true, description: 'Practice session focused on tire compound evaluation and degradation analysis.', status: 'Completed', access: 'Public', visibility: { show: true } },
    details: { enable: true, event: 1, format: { segment: 'Practice', duration: 90, interval: 0, specification: 'Extended running for tire compound comparison' }, classifications: [], features: [], protocols: [], strategies: [], visibility: { show: true } },
    traits: { enable: true, constraints: [], parameters: [], specifications: [], visibility: { show: true } },
    metrics: { enable: true, quantifiers: { laps: 45, distance: '225 km', duration: '90 min' }, visibility: { show: true } },
    assets: { enable: true, gallery: null, playlist: null, visibility: { show: true } },
    contexts: { enable: true, highlights: [], incidents: [], authorities: [], participants: [], crews: [], entities: [], insights: [], visibility: { show: true } },
    seo: { title: 'Tire Evaluation Practice | AF Motorsport', description: 'Practice session focused on tire compound evaluation' },
    generateSlug: false, slug: 'practice-session-tire-evaluation',
    visibility: { check_publish: true, check_featured: false, check_pinned: false }
  },
  {
    name: 'Race Session - Endurance Format',
    alias: 'ENDU',
    code: 'R-END',
    toggle: 'advanced',
    type: categoriesIds[243],
    basics: { enable: true, description: 'Extended-duration endurance race session with multiple driver stints.', status: 'Completed', access: 'Public', visibility: { show: true } },
    details: { enable: true, event: 1, format: { segment: 'Race', duration: 1440, interval: 0, specification: '24-hour endurance format with driver rotations' }, classifications: [], features: [], protocols: [], strategies: [], visibility: { show: true } },
    traits: { enable: true, constraints: [], parameters: [], specifications: [], visibility: { show: true } },
    metrics: { enable: true, quantifiers: { laps: 382, distance: '5280 km', duration: '24 hours' }, visibility: { show: true } },
    assets: { enable: true, gallery: null, playlist: null, visibility: { show: true } },
    contexts: { enable: true, highlights: [], incidents: [], authorities: [], participants: [], crews: [], entities: [], insights: [], visibility: { show: true } },
    seo: { title: 'Endurance Race Session | AF Motorsport', description: 'Extended-duration endurance race with multiple driver stints' },
    generateSlug: false, slug: 'race-session-endurance',
    visibility: { check_publish: true, check_featured: true, check_pinned: true }
  },
  {
    name: 'Qualifying Session - Shootout Format',
    alias: 'SHOOT',
    code: 'Q-SHO',
    toggle: 'advanced',
    type: categoriesIds[52],
    basics: { enable: true, description: 'Head-to-head shootout qualifying format for pole position decider.', status: 'Completed', access: 'Public', visibility: { show: true } },
    details: { enable: true, event: 1, format: { segment: 'Qualifying', duration: 15, interval: 0, specification: 'Top 2 drivers, single lap shootout for pole' }, classifications: [], features: [], protocols: [], strategies: [], visibility: { show: true } },
    traits: { enable: true, constraints: [], parameters: [], specifications: [], visibility: { show: true } },
    metrics: { enable: true, quantifiers: { laps: 2, distance: '10.4 km', duration: '15 min' }, visibility: { show: true } },
    assets: { enable: true, gallery: null, playlist: null, visibility: { show: true } },
    contexts: { enable: true, highlights: [], incidents: [], authorities: [], participants: [], crews: [], entities: [], insights: [], visibility: { show: true } },
    seo: { title: 'Shootout Qualifying | AF Motorsport', description: 'Head-to-head shootout format for pole position decider' },
    generateSlug: false, slug: 'qualifying-session-shootout',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Practice Session - Wet Weather Format',
    alias: 'FP-WET',
    code: 'FP-WW',
    toggle: 'advanced',
    type: categoriesIds[215],
    basics: { enable: true, description: 'Practice session conducted in wet weather conditions for tire and setup evaluation.', status: 'Completed', access: 'Public', visibility: { show: true } },
    details: { enable: true, event: 1, format: { segment: 'Practice', duration: 45, interval: 0, specification: 'Wet weather running with intermediate and wet tire compounds' }, classifications: [], features: [], protocols: [], strategies: [], visibility: { show: true } },
    traits: { enable: true, constraints: [], parameters: [], specifications: [], visibility: { show: true } },
    metrics: { enable: true, quantifiers: { laps: 20, distance: '100 km', duration: '45 min' }, visibility: { show: true } },
    assets: { enable: true, gallery: null, playlist: null, visibility: { show: true } },
    contexts: { enable: true, highlights: [], incidents: [], authorities: [], participants: [], crews: [], entities: [], insights: [], visibility: { show: true } },
    seo: { title: 'Wet Weather Practice | AF Motorsport', description: 'Practice session in wet conditions for tire and setup evaluation' },
    generateSlug: false, slug: 'practice-session-wet-weather',
    visibility: { check_publish: true, check_featured: false, check_pinned: false }
  },
  {
    name: 'Race Session - Sprint Cup Format',
    alias: 'CUP',
    code: 'R-CUP',
    toggle: 'advanced',
    type: categoriesIds[232],
    basics: { enable: true, description: 'Cup-style race session with multiple short races determining overall winner.', status: 'Completed', access: 'Public', visibility: { show: true } },
    details: { enable: true, event: 1, format: { segment: 'Race', duration: 60, interval: 15, specification: 'Three 15-minute races with cumulative points' }, classifications: [], features: [], protocols: [], strategies: [], visibility: { show: true } },
    traits: { enable: true, constraints: [], parameters: [], specifications: [], visibility: { show: true } },
    metrics: { enable: true, quantifiers: { laps: 30, distance: '150 km', duration: '60 min' }, visibility: { show: true } },
    assets: { enable: true, gallery: null, playlist: null, visibility: { show: true } },
    contexts: { enable: true, highlights: [], incidents: [], authorities: [], participants: [], crews: [], entities: [], insights: [], visibility: { show: true } },
    seo: { title: 'Sprint Cup Race | AF Motorsport', description: 'Cup-style race with multiple short races for overall winner' },
    generateSlug: false, slug: 'race-session-sprint-cup',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Qualifying Session - Aggregate Format',
    alias: 'Q-AGG',
    code: 'Q-AGG',
    toggle: 'advanced',
    type: categoriesIds[107],
    basics: { enable: true, description: 'Aggregate qualifying format combining multiple session times for grid order.', status: 'Completed', access: 'Public', visibility: { show: true } },
    details: { enable: true, event: 1, format: { segment: 'Qualifying', duration: 60, interval: 20, specification: 'Three 20-minute sessions, best aggregate time determines grid' }, classifications: [], features: [], protocols: [], strategies: [], visibility: { show: true } },
    traits: { enable: true, constraints: [], parameters: [], specifications: [], visibility: { show: true } },
    metrics: { enable: true, quantifiers: { laps: 18, distance: '90 km', duration: '60 min' }, visibility: { show: true } },
    assets: { enable: true, gallery: null, playlist: null, visibility: { show: true } },
    contexts: { enable: true, highlights: [], incidents: [], authorities: [], participants: [], crews: [], entities: [], insights: [], visibility: { show: true } },
    seo: { title: 'Aggregate Qualifying | AF Motorsport', description: 'Aggregate qualifying format combining multiple session times' },
    generateSlug: false, slug: 'qualifying-session-aggregate',
    visibility: { check_publish: true, check_featured: false, check_pinned: false }
  },
  {
    name: 'Practice Session - Setup Lock Format',
    alias: 'FP-LOCK',
    code: 'FP-SL',
    toggle: 'advanced',
    type: categoriesIds[126],
    basics: { enable: true, description: 'Practice session with setup lock period for race preparation.', status: 'Completed', access: 'Public', visibility: { show: true } },
    details: { enable: true, event: 1, format: { segment: 'Practice', duration: 40, interval: 0, specification: 'Setup freeze period after initial running' }, classifications: [], features: [], protocols: [], strategies: [], visibility: { show: true } },
    traits: { enable: true, constraints: [], parameters: [], specifications: [], visibility: { show: true } },
    metrics: { enable: true, quantifiers: { laps: 25, distance: '125 km', duration: '40 min' }, visibility: { show: true } },
    assets: { enable: true, gallery: null, playlist: null, visibility: { show: true } },
    contexts: { enable: true, highlights: [], incidents: [], authorities: [], participants: [], crews: [], entities: [], insights: [], visibility: { show: true } },
    seo: { title: 'Setup Lock Practice | AF Motorsport', description: 'Practice session with setup lock period for race preparation' },
    generateSlug: false, slug: 'practice-session-setup-lock',
    visibility: { check_publish: true, check_featured: false, check_pinned: false }
  },
  {
    name: 'Race Session - Heat Race Format',
    alias: 'HEAT',
    code: 'R-HET',
    toggle: 'advanced',
    type: categoriesIds[41],
    basics: { enable: true, description: 'Heat race format determining qualification for main event.', status: 'Completed', access: 'Public', visibility: { show: true } },
    details: { enable: true, event: 1, format: { segment: 'Race', duration: 20, interval: 0, specification: 'Short heat race for main event qualification' }, classifications: [], features: [], protocols: [], strategies: [], visibility: { show: true } },
    traits: { enable: true, constraints: [], parameters: [], specifications: [], visibility: { show: true } },
    metrics: { enable: true, quantifiers: { laps: 10, distance: '50 km', duration: '20 min' }, visibility: { show: true } },
    assets: { enable: true, gallery: null, playlist: null, visibility: { show: true } },
    contexts: { enable: true, highlights: [], incidents: [], authorities: [], participants: [], crews: [], entities: [], insights: [], visibility: { show: true } },
    seo: { title: 'Heat Race Session | AF Motorsport', description: 'Heat race format for main event qualification' },
    generateSlug: false, slug: 'race-session-heat-race',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Qualifying Session - Reverse Grid Format',
    alias: 'Q-REV',
    code: 'Q-RG',
    toggle: 'advanced',
    type: categoriesIds[9],
    basics: { enable: true, description: 'Reverse grid qualifying format for enhanced racing competition.', status: 'Completed', access: 'Public', visibility: { show: true } },
    details: { enable: true, event: 1, format: { segment: 'Qualifying', duration: 30, interval: 0, specification: 'Fastest qualifier starts last, slowest starts first' }, classifications: [], features: [], protocols: [], strategies: [], visibility: { show: true } },
    traits: { enable: true, constraints: [], parameters: [], specifications: [], visibility: { show: true } },
    metrics: { enable: true, quantifiers: { laps: 10, distance: '50 km', duration: '30 min' }, visibility: { show: true } },
    assets: { enable: true, gallery: null, playlist: null, visibility: { show: true } },
    contexts: { enable: true, highlights: [], incidents: [], authorities: [], participants: [], crews: [], entities: [], insights: [], visibility: { show: true } },
    seo: { title: 'Reverse Grid Qualifying | AF Motorsport', description: 'Reverse grid qualifying format for enhanced racing competition' },
    generateSlug: false, slug: 'qualifying-session-reverse-grid',
    visibility: { check_publish: true, check_featured: false, check_pinned: false }
  },
  {
    name: 'Practice Session - Night Running Format',
    alias: 'FP-NIGHT',
    code: 'FP-NR',
    toggle: 'advanced',
    type: categoriesIds[105],
    basics: { enable: true, description: 'Practice session conducted under night conditions with artificial lighting.', status: 'Completed', access: 'Public', visibility: { show: true } },
    details: { enable: true, event: 1, format: { segment: 'Practice', duration: 50, interval: 0, specification: 'Night running with circuit lighting systems active' }, classifications: [], features: [], protocols: [], strategies: [], visibility: { show: true } },
    traits: { enable: true, constraints: [], parameters: [], specifications: [], visibility: { show: true } },
    metrics: { enable: true, quantifiers: { laps: 28, distance: '140 km', duration: '50 min' }, visibility: { show: true } },
    assets: { enable: true, gallery: null, playlist: null, visibility: { show: true } },
    contexts: { enable: true, highlights: [], incidents: [], authorities: [], participants: [], crews: [], entities: [], insights: [], visibility: { show: true } },
    seo: { title: 'Night Practice Session | AF Motorsport', description: 'Practice session under night conditions with artificial lighting' },
    generateSlug: false, slug: 'practice-session-night-running',
    visibility: { check_publish: true, check_featured: false, check_pinned: false }
  },
  {
    name: 'Race Session - Twilight Format',
    alias: 'TWILIGHT',
    code: 'R-TWL',
    toggle: 'advanced',
    type: categoriesIds[118],
    basics: { enable: true, description: 'Twilight race session starting at dusk and finishing under lights.', status: 'Completed', access: 'Public', visibility: { show: true } },
    details: { enable: true, event: 1, format: { segment: 'Race', duration: 90, interval: 0, specification: 'Race starts at sunset, finishes under artificial lighting' }, classifications: [], features: [], protocols: [], strategies: [], visibility: { show: true } },
    traits: { enable: true, constraints: [], parameters: [], specifications: [], visibility: { show: true } },
    metrics: { enable: true, quantifiers: { laps: 55, distance: '308 km', duration: '90 min' }, visibility: { show: true } },
    assets: { enable: true, gallery: null, playlist: null, visibility: { show: true } },
    contexts: { enable: true, highlights: [], incidents: [], authorities: [], participants: [], crews: [], entities: [], insights: [], visibility: { show: true } },
    seo: { title: 'Twilight Race Session | AF Motorsport', description: 'Twilight race starting at dusk and finishing under lights' },
    generateSlug: false, slug: 'race-session-twilight',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Qualifying Session - Superpole Format',
    alias: 'Q-SUPER',
    code: 'Q-SP',
    toggle: 'advanced',
    type: categoriesIds[27],
    basics: { enable: true, description: 'Superpole format where top qualifiers compete for pole in final shootout.', status: 'Completed', access: 'Public', visibility: { show: true } },
    details: { enable: true, event: 1, format: { segment: 'Qualifying', duration: 25, interval: 0, specification: 'Top 6 drivers, single lap shootout for pole position' }, classifications: [], features: [], protocols: [], strategies: [], visibility: { show: true } },
    traits: { enable: true, constraints: [], parameters: [], specifications: [], visibility: { show: true } },
    metrics: { enable: true, quantifiers: { laps: 6, distance: '30 km', duration: '25 min' }, visibility: { show: true } },
    assets: { enable: true, gallery: null, playlist: null, visibility: { show: true } },
    contexts: { enable: true, highlights: [], incidents: [], authorities: [], participants: [], crews: [], entities: [], insights: [], visibility: { show: true } },
    seo: { title: 'Superpole Qualifying | AF Motorsport', description: 'Superpole format with top qualifiers competing for pole' },
    generateSlug: false, slug: 'qualifying-session-superpole',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Practice Session - Aerodynamic Evaluation Format',
    alias: 'FP-AERO',
    code: 'FP-AE',
    toggle: 'advanced',
    type: categoriesIds[166],
    basics: { enable: true, description: 'Practice session dedicated to aerodynamic package evaluation and correlation.', status: 'Completed', access: 'Private', visibility: { show: true } },
    details: { enable: true, event: 1, format: { segment: 'Practice', duration: 75, interval: 0, specification: 'Focused aero testing with specific run plans' }, classifications: [], features: [], protocols: [], strategies: [], visibility: { show: true } },
    traits: { enable: true, constraints: [], parameters: [], specifications: [], visibility: { show: true } },
    metrics: { enable: true, quantifiers: { laps: 35, distance: '175 km', duration: '75 min' }, visibility: { show: true } },
    assets: { enable: true, gallery: null, playlist: null, visibility: { show: true } },
    contexts: { enable: true, highlights: [], incidents: [], authorities: [], participants: [], crews: [], entities: [], insights: [], visibility: { show: true } },
    seo: { title: 'Aero Evaluation Practice | AF Motorsport', description: 'Practice session for aerodynamic package evaluation' },
    generateSlug: false, slug: 'practice-session-aerodynamic-evaluation',
    visibility: { check_publish: true, check_featured: false, check_pinned: false }
  }
] as const;
