export const PRELOAD_VISUALIZATION = (categoriesIds: number[], mediaIds: number[]) => [
  {
    name: 'F1 Lap Time Delta Analysis Chart - Monaco GP 2024',
    toggle: 'advanced',
    type: categoriesIds[185],
    details: {
      enable: true,
      designs: [mediaIds[0], mediaIds[1], mediaIds[2]],
      narrative: null,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'f1-lap-time-delta-analysis-chart-monaco-gp-2024',
    visibility: { check_publish: true, check_featured: true, check_pinned: false },
  },
  {
    name: 'WEC Endurance Stint Performance Graph - Le Mans 24h',
    toggle: 'advanced',
    type: categoriesIds[53],
    details: {
      enable: true,
      designs: [mediaIds[0], mediaIds[1], mediaIds[4]],
      narrative: null,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'wec-endurance-stint-performance-graph-le-mans-24h',
    visibility: { check_publish: true, check_featured: true, check_pinned: false },
  },
  {
    name: 'Circuit Layout Map with Sector Timing Zones - Silverstone',
    toggle: 'advanced',
    type: categoriesIds[146],
    details: {
      enable: true,
      designs: [mediaIds[1], mediaIds[2], mediaIds[3]],
      narrative: null,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'circuit-layout-map-sector-timing-zones-silverstone',
    visibility: { check_publish: true, check_featured: true, check_pinned: false },
  },
  {
    name: 'Championship Points Progression Timeline - 2024 Season',
    toggle: 'advanced',
    type: categoriesIds[123],
    details: {
      enable: true,
      designs: [mediaIds[2], mediaIds[3], mediaIds[4]],
      narrative: null,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'championship-points-progression-timeline-2024-season',
    visibility: { check_publish: true, check_featured: true, check_pinned: true },
  },
  {
    name: 'Hybrid Powertrain Energy Flow 3D Model Diagram',
    toggle: 'advanced',
    type: categoriesIds[38],
    details: {
      enable: true,
      designs: [mediaIds[0], mediaIds[2], mediaIds[4]],
      narrative: null,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'hybrid-powertrain-energy-flow-3d-model-diagram',
    visibility: { check_publish: true, check_featured: true, check_pinned: false },
  },
  {
    name: 'Tire Degradation Comparison Infographic - Compound Analysis',
    toggle: 'advanced',
    type: categoriesIds[122],
    details: {
      enable: true,
      designs: [mediaIds[1], mediaIds[3], mediaIds[4]],
      narrative: null,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'tire-degradation-comparison-infographic-compound-analysis',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    name: 'Aerodynamic Downforce Distribution Chart - Spa-Francorchamps',
    toggle: 'advanced',
    type: categoriesIds[17],
    details: {
      enable: true,
      designs: [mediaIds[0], mediaIds[1], mediaIds[2]],
      narrative: null,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'aerodynamic-downforce-distribution-chart-spa-francorchamps',
    visibility: { check_publish: true, check_featured: true, check_pinned: false },
  },
  {
    name: 'Driver Performance Metrics Radar Graph - Qualifying Session',
    toggle: 'advanced',
    type: categoriesIds[245],
    details: {
      enable: true,
      designs: [mediaIds[2], mediaIds[3], mediaIds[4]],
      narrative: null,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'driver-performance-metrics-radar-graph-qualifying-session',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    name: 'WRC Rally Stage Elevation Profile Map - Monte-Carlo',
    toggle: 'advanced',
    type: categoriesIds[243],
    details: {
      enable: true,
      designs: [mediaIds[0], mediaIds[1], mediaIds[3]],
      narrative: null,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'wrc-rally-stage-elevation-profile-map-monte-carlo',
    visibility: { check_publish: true, check_featured: true, check_pinned: false },
  },
  {
    name: 'Pit Stop Efficiency Timeline Comparison - Team Analysis',
    toggle: 'advanced',
    type: categoriesIds[52],
    details: {
      enable: true,
      designs: [mediaIds[1], mediaIds[2], mediaIds[4]],
      narrative: null,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'pit-stop-efficiency-timeline-comparison-team-analysis',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    name: 'Chassis Torsional Rigidity 3D Model Visualization',
    toggle: 'advanced',
    type: categoriesIds[215],
    details: {
      enable: true,
      designs: [mediaIds[0], mediaIds[2], mediaIds[3]],
      narrative: null,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'chassis-torsional-rigidity-3d-model-visualization',
    visibility: { check_publish: true, check_featured: true, check_pinned: false },
  },
  {
    name: 'Race Strategy Decision Tree Infographic - Monaco GP',
    toggle: 'advanced',
    type: categoriesIds[232],
    details: {
      enable: true,
      designs: [mediaIds[1], mediaIds[2], mediaIds[3]],
      narrative: null,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'race-strategy-decision-tree-infographic-monaco-gp',
    visibility: { check_publish: true, check_featured: true, check_pinned: false },
  },
  {
    name: 'Fuel Consumption Rate Chart - Endurance Race Analysis',
    toggle: 'advanced',
    type: categoriesIds[107],
    details: {
      enable: true,
      designs: [mediaIds[2], mediaIds[3], mediaIds[4]],
      narrative: null,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'fuel-consumption-rate-chart-endurance-race-analysis',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    name: 'Driver G-Force Exposure Graph - High-Speed Corner Analysis',
    toggle: 'advanced',
    type: categoriesIds[126],
    details: {
      enable: true,
      designs: [mediaIds[0], mediaIds[1], mediaIds[4]],
      narrative: null,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'driver-g-force-exposure-graph-high-speed-corner-analysis',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    name: 'Global Championship Calendar Map - 2024 Season Venues',
    toggle: 'advanced',
    type: categoriesIds[41],
    details: {
      enable: true,
      designs: [mediaIds[0], mediaIds[2], mediaIds[4]],
      narrative: null,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'global-championship-calendar-map-2024-season-venues',
    visibility: { check_publish: true, check_featured: true, check_pinned: false },
  },
  {
    name: 'Technical Regulation Evolution Timeline - Hybrid Era',
    toggle: 'advanced',
    type: categoriesIds[9],
    details: {
      enable: true,
      designs: [mediaIds[1], mediaIds[2], mediaIds[3]],
      narrative: null,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'technical-regulation-evolution-timeline-hybrid-era',
    visibility: { check_publish: true, check_featured: true, check_pinned: false },
  },
  {
    name: 'Suspension Geometry 3D Model - Setup Optimization Diagram',
    toggle: 'advanced',
    type: categoriesIds[105],
    details: {
      enable: true,
      designs: [mediaIds[0], mediaIds[3], mediaIds[4]],
      narrative: null,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'suspension-geometry-3d-model-setup-optimization-diagram',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    name: 'Championship Standings Comparison Infographic - Constructors vs Drivers',
    toggle: 'advanced',
    type: categoriesIds[118],
    details: {
      enable: true,
      designs: [mediaIds[1], mediaIds[2], mediaIds[4]],
      narrative: null,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'championship-standings-comparison-infographic-constructors-vs-drivers',
    visibility: { check_publish: true, check_featured: true, check_pinned: false },
  },
  {
    name: 'Weather Impact Performance Chart - Wet vs Dry Lap Times',
    toggle: 'advanced',
    type: categoriesIds[27],
    details: {
      enable: true,
      designs: [mediaIds[0], mediaIds[1], mediaIds[2]],
      narrative: null,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'weather-impact-performance-chart-wet-vs-dry-lap-times',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    name: 'Team Budget Allocation Graph - Cost Cap Compliance Visualization',
    toggle: 'advanced',
    type: categoriesIds[166],
    details: {
      enable: true,
      designs: [mediaIds[2], mediaIds[3], mediaIds[4]],
      narrative: null,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'team-budget-allocation-graph-cost-cap-compliance-visualization',
    visibility: { check_publish: true, check_featured: true, check_pinned: false },
  },
  {
    name: 'Circuit Safety Barrier Impact Zone Map - FIA Standards',
    toggle: 'advanced',
    type: categoriesIds[84],
    details: {
      enable: true,
      designs: [mediaIds[0], mediaIds[1], mediaIds[3]],
      narrative: null,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'circuit-safety-barrier-impact-zone-map-fia-standards',
    visibility: { check_publish: true, check_featured: true, check_pinned: true },
  },
  {
    name: 'Driver Career Progression Timeline - Championship Journey',
    toggle: 'advanced',
    type: categoriesIds[48],
    details: {
      enable: true,
      designs: [mediaIds[1], mediaIds[2], mediaIds[4]],
      narrative: null,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'driver-career-progression-timeline-championship-journey',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    name: 'Power Unit Component Assembly 3D Model - Technical Exploded View',
    toggle: 'advanced',
    type: categoriesIds[109],
    details: {
      enable: true,
      designs: [mediaIds[0], mediaIds[2], mediaIds[3]],
      narrative: null,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'power-unit-component-assembly-3d-model-technical-exploded-view',
    visibility: { check_publish: true, check_featured: true, check_pinned: false },
  },
  {
    name: 'Sponsor Activation ROI Infographic - Brand Value Analysis',
    toggle: 'advanced',
    type: categoriesIds[110],
    details: {
      enable: true,
      designs: [mediaIds[1], mediaIds[3], mediaIds[4]],
      narrative: null,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'sponsor-activation-roi-infographic-brand-value-analysis',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
] as const
