// FILE: src/collections/Content/Story/seeders/preload.ts
export const PRELOAD_STORY = (categoriesIds: number[], narrativesIds: number[]) => [
  {
    name: 'From Karting to Championship',
    alias: 'Rookie Rise',
    toggle: 'advanced',
    type: categoriesIds[185],
    details: { enable: true, narrative: narrativesIds[1], visibility: { show: true } },
    traits: { enable: true, concerns: [{ conflict: 'Limited resources vs elite competition', stakes: 'Career-defining opportunity', resolution: 'Strategic partnerships and relentless development' }], interactions: [{ dynamics: 'Mentorship', outcome: 'Accelerated skill acquisition and competitive breakthrough' }], visibility: { show: true } },
    assets: { enable: true, gallery: null, playlist: null, visibility: { show: true } },
    contexts: { enable: true, highlights: [], incidents: [], visibility: { show: true } },
    seo: { title: 'From Karting to Championship Story | AF Motorsport', description: 'Origin story of emerging talent rising through racing ranks' },
    generateSlug: false, slug: 'from-karting-to-championship',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'The Comeback Drive',
    alias: 'Resilience Redeemed',
    toggle: 'advanced',
    type: categoriesIds[53],
    details: { enable: true, narrative: narrativesIds[2], visibility: { show: true } },
    traits: { enable: true, concerns: [{ conflict: 'Career-threatening injury vs competitive ambition', stakes: 'Return to elite competition', resolution: 'Rehabilitation, mental conditioning, and strategic patience' }], interactions: [{ dynamics: 'Cooperative', outcome: 'Full recovery and podium achievement' }], visibility: { show: true } },
    assets: { enable: true, gallery: null, playlist: null, visibility: { show: true } },
    contexts: { enable: true, highlights: [], incidents: [], visibility: { show: true } },
    seo: { title: 'The Comeback Drive Story | AF Motorsport', description: 'Story of resilience and recovery returning to competitive racing' },
    generateSlug: false, slug: 'the-comeback-drive',
    visibility: { check_publish: true, check_featured: true, check_pinned: true }
  },
  {
    name: 'Victory at Monaco',
    alias: 'Street Circuit Triumph',
    toggle: 'advanced',
    type: categoriesIds[146],
    details: { enable: true, narrative: narrativesIds[3], visibility: { show: true } },
    traits: { enable: true, concerns: [{ conflict: 'Precision vs pressure on narrow streets', stakes: 'Prestigious championship victory', resolution: 'Flawless execution under extreme conditions' }], interactions: [{ dynamics: 'Competitive', outcome: 'Historic win at motorsport\'s most demanding circuit' }], visibility: { show: true } },
    assets: { enable: true, gallery: null, playlist: null, visibility: { show: true } },
    contexts: { enable: true, highlights: [], incidents: [], visibility: { show: true } },
    seo: { title: 'Victory at Monaco Story | AF Motorsport', description: 'Story of triumph at the prestigious Monaco Grand Prix' },
    generateSlug: false, slug: 'victory-at-monaco',
    visibility: { check_publish: true, check_featured: true, check_pinned: true }
  },
  {
    name: 'Behind the Pit Wall',
    alias: 'Strategy Unveiled',
    toggle: 'advanced',
    type: categoriesIds[123],
    details: { enable: true, narrative: narrativesIds[4], visibility: { show: true } },
    traits: { enable: true, concerns: [{ conflict: 'Data overload vs decisive action', stakes: 'Championship points at risk', resolution: 'Clear communication and trusted protocols' }], interactions: [{ dynamics: 'Cooperative', outcome: 'Race-winning strategic execution' }], visibility: { show: true } },
    assets: { enable: true, gallery: null, playlist: null, visibility: { show: true } },
    contexts: { enable: true, highlights: [], incidents: [], visibility: { show: true } },
    seo: { title: 'Behind the Pit Wall Story | AF Motorsport', description: 'Behind-the-scenes story of strategic decision-making in racing' },
    generateSlug: false, slug: 'behind-the-pit-wall',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Legacy of a Legend',
    alias: 'Champion\'s Journey',
    toggle: 'advanced',
    type: categoriesIds[38],
    details: { enable: true, narrative: narrativesIds[5], visibility: { show: true } },
    traits: { enable: true, concerns: [{ conflict: 'Sustaining excellence vs evolving competition', stakes: 'Enduring influence on the sport', resolution: 'Adaptation, innovation, and mentorship' }], interactions: [{ dynamics: 'Mentorship', outcome: 'Inspiration for next generation of competitors' }], visibility: { show: true } },
    assets: { enable: true, gallery: null, playlist: null, visibility: { show: true } },
    contexts: { enable: true, highlights: [], incidents: [], visibility: { show: true } },
    seo: { title: 'Legacy of a Legend Story | AF Motorsport', description: 'Story of a championship driver\'s enduring influence on motorsport' },
    generateSlug: false, slug: 'legacy-of-a-legend',
    visibility: { check_publish: true, check_featured: true, check_pinned: true }
  },
  {
    name: 'The First Win',
    alias: 'Breakthrough Moment',
    toggle: 'advanced',
    type: categoriesIds[122],
    details: { enable: true, narrative: narrativesIds[6], visibility: { show: true } },
    traits: { enable: true, concerns: [{ conflict: 'Self-doubt vs competitive opportunity', stakes: 'Career validation and team confidence', resolution: 'Focused preparation and courageous execution' }], interactions: [{ dynamics: 'Cooperative', outcome: 'First victory and foundation for future success' }], visibility: { show: true } },
    assets: { enable: true, gallery: null, playlist: null, visibility: { show: true } },
    contexts: { enable: true, highlights: [], incidents: [], visibility: { show: true } },
    seo: { title: 'The First Win Story | AF Motorsport', description: 'Story of a driver\'s breakthrough first victory in championship competition' },
    generateSlug: false, slug: 'the-first-win',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Team Transformation',
    alias: 'From Midfield to Podium',
    toggle: 'advanced',
    type: categoriesIds[17],
    details: { enable: true, narrative: narrativesIds[7], visibility: { show: true } },
    traits: { enable: true, concerns: [{ conflict: 'Resource constraints vs competitive ambition', stakes: 'Organizational survival and growth', resolution: 'Strategic investment and cultural alignment' }], interactions: [{ dynamics: 'Cooperative', outcome: 'Sustained competitive improvement and championship contention' }], visibility: { show: true } },
    assets: { enable: true, gallery: null, playlist: null, visibility: { show: true } },
    contexts: { enable: true, highlights: [], incidents: [], visibility: { show: true } },
    seo: { title: 'Team Transformation Story | AF Motorsport', description: 'Story of organizational evolution from midfield to championship contention' },
    generateSlug: false, slug: 'team-transformation',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'The Technical Breakthrough',
    alias: 'Innovation Advantage',
    toggle: 'advanced',
    type: categoriesIds[245],
    details: { enable: true, narrative: narrativesIds[8], visibility: { show: true } },
    traits: { enable: true, concerns: [{ conflict: 'Regulatory boundaries vs performance potential', stakes: 'Competitive advantage and regulatory compliance', resolution: 'Creative engineering within technical frameworks' }], interactions: [{ dynamics: 'Cooperative', outcome: 'Performance gain and industry-wide technical influence' }], visibility: { show: true } },
    assets: { enable: true, gallery: null, playlist: null, visibility: { show: true } },
    contexts: { enable: true, highlights: [], incidents: [], visibility: { show: true } },
    seo: { title: 'Technical Breakthrough Story | AF Motorsport', description: 'Story of engineering innovation creating competitive advantage' },
    generateSlug: false, slug: 'the-technical-breakthrough',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Wet Weather Mastery',
    alias: 'Rain God Performance',
    toggle: 'advanced',
    type: categoriesIds[243],
    details: { enable: true, narrative: narrativesIds[9], visibility: { show: true } },
    traits: { enable: true, concerns: [{ conflict: 'Variable grip vs competitive consistency', stakes: 'Championship points in challenging conditions', resolution: 'Adaptive driving technique and strategic tire management' }], interactions: [{ dynamics: 'Competitive', outcome: 'Victory in conditions that separated skill from speed' }], visibility: { show: true } },
    assets: { enable: true, gallery: null, playlist: null, visibility: { show: true } },
    contexts: { enable: true, highlights: [], incidents: [], visibility: { show: true } },
    seo: { title: 'Wet Weather Mastery Story | AF Motorsport', description: 'Story of exceptional driving skill in challenging wet conditions' },
    generateSlug: false, slug: 'wet-weather-mastery',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'The Safety Innovation',
    alias: 'Protection Progress',
    toggle: 'advanced',
    type: categoriesIds[52],
    details: { enable: true, narrative: narrativesIds[10], visibility: { show: true } },
    traits: { enable: true, concerns: [{ conflict: 'Performance weight vs driver protection', stakes: 'Life-saving capability in high-speed incidents', resolution: 'Advanced materials and integrated safety systems' }], interactions: [{ dynamics: 'Cooperative', outcome: 'Industry-wide safety standard adoption' }], visibility: { show: true } },
    assets: { enable: true, gallery: null, playlist: null, visibility: { show: true } },
    contexts: { enable: true, highlights: [], incidents: [], visibility: { show: true } },
    seo: { title: 'Safety Innovation Story | AF Motorsport', description: 'Story of life-saving safety technology development in motorsport' },
    generateSlug: false, slug: 'the-safety-innovation',
    visibility: { check_publish: true, check_featured: true, check_pinned: true }
  },
  {
    name: 'The Rivalry',
    alias: 'Wheel-to-Wheel Legacy',
    toggle: 'advanced',
    type: categoriesIds[215],
    details: { enable: true, narrative: narrativesIds[11], visibility: { show: true } },
    traits: { enable: true, concerns: [{ conflict: 'Mutual ambition vs sporting respect', stakes: 'Championship titles and historical recognition', resolution: 'Competitive excellence elevating both competitors' }], interactions: [{ dynamics: 'Competitive', outcome: 'Defining era of motorsport competition' }], visibility: { show: true } },
    assets: { enable: true, gallery: null, playlist: null, visibility: { show: true } },
    contexts: { enable: true, highlights: [], incidents: [], visibility: { show: true } },
    seo: { title: 'The Rivalry Story | AF Motorsport', description: 'Story of legendary competitive rivalry defining an era of racing' },
    generateSlug: false, slug: 'the-rivalry',
    visibility: { check_publish: true, check_featured: true, check_pinned: true }
  },
  {
    name: 'The Underdog Victory',
    alias: 'Against the Odds',
    toggle: 'advanced',
    type: categoriesIds[232],
    details: { enable: true, narrative: narrativesIds[12], visibility: { show: true } },
    traits: { enable: true, concerns: [{ conflict: 'Resource disparity vs competitive determination', stakes: 'Proving potential against established powers', resolution: 'Strategic excellence and flawless execution' }], interactions: [{ dynamics: 'Competitive', outcome: 'Historic victory inspiring future challengers' }], visibility: { show: true } },
    assets: { enable: true, gallery: null, playlist: null, visibility: { show: true } },
    contexts: { enable: true, highlights: [], incidents: [], visibility: { show: true } },
    seo: { title: 'Underdog Victory Story | AF Motorsport', description: 'Story of unexpected triumph against established competitive powers' },
    generateSlug: false, slug: 'the-underdog-victory',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'The Final Lap',
    alias: 'Championship Decider',
    toggle: 'advanced',
    type: categoriesIds[107],
    details: { enable: true, narrative: narrativesIds[13], visibility: { show: true } },
    traits: { enable: true, concerns: [{ conflict: 'Championship pressure vs performance execution', stakes: 'Season-long effort culminating in single moment', resolution: 'Mental fortitude and technical precision under extreme pressure' }], interactions: [{ dynamics: 'Competitive', outcome: 'Title victory and career-defining achievement' }], visibility: { show: true } },
    assets: { enable: true, gallery: null, playlist: null, visibility: { show: true } },
    contexts: { enable: true, highlights: [], incidents: [], visibility: { show: true } },
    seo: { title: 'Final Lap Story | AF Motorsport', description: 'Story of championship-deciding final lap performance' },
    generateSlug: false, slug: 'the-final-lap',
    visibility: { check_publish: true, check_featured: true, check_pinned: true }
  },
  {
    name: 'The Mentor\'s Impact',
    alias: 'Passing the Torch',
    toggle: 'advanced',
    type: categoriesIds[126],
    details: { enable: true, narrative: narrativesIds[14], visibility: { show: true } },
    traits: { enable: true, concerns: [{ conflict: 'Personal legacy vs emerging talent development', stakes: 'Continuity of excellence across generations', resolution: 'Knowledge transfer and empowerment of next generation' }], interactions: [{ dynamics: 'Mentorship', outcome: 'Emerging champion carrying forward competitive standards' }], visibility: { show: true } },
    assets: { enable: true, gallery: null, playlist: null, visibility: { show: true } },
    contexts: { enable: true, highlights: [], incidents: [], visibility: { show: true } },
    seo: { title: 'Mentor Impact Story | AF Motorsport', description: 'Story of legendary driver mentoring next generation of champions' },
    generateSlug: false, slug: 'the-mentors-impact',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'The Sustainability Shift',
    alias: 'Green Racing Evolution',
    toggle: 'advanced',
    type: categoriesIds[41],
    details: { enable: true, narrative: narrativesIds[15], visibility: { show: true } },
    traits: { enable: true, concerns: [{ conflict: 'Performance tradition vs environmental responsibility', stakes: 'Long-term viability of motorsport', resolution: 'Innovation in sustainable technology and operations' }], interactions: [{ dynamics: 'Cooperative', outcome: 'Industry leadership in sustainable racing practices' }], visibility: { show: true } },
    assets: { enable: true, gallery: null, playlist: null, visibility: { show: true } },
    contexts: { enable: true, highlights: [], incidents: [], visibility: { show: true } },
    seo: { title: 'Sustainability Shift Story | AF Motorsport', description: 'Story of motorsport evolution toward environmental responsibility' },
    generateSlug: false, slug: 'the-sustainability-shift',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'The Digital Revolution',
    alias: 'Data-Driven Excellence',
    toggle: 'advanced',
    type: categoriesIds[9],
    details: { enable: true, narrative: narrativesIds[16], visibility: { show: true } },
    traits: { enable: true, concerns: [{ conflict: 'Traditional intuition vs analytical precision', stakes: 'Competitive advantage through information', resolution: 'Integration of human expertise and data intelligence' }], interactions: [{ dynamics: 'Cooperative', outcome: 'Performance optimization through digital transformation' }], visibility: { show: true } },
    assets: { enable: true, gallery: null, playlist: null, visibility: { show: true } },
    contexts: { enable: true, highlights: [], incidents: [], visibility: { show: true } },
    seo: { title: 'Digital Revolution Story | AF Motorsport', description: 'Story of data analytics transforming competitive racing performance' },
    generateSlug: false, slug: 'the-digital-revolution',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'The Global Expansion',
    alias: 'Worldwide Reach',
    toggle: 'advanced',
    type: categoriesIds[105],
    details: { enable: true, narrative: narrativesIds[17], visibility: { show: true } },
    traits: { enable: true, concerns: [{ conflict: 'Regional tradition vs international growth', stakes: 'Cultural relevance and commercial viability', resolution: 'Adaptive engagement strategies respecting local heritage' }], interactions: [{ dynamics: 'Cooperative', outcome: 'Global fan community and diversified competitive landscape' }], visibility: { show: true } },
    assets: { enable: true, gallery: null, playlist: null, visibility: { show: true } },
    contexts: { enable: true, highlights: [], incidents: [], visibility: { show: true } },
    seo: { title: 'Global Expansion Story | AF Motorsport', description: 'Story of motorsport growth connecting fans and competitors worldwide' },
    generateSlug: false, slug: 'the-global-expansion',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'The Heritage Preservation',
    alias: 'Honoring the Past',
    toggle: 'advanced',
    type: categoriesIds[118],
    details: { enable: true, narrative: narrativesIds[18], visibility: { show: true } },
    traits: { enable: true, concerns: [{ conflict: 'Modern innovation vs historical authenticity', stakes: 'Cultural continuity and inspirational legacy', resolution: 'Thoughtful conservation and contextual celebration' }], interactions: [{ dynamics: 'Cooperative', outcome: 'Living heritage inspiring future achievement' }], visibility: { show: true } },
    assets: { enable: true, gallery: null, playlist: null, visibility: { show: true } },
    contexts: { enable: true, highlights: [], incidents: [], visibility: { show: true } },
    seo: { title: 'Heritage Preservation Story | AF Motorsport', description: 'Story of honoring motorsport history while advancing competitive future' },
    generateSlug: false, slug: 'the-heritage-preservation',
    visibility: { check_publish: true, check_featured: false, check_pinned: true }
  },
  {
    name: 'The Youth Development',
    alias: 'Next Generation Pathway',
    toggle: 'advanced',
    type: categoriesIds[27],
    details: { enable: true, narrative: narrativesIds[19], visibility: { show: true } },
    traits: { enable: true, concerns: [{ conflict: 'Immediate results vs long-term talent cultivation', stakes: 'Sustainable competitive excellence', resolution: 'Structured development programs and patient investment' }], interactions: [{ dynamics: 'Mentorship', outcome: 'Emerging champions ready for elite competition' }], visibility: { show: true } },
    assets: { enable: true, gallery: null, playlist: null, visibility: { show: true } },
    contexts: { enable: true, highlights: [], incidents: [], visibility: { show: true } },
    seo: { title: 'Youth Development Story | AF Motorsport', description: 'Story of structured talent development creating future racing champions' },
    generateSlug: false, slug: 'the-youth-development',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'The Fan Connection',
    alias: 'Community Bond',
    toggle: 'advanced',
    type: categoriesIds[166],
    details: { enable: true, narrative: narrativesIds[20], visibility: { show: true } },
    traits: { enable: true, concerns: [{ conflict: 'Exclusive competition vs inclusive engagement', stakes: 'Long-term sport vitality and cultural relevance', resolution: 'Authentic connection and accessible storytelling' }], interactions: [{ dynamics: 'Cooperative', outcome: 'Loyal global community sustaining competitive passion' }], visibility: { show: true } },
    assets: { enable: true, gallery: null, playlist: null, visibility: { show: true } },
    contexts: { enable: true, highlights: [], incidents: [], visibility: { show: true } },
    seo: { title: 'Fan Connection Story | AF Motorsport', description: 'Story of meaningful engagement connecting fans to competitive motorsport' },
    generateSlug: false, slug: 'the-fan-connection',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  }
] as const;
