// FILE: src/collections/Entities/Driver/seeders/preload.ts
export const PRELOAD_DRIVER = [
  {
    first: 'Lewis',
    middle: 'Carl',
    last: 'Hamilton',
    alias: 'LH44',
    toggle: 'advanced',
    type: 1,
    basics: {
      enable: true,
      description: 'Seven-time Formula 1 World Champion',
      identifier: {
        number: '44',
        nickname: 'Sir Lewis',
        competition: 'F1',
        callsign: 'Hammer',
      },
      identity: {
        gender: 'Male',
        pronouns: 'he/him',
        age: '40',
        nationality: 'British',
      },
      chronology: {
        birth: '1985-01-07',
        debut: '2007-03-18',
        retirement: null,
      },
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'lewis-hamilton',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    first: 'Max',
    middle: '',
    last: 'Verstappen',
    alias: 'MV33',
    toggle: 'advanced',
    type: 2,
    basics: {
      enable: true,
      description: 'Reigning Formula 1 World Champion',
      identifier: {
        number: '33',
        nickname: 'Mad Max',
        competition: 'F1',
        callsign: 'SuperMax',
      },
      identity: {
        gender: 'Male',
        pronouns: 'he/him',
        age: '28',
        nationality: 'Dutch',
      },
      chronology: {
        birth: '1997-09-30',
        debut: '2015-03-15',
        retirement: null,
      },
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'max-verstappen',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    first: 'Charles',
    middle: '',
    last: 'Leclerc',
    alias: 'CL16',
    toggle: 'advanced',
    type: 3,
    basics: {
      enable: true,
      description: 'Ferrari Formula 1 driver',
      identifier: {
        number: '16',
        nickname: 'Il Predestinato',
        competition: 'F1',
        callsign: 'Lec',
      },
      identity: {
        gender: 'Male',
        pronouns: 'he/him',
        age: '28',
        nationality: 'Monegasque',
      },
      chronology: {
        birth: '1997-10-16',
        debut: '2018-03-25',
        retirement: null,
      },
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'charles-leclerc',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
] as const
