// FILE: src/collections/Competition/Event/seeders/preload.ts
export const PRELOAD_EVENT = (categoriesIds: number[]) => [
  {
    name: 'British Grand Prix',
    toggle: 'advanced',
    type: categoriesIds[185],
    basics: { enable: true, description: 'The British Grand Prix at Silverstone Circuit.', identifiers: { code: 'GBR', round: '12' }, status: 'Scheduled', access: 'Public', visibility: { show: true } },
    details: { enable: true, season: 1, location: 1, visibility: { show: true } },
    traits: { enable: true, chronology: { start: '2026-07-03T08:00:00.000Z', end: '2026-07-05T18:00:00.000Z', timezone: 'Europe/London' }, format: 1, visibility: { show: true } },
    metrics: { enable: true, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'British Grand Prix 2026 | AF Motorsport', description: 'Formula 1 British Grand Prix at Silverstone Circuit' },
    generateSlug: false, slug: 'british-grand-prix-2026',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Monaco Grand Prix',
    toggle: 'advanced',
    type: categoriesIds[53],
    basics: { enable: true, description: 'The prestigious Monaco Grand Prix street circuit race.', identifiers: { code: 'MCO', round: '7' }, status: 'Scheduled', access: 'Public', visibility: { show: true } },
    details: { enable: true, season: 1, location: 4, visibility: { show: true } },
    traits: { enable: true, chronology: { start: '2026-05-22T08:00:00.000Z', end: '2026-05-24T18:00:00.000Z', timezone: 'Europe/Monaco' }, format: 1, visibility: { show: true } },
    metrics: { enable: true, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Monaco Grand Prix 2026 | AF Motorsport', description: 'Formula 1 Monaco Grand Prix street circuit racing' },
    generateSlug: false, slug: 'monaco-grand-prix-2026',
    visibility: { check_publish: true, check_featured: true, check_pinned: true }
  },
  {
    name: 'Italian Grand Prix',
    toggle: 'advanced',
    type: categoriesIds[146],
    basics: { enable: true, description: 'The Temple of Speed at Autodromo Nazionale di Monza.', identifiers: { code: 'ITA', round: '16' }, status: 'Scheduled', access: 'Public', visibility: { show: true } },
    details: { enable: true, season: 1, location: 9, visibility: { show: true } },
    traits: { enable: true, chronology: { start: '2026-09-04T08:00:00.000Z', end: '2026-09-06T18:00:00.000Z', timezone: 'Europe/Rome' }, format: 1, visibility: { show: true } },
    metrics: { enable: true, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Italian Grand Prix 2026 | AF Motorsport', description: 'Formula 1 Italian Grand Prix at Monza circuit' },
    generateSlug: false, slug: 'italian-grand-prix-2026',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Belgian Grand Prix',
    toggle: 'advanced',
    type: categoriesIds[123],
    basics: { enable: true, description: 'The ultimate drivers circuit at Spa-Francorchamps.', identifiers: { code: 'BEL', round: '14' }, status: 'Scheduled', access: 'Public', visibility: { show: true } },
    details: { enable: true, season: 1, location: 5, visibility: { show: true } },
    traits: { enable: true, chronology: { start: '2026-07-24T08:00:00.000Z', end: '2026-07-26T18:00:00.000Z', timezone: 'Europe/Brussels' }, format: 1, visibility: { show: true } },
    metrics: { enable: true, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Belgian Grand Prix 2026 | AF Motorsport', description: 'Formula 1 Belgian Grand Prix at Spa-Francorchamps' },
    generateSlug: false, slug: 'belgian-grand-prix-2026',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Japanese Grand Prix',
    toggle: 'advanced',
    type: categoriesIds[38],
    basics: { enable: true, description: 'Technical mastery challenge at Suzuka International Racing Course.', identifiers: { code: 'JPN', round: '18' }, status: 'Scheduled', access: 'Public', visibility: { show: true } },
    details: { enable: true, season: 1, location: 6, visibility: { show: true } },
    traits: { enable: true, chronology: { start: '2026-09-25T01:00:00.000Z', end: '2026-09-27T11:00:00.000Z', timezone: 'Asia/Tokyo' }, format: 1, visibility: { show: true } },
    metrics: { enable: true, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Japanese Grand Prix 2026 | AF Motorsport', description: 'Formula 1 Japanese Grand Prix at Suzuka circuit' },
    generateSlug: false, slug: 'japanese-grand-prix-2026',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'United States Grand Prix',
    toggle: 'advanced',
    type: categoriesIds[122],
    basics: { enable: true, description: 'Americas premier motorsport venue at Circuit of the Americas.', identifiers: { code: 'USA', round: '19' }, status: 'Scheduled', access: 'Public', visibility: { show: true } },
    details: { enable: true, season: 1, location: 7, visibility: { show: true } },
    traits: { enable: true, chronology: { start: '2026-10-16T13:00:00.000Z', end: '2026-10-18T21:00:00.000Z', timezone: 'America/Chicago' }, format: 1, visibility: { show: true } },
    metrics: { enable: true, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'United States Grand Prix 2026 | AF Motorsport', description: 'Formula 1 United States Grand Prix at COTA Austin' },
    generateSlug: false, slug: 'united-states-grand-prix-2026',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Brazilian Grand Prix',
    toggle: 'advanced',
    type: categoriesIds[17],
    basics: { enable: true, description: 'The peoples circuit at Autódromo José Carlos Pace Interlagos.', identifiers: { code: 'BRA', round: '21' }, status: 'Scheduled', access: 'Public', visibility: { show: true } },
    details: { enable: true, season: 1, location: 8, visibility: { show: true } },
    traits: { enable: true, chronology: { start: '2026-11-06T11:00:00.000Z', end: '2026-11-08T19:00:00.000Z', timezone: 'America/Sao_Paulo' }, format: 1, visibility: { show: true } },
    metrics: { enable: true, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Brazilian Grand Prix 2026 | AF Motorsport', description: 'Formula 1 Brazilian Grand Prix at Interlagos São Paulo' },
    generateSlug: false, slug: 'brazilian-grand-prix-2026',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Abu Dhabi Grand Prix',
    toggle: 'advanced',
    type: categoriesIds[245],
    basics: { enable: true, description: 'Season finale twilight racing at Yas Marina Circuit.', identifiers: { code: 'UAE', round: '24' }, status: 'Scheduled', access: 'Public', visibility: { show: true } },
    details: { enable: true, season: 1, location: 14, visibility: { show: true } },
    traits: { enable: true, chronology: { start: '2026-11-27T09:00:00.000Z', end: '2026-11-29T17:00:00.000Z', timezone: 'Asia/Dubai' }, format: 1, visibility: { show: true } },
    metrics: { enable: true, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Abu Dhabi Grand Prix 2026 | AF Motorsport', description: 'Formula 1 Abu Dhabi Grand Prix season finale at Yas Marina' },
    generateSlug: false, slug: 'abu-dhabi-grand-prix-2026',
    visibility: { check_publish: true, check_featured: true, check_pinned: true }
  },
  {
    name: '24 Hours of Le Mans',
    toggle: 'advanced',
    type: categoriesIds[243],
    basics: { enable: true, description: 'The worlds most prestigious endurance race at Circuit de la Sarthe.', identifiers: { code: 'LMS', round: '4' }, status: 'Scheduled', access: 'Public', visibility: { show: true } },
    details: { enable: true, season: 2, location: 10, visibility: { show: true } },
    traits: { enable: true, chronology: { start: '2026-06-13T13:00:00.000Z', end: '2026-06-14T13:00:00.000Z', timezone: 'Europe/Paris' }, format: 2, visibility: { show: true } },
    metrics: { enable: true, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: '24 Hours of Le Mans 2026 | AF Motorsport', description: 'World Endurance Championship 24 Hours of Le Mans endurance race' },
    generateSlug: false, slug: '24-hours-of-le-mans-2026',
    visibility: { check_publish: true, check_featured: true, check_pinned: true }
  },
  {
    name: 'Indianapolis 500',
    toggle: 'advanced',
    type: categoriesIds[52],
    basics: { enable: true, description: 'The Greatest Spectacle in Racing at Indianapolis Motor Speedway.', identifiers: { code: 'IND', round: '6' }, status: 'Scheduled', access: 'Public', visibility: { show: true } },
    details: { enable: true, season: 3, location: 12, visibility: { show: true } },
    traits: { enable: true, chronology: { start: '2026-05-24T12:00:00.000Z', end: '2026-05-24T19:00:00.000Z', timezone: 'America/Indiana/Indianapolis' }, format: 2, visibility: { show: true } },
    metrics: { enable: true, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Indianapolis 500 2026 | AF Motorsport', description: 'IndyCar Series Indianapolis 500 oval racing classic' },
    generateSlug: false, slug: 'indianapolis-500-2026',
    visibility: { check_publish: true, check_featured: true, check_pinned: true }
  },
  {
    name: 'Bathurst 1000',
    toggle: 'advanced',
    type: categoriesIds[215],
    basics: { enable: true, description: 'The Great Race at Mount Panorama Circuit.', identifiers: { code: 'AUS', round: '11' }, status: 'Scheduled', access: 'Public', visibility: { show: true } },
    details: { enable: true, season: 4, location: 13, visibility: { show: true } },
    traits: { enable: true, chronology: { start: '2026-10-08T20:00:00.000Z', end: '2026-10-11T06:00:00.000Z', timezone: 'Australia/Sydney' }, format: 3, visibility: { show: true } },
    metrics: { enable: true, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Bathurst 1000 2026 | AF Motorsport', description: 'Supercars Championship Bathurst 1000 endurance classic' },
    generateSlug: false, slug: 'bathurst-1000-2026',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Daytona 24 Hours',
    toggle: 'advanced',
    type: categoriesIds[232],
    basics: { enable: true, description: 'Season opening endurance classic at Daytona International Speedway.', identifiers: { code: 'DAY', round: '1' }, status: 'Scheduled', access: 'Public', visibility: { show: true } },
    details: { enable: true, season: 5, location: 11, visibility: { show: true } },
    traits: { enable: true, chronology: { start: '2026-01-24T19:00:00.000Z', end: '2026-01-25T19:00:00.000Z', timezone: 'America/New_York' }, format: 2, visibility: { show: true } },
    metrics: { enable: true, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Daytona 24 Hours 2026 | AF Motorsport', description: 'IMSA WeatherTech SportsCar Championship Daytona 24 Hours' },
    generateSlug: false, slug: 'daytona-24-hours-2026',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Nürburgring 24 Hours',
    toggle: 'advanced',
    type: categoriesIds[107],
    basics: { enable: true, description: 'The Green Hell endurance challenge at Nürburgring Nordschleife.', identifiers: { code: 'N24', round: '5' }, status: 'Scheduled', access: 'Public', visibility: { show: true } },
    details: { enable: true, season: 6, location: 3, visibility: { show: true } },
    traits: { enable: true, chronology: { start: '2026-06-20T13:00:00.000Z', end: '2026-06-21T13:00:00.000Z', timezone: 'Europe/Berlin' }, format: 2, visibility: { show: true } },
    metrics: { enable: true, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Nürburgring 24 Hours 2026 | AF Motorsport', description: 'ADAC TotalEnergies 24 Hours Nürburgring endurance race' },
    generateSlug: false, slug: 'nurburgring-24-hours-2026',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Spa 24 Hours',
    toggle: 'advanced',
    type: categoriesIds[126],
    basics: { enable: true, description: 'GT endurance racing at Circuit de Spa-Francorchamps.', identifiers: { code: 'SPA', round: '7' }, status: 'Scheduled', access: 'Public', visibility: { show: true } },
    details: { enable: true, season: 7, location: 5, visibility: { show: true } },
    traits: { enable: true, chronology: { start: '2026-07-25T13:00:00.000Z', end: '2026-07-26T13:00:00.000Z', timezone: 'Europe/Brussels' }, format: 2, visibility: { show: true } },
    metrics: { enable: true, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Spa 24 Hours 2026 | AF Motorsport', description: 'GT World Challenge Europe Spa 24 Hours endurance race' },
    generateSlug: false, slug: 'spa-24-hours-2026',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Monza Rally Show',
    toggle: 'advanced',
    type: categoriesIds[41],
    basics: { enable: true, description: 'End of season rally exhibition at Autodromo Nazionale di Monza.', identifiers: { code: 'MRZ', round: '1' }, status: 'Scheduled', access: 'Public', visibility: { show: true } },
    details: { enable: true, season: 8, location: 9, visibility: { show: true } },
    traits: { enable: true, chronology: { start: '2026-12-03T09:00:00.000Z', end: '2026-12-04T18:00:00.000Z', timezone: 'Europe/Rome' }, format: 2, visibility: { show: true } },
    metrics: { enable: true, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Monza Rally Show 2026 | AF Motorsport', description: 'WRC Monza Rally Show exhibition event' },
    generateSlug: false, slug: 'monza-rally-show-2026',
    visibility: { check_publish: true, check_featured: false, check_pinned: false }
  },
  {
    name: 'Goodwood Festival of Speed',
    toggle: 'advanced',
    type: categoriesIds[9],
    basics: { enable: true, description: 'Historic motorsport celebration at Goodwood House.', identifiers: { code: 'GWD', round: '1' }, status: 'Scheduled', access: 'Public', visibility: { show: true } },
    details: { enable: true, season: 9, location: 1, visibility: { show: true } },
    traits: { enable: true, chronology: { start: '2026-06-26T08:00:00.000Z', end: '2026-06-29T18:00:00.000Z', timezone: 'Europe/London' }, format: 3, visibility: { show: true } },
    metrics: { enable: true, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Goodwood Festival of Speed 2026 | AF Motorsport', description: 'Historic motorsport celebration and hillclimb event' },
    generateSlug: false, slug: 'goodwood-festival-of-speed-2026',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Pikes Peak International Hill Climb',
    toggle: 'advanced',
    type: categoriesIds[105],
    basics: { enable: true, description: 'The Race to the Clouds at Pikes Peak Mountain.', identifiers: { code: 'PPK', round: '1' }, status: 'Scheduled', access: 'Public', visibility: { show: true } },
    details: { enable: true, season: 10, location: 15, visibility: { show: true } },
    traits: { enable: true, chronology: { start: '2026-06-28T13:00:00.000Z', end: '2026-06-28T18:00:00.000Z', timezone: 'America/Denver' }, format: 2, visibility: { show: true } },
    metrics: { enable: true, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Pikes Peak Hill Climb 2026 | AF Motorsport', description: 'Pikes Peak International Hill Climb mountain racing event' },
    generateSlug: false, slug: 'pikes-peak-hill-climb-2026',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Macau Grand Prix',
    toggle: 'advanced',
    type: categoriesIds[118],
    basics: { enable: true, description: 'Street circuit racing spectacle in Macau.', identifiers: { code: 'MAC', round: '1' }, status: 'Scheduled', access: 'Public', visibility: { show: true } },
    details: { enable: true, season: 11, location: 16, visibility: { show: true } },
    traits: { enable: true, chronology: { start: '2026-11-13T02:00:00.000Z', end: '2026-11-15T10:00:00.000Z', timezone: 'Asia/Macau' }, format: 1, visibility: { show: true } },
    metrics: { enable: true, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Macau Grand Prix 2026 | AF Motorsport', description: 'Macau Grand Prix street circuit racing event' },
    generateSlug: false, slug: 'macau-grand-prix-2026',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Race of Champions',
    toggle: 'advanced',
    type: categoriesIds[27],
    basics: { enable: true, description: 'Champions from different disciplines compete head-to-head.', identifiers: { code: 'ROC', round: '1' }, status: 'Scheduled', access: 'InviteOnly', visibility: { show: true } },
    details: { enable: true, season: 12, location: 17, visibility: { show: true } },
    traits: { enable: true, chronology: { start: '2026-01-30T14:00:00.000Z', end: '2026-01-31T20:00:00.000Z', timezone: 'Europe/Stockholm' }, format: 2, visibility: { show: true } },
    metrics: { enable: true, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Race of Champions 2026 | AF Motorsport', description: 'Race of Champions cross-discipline motorsport showcase' },
    generateSlug: false, slug: 'race-of-champions-2026',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Formula E London E-Prix',
    toggle: 'advanced',
    type: categoriesIds[166],
    basics: { enable: true, description: 'Electric racing through the streets of ExCeL London.', identifiers: { code: 'LDN', round: '15' }, status: 'Scheduled', access: 'Public', visibility: { show: true } },
    details: { enable: true, season: 13, location: 18, visibility: { show: true } },
    traits: { enable: true, chronology: { start: '2026-07-18T09:00:00.000Z', end: '2026-07-19T17:00:00.000Z', timezone: 'Europe/London' }, format: 2, visibility: { show: true } },
    metrics: { enable: true, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'London E-Prix 2026 | AF Motorsport', description: 'ABB FIA Formula E World Championship London E-Prix' },
    generateSlug: false, slug: 'london-e-prix-2026',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  }
] as const;
