// FILE: src/collections/Competition/Season/seeders/preload.ts
export const PRELOAD_SEASON = (categoriesIds: number[]) => [
  {
    name: 'Formula 1 Championship Season - Standard Format',
    series: 1,
    toggle: 'advanced',
    type: categoriesIds[185],
    basics: { enable: true, description: 'Standard championship season format for Formula 1 World Championship with sprint and qualifying sessions.', identifiers: { code: 'F1-STD', abbreviation: 'F1' }, visibility: { show: true } },
    details: { enable: true, schedule: 1, visibility: { show: true } },
    metrics: { enable: true, counts: { entries: 20, events: 24, races: 24 }, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'F1 Championship Season | AF Motorsport', description: 'Standard Formula 1 World Championship season structure' },
    generateSlug: false, slug: 'f1-championship-season-standard',
    visibility: { check_publish: true, check_featured: true, check_pinned: true }
  },
  {
    name: 'World Endurance Championship Season - Multi-Class Format',
    series: 2,
    toggle: 'advanced',
    type: categoriesIds[53],
    basics: { enable: true, description: 'Multi-class endurance racing season format with prototype and GT categories.', identifiers: { code: 'WEC-MC', abbreviation: 'WEC' }, visibility: { show: true } },
    details: { enable: true, schedule: 2, visibility: { show: true } },
    metrics: { enable: true, counts: { entries: 38, events: 8, races: 8 }, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'WEC Multi-Class Season | AF Motorsport', description: 'World Endurance Championship multi-class season structure' },
    generateSlug: false, slug: 'wec-season-multi-class-format',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'IndyCar Series Season - Oval/Road Mix Format',
    series: 3,
    toggle: 'advanced',
    type: categoriesIds[146],
    basics: { enable: true, description: 'Mixed circuit season format featuring oval, road, and street courses.', identifiers: { code: 'IND-MIX', abbreviation: 'INDY' }, visibility: { show: true } },
    details: { enable: true, schedule: 3, visibility: { show: true } },
    metrics: { enable: true, counts: { entries: 26, events: 17, races: 17 }, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'IndyCar Mixed Format Season | AF Motorsport', description: 'IndyCar Series season with oval and road course events' },
    generateSlug: false, slug: 'indycar-season-oval-road-mix',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'GT World Challenge Season - Sprint/Endurance Format',
    series: 4,
    toggle: 'advanced',
    type: categoriesIds[123],
    basics: { enable: true, description: 'Dual-format season with sprint races and endurance events for GT3 competition.', identifiers: { code: 'GTWC-SE', abbreviation: 'GTWC' }, visibility: { show: true } },
    details: { enable: true, schedule: 4, visibility: { show: true } },
    metrics: { enable: true, counts: { entries: 45, events: 10, races: 20 }, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'GT World Challenge Season | AF Motorsport', description: 'GT3 championship season with sprint and endurance formats' },
    generateSlug: false, slug: 'gt-world-challenge-season-format',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Formula E Championship Season - Street Circuit Format',
    series: 5,
    toggle: 'advanced',
    type: categoriesIds[38],
    basics: { enable: true, description: 'All-electric racing season on temporary street circuits in urban environments.', identifiers: { code: 'FE-SC', abbreviation: 'FE' }, visibility: { show: true } },
    details: { enable: true, schedule: 5, visibility: { show: true } },
    metrics: { enable: true, counts: { entries: 22, events: 16, races: 16 }, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Formula E Street Circuit Season | AF Motorsport', description: 'Electric racing championship season on urban street circuits' },
    generateSlug: false, slug: 'formula-e-season-street-circuit',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'World Rally Championship Season - Terrain Variety Format',
    series: 6,
    toggle: 'advanced',
    type: categoriesIds[122],
    basics: { enable: true, description: 'Multi-terrain rally season featuring gravel, tarmac, snow, and mixed surface events.', identifiers: { code: 'WRC-TV', abbreviation: 'WRC' }, visibility: { show: true } },
    details: { enable: true, schedule: 6, visibility: { show: true } },
    metrics: { enable: true, counts: { entries: 18, events: 13, races: 13 }, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'WRC Terrain Variety Season | AF Motorsport', description: 'World Rally Championship season with diverse surface conditions' },
    generateSlug: false, slug: 'wrc-season-terrain-variety',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'NASCAR Cup Series Season - Playoff Format',
    series: 7,
    toggle: 'advanced',
    type: categoriesIds[17],
    basics: { enable: true, description: 'Stock car racing season with elimination-style playoff championship structure.', identifiers: { code: 'NCS-PF', abbreviation: 'NASCAR' }, visibility: { show: true } },
    details: { enable: true, schedule: 7, visibility: { show: true } },
    metrics: { enable: true, counts: { entries: 36, events: 36, races: 36 }, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'NASCAR Playoff Format Season | AF Motorsport', description: 'NASCAR Cup Series season with elimination playoff structure' },
    generateSlug: false, slug: 'nascar-cup-season-playoff-format',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'MotoGP World Championship Season - Grand Prix Format',
    series: 8,
    toggle: 'advanced',
    type: categoriesIds[245],
    basics: { enable: true, description: 'Premier motorcycle racing season with sprint and main race format at each Grand Prix.', identifiers: { code: 'MGP-GP', abbreviation: 'MotoGP' }, visibility: { show: true } },
    details: { enable: true, schedule: 8, visibility: { show: true } },
    metrics: { enable: true, counts: { entries: 24, events: 20, races: 40 }, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'MotoGP Grand Prix Season | AF Motorsport', description: 'Premier motorcycle racing championship season with sprint format' },
    generateSlug: false, slug: 'motogp-season-grand-prix-format',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Development Series Season - Rookie Focus Format',
    series: 9,
    toggle: 'advanced',
    type: categoriesIds[243],
    basics: { enable: true, description: 'Driver development season format prioritizing rookie progression and skill assessment.', identifiers: { code: 'DEV-RF', abbreviation: 'DEV' }, visibility: { show: true } },
    details: { enable: true, schedule: 9, visibility: { show: true } },
    metrics: { enable: true, counts: { entries: 30, events: 12, races: 24 }, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Development Rookie Season | AF Motorsport', description: 'Driver development championship season focused on emerging talent' },
    generateSlug: false, slug: 'development-season-rookie-focus',
    visibility: { check_publish: true, check_featured: false, check_pinned: false }
  },
  {
    name: 'Historic Racing Season - Heritage Format',
    series: 10,
    toggle: 'advanced',
    type: categoriesIds[52],
    basics: { enable: true, description: 'Historic vehicle competition season celebrating motorsport heritage and classic racing.', identifiers: { code: 'HST-HF', abbreviation: 'HIST' }, visibility: { show: true } },
    details: { enable: true, schedule: 10, visibility: { show: true } },
    metrics: { enable: true, counts: { entries: 50, events: 8, races: 16 }, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Historic Racing Heritage Season | AF Motorsport', description: 'Classic vehicle championship season celebrating motorsport heritage' },
    generateSlug: false, slug: 'historic-racing-season-heritage',
    visibility: { check_publish: true, check_featured: false, check_pinned: true }
  },
  {
    name: 'Test Season - Development Format',
    series: 11,
    toggle: 'advanced',
    type: categoriesIds[215],
    basics: { enable: true, description: 'Non-championship testing season for vehicle development and driver evaluation.', identifiers: { code: 'TST-DF', abbreviation: 'TEST' }, visibility: { show: true } },
    details: { enable: true, schedule: 11, visibility: { show: true } },
    metrics: { enable: true, counts: { entries: 15, events: 6, races: 0 }, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Test Development Season | AF Motorsport', description: 'Non-championship testing season for vehicle and driver development' },
    generateSlug: false, slug: 'test-season-development-format',
    visibility: { check_publish: true, check_featured: false, check_pinned: false }
  },
  {
    name: 'Exhibition Season - Showcase Format',
    series: 12,
    toggle: 'advanced',
    type: categoriesIds[232],
    basics: { enable: true, description: 'Non-competitive exhibition season for promotional events and fan engagement.', identifiers: { code: 'EXH-SF', abbreviation: 'EXH' }, visibility: { show: true } },
    details: { enable: true, schedule: 12, visibility: { show: true } },
    metrics: { enable: true, counts: { entries: 10, events: 4, races: 4 }, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Exhibition Showcase Season | AF Motorsport', description: 'Non-competitive exhibition season for promotional motorsport events' },
    generateSlug: false, slug: 'exhibition-season-showcase-format',
    visibility: { check_publish: true, check_featured: false, check_pinned: false }
  },
  {
    name: 'Anniversary Season - Commemorative Format',
    series: 13,
    toggle: 'advanced',
    type: categoriesIds[107],
    basics: { enable: true, description: 'Special commemorative season celebrating milestone anniversaries in motorsport history.', identifiers: { code: 'ANN-CF', abbreviation: 'ANN' }, visibility: { show: true } },
    details: { enable: true, schedule: 13, visibility: { show: true } },
    metrics: { enable: true, counts: { entries: 25, events: 5, races: 5 }, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Anniversary Commemorative Season | AF Motorsport', description: 'Special season celebrating motorsport milestone anniversaries' },
    generateSlug: false, slug: 'anniversary-season-commemorative',
    visibility: { check_publish: true, check_featured: true, check_pinned: true }
  },
  {
    name: 'Farewell Season - Legacy Format',
    series: 14,
    toggle: 'advanced',
    type: categoriesIds[126],
    basics: { enable: true, description: 'Final season format for retiring series, vehicles, or legendary competitors.', identifiers: { code: 'FAR-LF', abbreviation: 'FARE' }, visibility: { show: true } },
    details: { enable: true, schedule: 14, visibility: { show: true } },
    metrics: { enable: true, counts: { entries: 20, events: 10, races: 10 }, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Farewell Legacy Season | AF Motorsport', description: 'Final season format for retiring motorsport series or competitors' },
    generateSlug: false, slug: 'farewell-season-legacy-format',
    visibility: { check_publish: true, check_featured: false, check_pinned: true }
  },
  {
    name: 'Pro-Am Championship Season - Mixed Class Format',
    series: 15,
    toggle: 'advanced',
    type: categoriesIds[41],
    basics: { enable: true, description: 'Professional-amateur mixed class season format promoting driver development.', identifiers: { code: 'PAM-MC', abbreviation: 'ProAm' }, visibility: { show: true } },
    details: { enable: true, schedule: 15, visibility: { show: true } },
    metrics: { enable: true, counts: { entries: 32, events: 12, races: 24 }, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Pro-Am Mixed Class Season | AF Motorsport', description: 'Professional-amateur mixed class championship season format' },
    generateSlug: false, slug: 'pro-am-season-mixed-class',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Esports Championship Season - Virtual Format',
    series: 16,
    toggle: 'advanced',
    type: categoriesIds[9],
    basics: { enable: true, description: 'Virtual racing championship season conducted through simulation platforms.', identifiers: { code: 'ESP-VF', abbreviation: 'ESPORTS' }, visibility: { show: true } },
    details: { enable: true, schedule: 16, visibility: { show: true } },
    metrics: { enable: true, counts: { entries: 40, events: 18, races: 36 }, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Esports Virtual Season | AF Motorsport', description: 'Virtual racing championship season through simulation platforms' },
    generateSlug: false, slug: 'esports-season-virtual-format',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Winter Series Season - Off-Season Format',
    series: 17,
    toggle: 'advanced',
    type: categoriesIds[105],
    basics: { enable: true, description: 'Off-season winter racing series for skill maintenance and team preparation.', identifiers: { code: 'WIN-OF', abbreviation: 'WINTER' }, visibility: { show: true } },
    details: { enable: true, schedule: 17, visibility: { show: true } },
    metrics: { enable: true, counts: { entries: 18, events: 4, races: 8 }, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Winter Off-Season Series | AF Motorsport', description: 'Off-season winter racing series for preparation and development' },
    generateSlug: false, slug: 'winter-series-off-season-format',
    visibility: { check_publish: true, check_featured: false, check_pinned: false }
  },
  {
    name: 'Summer Series Season - Peak Format',
    series: 18,
    toggle: 'advanced',
    type: categoriesIds[118],
    basics: { enable: true, description: 'Peak season racing series during optimal weather and fan attendance periods.', identifiers: { code: 'SUM-PF', abbreviation: 'SUMMER' }, visibility: { show: true } },
    details: { enable: true, schedule: 18, visibility: { show: true } },
    metrics: { enable: true, counts: { entries: 24, events: 14, races: 28 }, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Summer Peak Season Series | AF Motorsport', description: 'Peak season racing series during optimal weather conditions' },
    generateSlug: false, slug: 'summer-series-peak-format',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Invitational Trophy Season - Select Format',
    series: 19,
    toggle: 'advanced',
    type: categoriesIds[27],
    basics: { enable: true, description: 'Invitation-only trophy season for elite competitors and special entries.', identifiers: { code: 'INV-SF', abbreviation: 'INV' }, visibility: { show: true } },
    details: { enable: true, schedule: 19, visibility: { show: true } },
    metrics: { enable: true, counts: { entries: 12, events: 3, races: 6 }, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Invitational Trophy Season | AF Motorsport', description: 'Elite invitation-only trophy season for selected competitors' },
    generateSlug: false, slug: 'invitational-trophy-season-select',
    visibility: { check_publish: true, check_featured: true, check_pinned: true }
  },
  {
    name: 'Support Series Season - Feeder Format',
    series: 20,
    toggle: 'advanced',
    type: categoriesIds[166],
    basics: { enable: true, description: 'Feeder series season supporting main championship events with emerging talent.', identifiers: { code: 'SUP-FF', abbreviation: 'SUPPORT' }, visibility: { show: true } },
    details: { enable: true, schedule: 20, visibility: { show: true } },
    metrics: { enable: true, counts: { entries: 28, events: 20, races: 40 }, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Support Feeder Series Season | AF Motorsport', description: 'Feeder series season supporting main championship with emerging talent' },
    generateSlug: false, slug: 'support-series-season-feeder',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  }
] as const;
