export const PRELOAD_AWARD = (categoriesIds: number[], narrativesIds: number[]) => [
  {
    name: 'FIA Formula 1 World Drivers\' Championship Trophy',
    toggle: 'advanced',
    type: categoriesIds[185],
    basics: {
      enable: true,
      description: 'The pinnacle achievement in Formula 1 racing, awarded annually to the driver accumulating the most championship points across a complete season of Grand Prix competition under FIA sporting regulations.',
      visibility: { show: true },
    },
    details: {
      enable: true,
      narrative: narrativesIds[29],
      visibility: { show: true },
    },
    contexts: {
      enable: true,
      entities: {
        relationTo: 'organizations',
        value: 1,
      },
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'fia-f1-world-drivers-championship-trophy',
    visibility: { check_publish: true, check_featured: true, check_pinned: true },
  },
  {
    name: 'Monaco Grand Prix Race Winner Award',
    toggle: 'advanced',
    type: categoriesIds[53],
    basics: {
      enable: true,
      description: 'Prestigious trophy presented to the driver who finishes first at the Monaco Grand Prix, recognizing mastery of the most demanding street circuit in motorsport with its narrow confines and zero-margin precision requirements.',
      visibility: { show: true },
    },
    details: {
      enable: true,
      narrative: narrativesIds[1],
      visibility: { show: true },
    },
    contexts: {
      enable: true,
      entities: {
        relationTo: 'organizations',
        value: 2,
      },
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'monaco-gp-race-winner-award',
    visibility: { check_publish: true, check_featured: true, check_pinned: false },
  },
  {
    name: 'Pirelli Pole Position Award',
    toggle: 'advanced',
    type: categoriesIds[146],
    basics: {
      enable: true,
      description: 'Official recognition for the driver who secures pole position in qualifying, demonstrating exceptional single-lap pace, tire management expertise, and strategic execution under pressure conditions.',
      visibility: { show: true },
    },
    details: {
      enable: true,
      narrative: narrativesIds[50],
      visibility: { show: true },
    },
    contexts: {
      enable: true,
      entities: {
        relationTo: 'organizations',
        value: 3,
      },
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'pirelli-pole-position-award',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    name: 'DHL Fastest Lap Award',
    toggle: 'advanced',
    type: categoriesIds[123],
    basics: {
      enable: true,
      description: 'Performance accolade awarded to the driver who records the quickest lap time during a Grand Prix race, highlighting raw speed, tire preservation strategy, and optimal track condition utilization.',
      visibility: { show: true },
    },
    details: {
      enable: true,
      narrative: narrativesIds[31],
      visibility: { show: true },
    },
    contexts: {
      enable: true,
      entities: {
        relationTo: 'organizations',
        value: 4,
      },
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'dhl-fastest-lap-award',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    name: 'WEC Driver of the Race Award',
    toggle: 'advanced',
    type: categoriesIds[38],
    basics: {
      enable: true,
      description: 'Endurance racing honor recognizing the most impactful driver performance across a WEC event, evaluating consistency, stint management, traffic navigation, and contribution to team success over extended race duration.',
      visibility: { show: true },
    },
    details: {
      enable: true,
      narrative: narrativesIds[12],
      visibility: { show: true },
    },
    contexts: {
      enable: true,
      entities: {
        relationTo: 'organizations',
        value: 5,
      },
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'wec-driver-of-the-race-award',
    visibility: { check_publish: true, check_featured: true, check_pinned: false },
  },
  {
    name: 'Red Dot Design Award: Racing Livery',
    toggle: 'advanced',
    type: categoriesIds[122],
    basics: {
      enable: true,
      description: 'International design excellence recognition for outstanding visual identity, livery composition, brand integration, and aesthetic innovation in motorsport vehicle presentation and team branding.',
      visibility: { show: true },
    },
    details: {
      enable: true,
      narrative: narrativesIds[33],
      visibility: { show: true },
    },
    contexts: {
      enable: true,
      entities: {
        relationTo: 'organizations',
        value: 6,
      },
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'red-dot-design-award-racing-livery',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    name: 'FIA Innovation Prize for Sustainable Motorsport',
    toggle: 'advanced',
    type: categoriesIds[17],
    basics: {
      enable: true,
      description: 'Prestigious award celebrating breakthrough technological advancements in sustainable racing solutions, including hybrid powertrain efficiency, renewable materials adoption, and carbon footprint reduction initiatives.',
      visibility: { show: true },
    },
    details: {
      enable: true,
      narrative: narrativesIds[52],
      visibility: { show: true },
    },
    contexts: {
      enable: true,
      entities: {
        relationTo: 'organizations',
        value: 7,
      },
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'fia-innovation-prize-sustainable-motorsport',
    visibility: { check_publish: true, check_featured: true, check_pinned: false },
  },
  {
    name: 'FIA Action of the Year Safety Award',
    toggle: 'advanced',
    type: categoriesIds[245],
    basics: {
      enable: true,
      description: 'Critical recognition for exceptional safety protocol implementation, incident response excellence, medical team coordination, and life-saving interventions during high-risk motorsport competition scenarios.',
      visibility: { show: true },
    },
    details: {
      enable: true,
      narrative: narrativesIds[54],
      visibility: { show: true },
    },
    contexts: {
      enable: true,
      entities: {
        relationTo: 'organizations',
        value: 8,
      },
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'fia-action-of-the-year-safety-award',
    visibility: { check_publish: true, check_featured: true, check_pinned: true },
  },
  {
    name: 'Green Racing Environmental Stewardship Award',
    toggle: 'advanced',
    type: categoriesIds[243],
    basics: {
      enable: true,
      description: 'Environmental leadership accolade honoring teams and organizations demonstrating measurable commitment to ecological responsibility, waste reduction, renewable energy adoption, and sustainable event operations.',
      visibility: { show: true },
    },
    details: {
      enable: true,
      narrative: narrativesIds[30],
      visibility: { show: true },
    },
    contexts: {
      enable: true,
      entities: {
        relationTo: 'organizations',
        value: 9,
      },
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'green-racing-environmental-stewardship-award',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    name: 'FIA Special Recognition for Sporting Excellence',
    toggle: 'advanced',
    type: categoriesIds[52],
    basics: {
      enable: true,
      description: 'Distinctive honor bestowed for extraordinary contributions to motorsport integrity, fair play advocacy, youth development programs, and promotion of ethical competition standards across global racing disciplines.',
      visibility: { show: true },
    },
    details: {
      enable: true,
      narrative: narrativesIds[27],
      visibility: { show: true },
    },
    contexts: {
      enable: true,
      entities: {
        relationTo: 'organizations',
        value: 10,
      },
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'fia-special-recognition-sporting-excellence',
    visibility: { check_publish: true, check_featured: true, check_pinned: false },
  },
  {
    name: 'Motorsport Hall of Fame Induction',
    toggle: 'advanced',
    type: categoriesIds[215],
    basics: {
      enable: true,
      description: 'Lifetime honor recognizing individuals whose careers have fundamentally shaped motorsport history through championship success, technical innovation, leadership excellence, and enduring influence on racing culture.',
      visibility: { show: true },
    },
    details: {
      enable: true,
      narrative: narrativesIds[59],
      visibility: { show: true },
    },
    contexts: {
      enable: true,
      entities: {
        relationTo: 'organizations',
        value: 11,
      },
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'motorsport-hall-of-fame-induction',
    visibility: { check_publish: true, check_featured: true, check_pinned: true },
  },
  {
    name: 'Autosport Lifetime Achievement Award',
    toggle: 'advanced',
    type: categoriesIds[232],
    basics: {
      enable: true,
      description: 'Prestigious career-spanning recognition for individuals whose decades of dedication, mentorship, innovation, and competitive success have elevated the standards and global appeal of professional motorsport.',
      visibility: { show: true },
    },
    details: {
      enable: true,
      narrative: narrativesIds[5],
      visibility: { show: true },
    },
    contexts: {
      enable: true,
      entities: {
        relationTo: 'organizations',
        value: 12,
      },
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'autosport-lifetime-achievement-award',
    visibility: { check_publish: true, check_featured: true, check_pinned: false },
  },
  {
    name: 'FIA Team of the Year Award',
    toggle: 'advanced',
    type: categoriesIds[107],
    basics: {
      enable: true,
      description: 'Collective excellence award honoring the racing organization demonstrating superior technical development, strategic execution, personnel coordination, and championship performance across an entire competitive season.',
      visibility: { show: true },
    },
    details: {
      enable: true,
      narrative: narrativesIds[60],
      visibility: { show: true },
    },
    contexts: {
      enable: true,
      entities: {
        relationTo: 'organizations',
        value: 13,
      },
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'fia-team-of-the-year-award',
    visibility: { check_publish: true, check_featured: true, check_pinned: false },
  },
  {
    name: 'Pit Crew Member of the Year Award',
    toggle: 'advanced',
    type: categoriesIds[126],
    basics: {
      enable: true,
      description: 'Operational excellence recognition for individual pit crew members demonstrating flawless execution, sub-2.5 second stop consistency, safety protocol adherence, and critical contribution to race strategy success.',
      visibility: { show: true },
    },
    details: {
      enable: true,
      narrative: narrativesIds[54],
      visibility: { show: true },
    },
    contexts: {
      enable: true,
      entities: {
        relationTo: 'organizations',
        value: 14,
      },
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'pit-crew-member-of-the-year-award',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    name: 'Long Service Award: 25 Years in Motorsport',
    toggle: 'advanced',
    type: categoriesIds[41],
    basics: {
      enable: true,
      description: 'Dedication honor celebrating individuals who have contributed a quarter-century of continuous service to motorsport through technical expertise, operational reliability, mentorship, and institutional knowledge preservation.',
      visibility: { show: true },
    },
    details: {
      enable: true,
      narrative: narrativesIds[10],
      visibility: { show: true },
    },
    contexts: {
      enable: true,
      entities: {
        relationTo: 'organizations',
        value: 15,
      },
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'long-service-award-25-years-motorsport',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    name: 'Fan Favorite Driver Award',
    toggle: 'advanced',
    type: categoriesIds[9],
    basics: {
      enable: true,
      description: 'Popular vote recognition for the driver who most effectively engages global fan communities through authentic personality, competitive spirit, social media presence, and accessibility to supporters worldwide.',
      visibility: { show: true },
    },
    details: {
      enable: true,
      narrative: narrativesIds[38],
      visibility: { show: true },
    },
    contexts: {
      enable: true,
      entities: {
        relationTo: 'organizations',
        value: 16,
      },
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'fan-favorite-driver-award',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    name: 'Overtake of the Season Award',
    toggle: 'advanced',
    type: categoriesIds[105],
    basics: {
      enable: true,
      description: 'Spectacular maneuver recognition for the most skillful, daring, and technically precise overtaking action of the championship season, evaluated for risk assessment, execution timing, and competitive impact.',
      visibility: { show: true },
    },
    details: {
      enable: true,
      narrative: narrativesIds[46],
      visibility: { show: true },
    },
    contexts: {
      enable: true,
      entities: {
        relationTo: 'organizations',
        value: 17,
      },
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'overtake-of-the-season-award',
    visibility: { check_publish: true, check_featured: true, check_pinned: false },
  },
  {
    name: 'Motorsport Photograph of the Year',
    toggle: 'advanced',
    type: categoriesIds[118],
    basics: {
      enable: true,
      description: 'Visual storytelling award honoring the photographer whose image best captures the emotion, speed, precision, and human drama of professional motorsport competition through technical mastery and artistic vision.',
      visibility: { show: true },
    },
    details: {
      enable: true,
      narrative: narrativesIds[3],
      visibility: { show: true },
    },
    contexts: {
      enable: true,
      entities: {
        relationTo: 'organizations',
        value: 18,
      },
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'motorsport-photograph-of-the-year',
    visibility: { check_publish: true, check_featured: true, check_pinned: false },
  },
  {
    name: 'Rookie of the Year Championship Award',
    toggle: 'advanced',
    type: categoriesIds[27],
    basics: {
      enable: true,
      description: 'Breakthrough performance recognition for the first-year competitor demonstrating exceptional adaptation, rapid skill development, consistent point-scoring, and promising potential for future championship contention.',
      visibility: { show: true },
    },
    details: {
      enable: true,
      narrative: narrativesIds[24],
      visibility: { show: true },
    },
    contexts: {
      enable: true,
      entities: {
        relationTo: 'organizations',
        value: 19,
      },
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'rookie-of-the-year-championship-award',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    name: 'Constructors\' Championship Trophy',
    toggle: 'advanced',
    type: categoriesIds[166],
    basics: {
      enable: true,
      description: 'Premier team achievement award presented to the manufacturer accumulating the highest combined points from both entered cars across a full Formula 1 season, recognizing technical excellence and operational coordination.',
      visibility: { show: true },
    },
    details: {
      enable: true,
      narrative: narrativesIds[2],
      visibility: { show: true },
    },
    contexts: {
      enable: true,
      entities: {
        relationTo: 'organizations',
        value: 20,
      },
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'constructors-championship-trophy',
    visibility: { check_publish: true, check_featured: true, check_pinned: true },
  },
] as const
