// FILE: src/collections/Attributes/Classification/seeders/preload.ts
export const PRELOAD_CLASSIFICATION = (categoriesIds: number[]) => [
  {
    id: 1,
    name: 'Formula 1',
    type: categoriesIds[185],
    basics: { enable: true, description: 'The premier class of open-wheel single-seater racing governed by the FIA, featuring the most technologically advanced race cars and elite drivers competing for the World Championship.', visibility: { show: true } },
    details: { enable: true, definition: 'FIA-sanctioned international championship featuring hybrid-powered open-wheel race cars with ground-effect aerodynamics, competing across a global calendar of circuits.', criteria: 'Teams must hold a valid FIA entry, meet all technical and sporting regulations, pass scrutineering, and fulfill financial and operational commitments to the championship.', visibility: { show: true } },
    contexts: { enable: false, notes: null, visibility: { show: false } },
    seo: { title: 'Formula 1 Classification | AF Motorsport', description: 'Official Formula 1 World Championship classification standards and technical regulations', image: null },
    generateSlug: false,
    slug: 'formula-1',
    categories: null,
    tags: null,
    visibility: { check_publish: true, check_featured: true, check_pinned: true },
    updatedAt: '2026-02-22T09:20:00.000Z',
    createdAt: '2026-01-05T10:00:00.000Z'
  },
  {
    id: 2,
    name: 'FIA World Endurance Championship',
    type: categoriesIds[53],
    basics: { enable: true, description: 'Global endurance racing championship featuring prototype and grand touring cars competing in races from 6 hours to 24 hours in duration.', visibility: { show: true } },
    details: { enable: true, definition: 'International championship sanctioned by the FIA and ACO for Hypercar, LMP2, and LMGT3 class vehicles competing in endurance events worldwide.', criteria: 'Vehicles must meet class-specific technical regulations, teams must register with the FIA, and entries must complete minimum distance requirements for classification.', visibility: { show: true } },
    contexts: { enable: false, notes: null, visibility: { show: false } },
    seo: { title: 'WEC Classification | AF Motorsport', description: 'FIA World Endurance Championship classification standards and multi-class regulations', image: null },
    generateSlug: false,
    slug: 'fia-world-endurance-championship',
    categories: null,
    tags: null,
    visibility: { check_publish: true, check_featured: true, check_pinned: false },
    updatedAt: '2026-02-21T15:10:00.000Z',
    createdAt: '2026-01-08T14:30:00.000Z'
  },
  {
    id: 3,
    name: 'GT3',
    type: categoriesIds[146],
    basics: { enable: true, description: 'Production-based Grand Touring customer racing category featuring Balance of Performance regulations to ensure competitive parity across manufacturers.', visibility: { show: true } },
    details: { enable: true, definition: 'FIA-homologated GT3 specification for production-based grand touring cars modified for competition with restricted aerodynamics, standardized electronics, and BoP adjustments.', criteria: 'Vehicles must be derived from road-going production models with minimum production numbers, meet FIA GT3 technical regulations, and compete under Balance of Performance parameters.', visibility: { show: true } },
    contexts: { enable: false, notes: null, visibility: { show: false } },
    seo: { title: 'GT3 Classification | AF Motorsport', description: 'GT3 customer racing technical specifications and Balance of Performance regulations', image: null },
    generateSlug: false,
    slug: 'gt3',
    categories: null,
    tags: null,
    visibility: { check_publish: true, check_featured: false, check_pinned: true },
    updatedAt: '2026-02-20T11:45:00.000Z',
    createdAt: '2026-01-10T09:15:00.000Z'
  },
  {
    id: 4,
    name: 'Formula 2',
    type: categoriesIds[123],
    basics: { enable: true, description: 'FIA-sanctioned feeder series to Formula 1 using identical chassis and engine packages to develop future championship talent.', visibility: { show: true } },
    details: { enable: true, definition: 'Single-make championship featuring Dallara chassis and Mecachrome V6 turbo engines, serving as the primary development pathway for Formula 1.', criteria: 'Drivers must hold an FIA Super Licence or be eligible for one, teams must meet entry requirements, and vehicles must conform to standardized technical specifications.', visibility: { show: true } },
    contexts: { enable: false, notes: null, visibility: { show: false } },
    seo: { title: 'Formula 2 Classification | AF Motorsport', description: 'FIA Formula 2 Championship classification and driver development pathway standards', image: null },
    generateSlug: false,
    slug: 'formula-2',
    categories: null,
    tags: null,
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
    updatedAt: '2026-02-21T16:00:00.000Z',
    createdAt: '2026-01-11T10:30:00.000Z'
  },
  {
    id: 5,
    name: 'Formula 3',
    type: categoriesIds[38],
    basics: { enable: true, description: 'Entry-level FIA single-seater championship serving as the first step on the Global Pathway to Formula 1.', visibility: { show: true } },
    details: { enable: true, definition: 'International junior formula series using identical Dallara F3 chassis and Mecachrome engines to identify and develop emerging racing talent.', criteria: 'Drivers must meet age and licensing requirements, teams must hold FIA registration, and vehicles must comply with standardized technical and safety regulations.', visibility: { show: true } },
    contexts: { enable: false, notes: null, visibility: { show: false } },
    seo: { title: 'Formula 3 Classification | AF Motorsport', description: 'FIA Formula 3 Championship classification and junior development standards', image: null },
    generateSlug: false,
    slug: 'formula-3',
    categories: null,
    tags: null,
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
    updatedAt: '2026-02-21T16:30:00.000Z',
    createdAt: '2026-01-12T11:00:00.000Z'
  },
  {
    id: 6,
    name: 'LMP2',
    type: categoriesIds[122],
    basics: { enable: true, description: 'Second-tier Le Mans Prototype endurance racing class with standardized chassis and engine suppliers for competitive parity.', visibility: { show: true } },
    details: { enable: true, definition: 'FIA-homologated prototype category using approved constructor chassis and mandatory Gibson V8 engines for endurance competition.', criteria: 'Teams must use FIA-approved chassis from designated constructors, install the spec Gibson engine, and comply with aerodynamic and weight regulations specific to the class.', visibility: { show: true } },
    contexts: { enable: false, notes: null, visibility: { show: false } },
    seo: { title: 'LMP2 Classification | AF Motorsport', description: 'Le Mans Prototype 2 technical classification and endurance racing standards', image: null },
    generateSlug: false,
    slug: 'lmp2',
    categories: null,
    tags: null,
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
    updatedAt: '2026-02-20T12:15:00.000Z',
    createdAt: '2026-01-13T12:00:00.000Z'
  },
  {
    id: 7,
    name: 'Hypercar (LMH/LMDh)',
    type: categoriesIds[17],
    basics: { enable: true, description: 'Top-tier prototype class for endurance racing allowing manufacturer-designed or customer-chassis hybrid powertrains.', visibility: { show: true } },
    details: { enable: true, definition: 'Premier endurance prototype category permitting Le Mans Hypercar (LMH) or Le Mans Daytona hybrid (LMDh) specifications with performance balancing through BoP.', criteria: 'Vehicles must meet either LMH or LMDh technical regulations, incorporate hybrid energy recovery systems, and comply with performance balancing parameters set by the FIA and ACO.', visibility: { show: true } },
    contexts: { enable: false, notes: null, visibility: { show: false } },
    seo: { title: 'Hypercar Classification | AF Motorsport', description: 'LMH and LMDh prototype classification for top-tier endurance competition', image: null },
    generateSlug: false,
    slug: 'hypercar-lmh-lmdh',
    categories: null,
    tags: null,
    visibility: { check_publish: true, check_featured: true, check_pinned: false },
    updatedAt: '2026-02-21T17:00:00.000Z',
    createdAt: '2026-01-14T13:00:00.000Z'
  },
  {
    id: 8,
    name: 'TCR Touring Car',
    type: categoriesIds[245],
    basics: { enable: true, description: 'International touring car racing specification for production-based vehicles competing under unified technical regulations.', visibility: { show: true } },
    details: { enable: true, definition: 'FIA-sanctioned touring car category using production-based vehicles with standardized turbocharged engines, sequential gearboxes, and Balance of Performance adjustments.', criteria: 'Vehicles must be derived from road-going models with minimum production volumes, meet TCR technical regulations, and compete under BoP parameters to ensure competitive equity.', visibility: { show: true } },
    contexts: { enable: false, notes: null, visibility: { show: false } },
    seo: { title: 'TCR Classification | AF Motorsport', description: 'TCR touring car technical classification and global racing standards', image: null },
    generateSlug: false,
    slug: 'tcr-touring-car',
    categories: null,
    tags: null,
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
    updatedAt: '2026-02-20T13:00:00.000Z',
    createdAt: '2026-01-15T14:00:00.000Z'
  },
  {
    id: 9,
    name: 'Rally1 Hybrid',
    type: categoriesIds[243],
    basics: { enable: true, description: 'Top-tier World Rally Championship specification featuring hybrid-powered rally cars competing on mixed-surface stages.', visibility: { show: true } },
    details: { enable: true, definition: 'FIA World Rally Championship premier class using 1.6L turbocharged engines with integrated hybrid units, standardized aerodynamics, and reinforced safety cells.', criteria: 'Vehicles must conform to Rally1 technical regulations, incorporate the spec hybrid system, pass FIA safety certification, and compete under WRC sporting regulations.', visibility: { show: true } },
    contexts: { enable: false, notes: null, visibility: { show: false } },
    seo: { title: 'Rally1 Classification | AF Motorsport', description: 'WRC Rally1 hybrid technical classification and rally racing standards', image: null },
    generateSlug: false,
    slug: 'rally1-hybrid',
    categories: null,
    tags: null,
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
    updatedAt: '2026-02-20T13:30:00.000Z',
    createdAt: '2026-01-16T15:00:00.000Z'
  },
  {
    id: 10,
    name: 'Rally2',
    type: categoriesIds[52],
    basics: { enable: true, description: 'Second-tier World Rally Championship specification for production-based rally cars competing in WRC2 and regional championships.', visibility: { show: true } },
    details: { enable: true, definition: 'FIA-homologated rally category using production-based vehicles with 1.6L turbo engines, standardized suspension geometry, and cost-control regulations.', criteria: 'Vehicles must be derived from road-going models with minimum production numbers, meet Rally2 technical specifications, and comply with WRC2 sporting regulations.', visibility: { show: true } },
    contexts: { enable: false, notes: null, visibility: { show: false } },
    seo: { title: 'Rally2 Classification | AF Motorsport', description: 'WRC Rally2 technical classification and regional rally standards', image: null },
    generateSlug: false,
    slug: 'rally2',
    categories: null,
    tags: null,
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
    updatedAt: '2026-02-20T14:00:00.000Z',
    createdAt: '2026-01-17T16:00:00.000Z'
  },
  {
    id: 11,
    name: 'FIA Grade 1 Circuit',
    type: categoriesIds[215],
    basics: { enable: true, description: 'Highest-level circuit certification required for hosting Formula 1 World Championship events.', visibility: { show: true } },
    details: { enable: true, definition: 'Circuit meeting comprehensive FIA Grade 1 standards for safety infrastructure, medical facilities, runoff areas, and operational capabilities.', criteria: 'Circuits must provide specified runoff areas, barrier systems, medical center specifications, helicopter access, and pass annual FIA inspection for championship eligibility.', visibility: { show: true } },
    contexts: { enable: false, notes: null, visibility: { show: false } },
    seo: { title: 'Grade 1 Circuit Classification | AF Motorsport', description: 'FIA Grade 1 circuit certification standards for premier motorsport venues', image: null },
    generateSlug: false,
    slug: 'fia-grade-1-circuit',
    categories: null,
    tags: null,
    visibility: { check_publish: true, check_featured: true, check_pinned: true },
    updatedAt: '2026-02-22T10:00:00.000Z',
    createdAt: '2026-01-18T17:00:00.000Z'
  },
  {
    id: 12,
    name: 'FIA Grade 2 Circuit',
    type: categoriesIds[232],
    basics: { enable: true, description: 'Circuit certification for hosting international Formula 2, Formula 3, and other FIA-sanctioned single-seater events.', visibility: { show: true } },
    details: { enable: true, definition: 'Circuit meeting FIA Grade 2 standards for safety infrastructure, medical facilities, and spectator protection for international racing.', criteria: 'Circuits must provide adequate runoff areas, barrier specifications, medical center capabilities, and pass FIA inspection for international event hosting.', visibility: { show: true } },
    contexts: { enable: false, notes: null, visibility: { show: false } },
    seo: { title: 'Grade 2 Circuit Classification | AF Motorsport', description: 'FIA Grade 2 circuit certification standards for international racing venues', image: null },
    generateSlug: false,
    slug: 'fia-grade-2-circuit',
    categories: null,
    tags: null,
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
    updatedAt: '2026-02-21T17:30:00.000Z',
    createdAt: '2026-01-19T18:00:00.000Z'
  },
  {
    id: 13,
    name: 'FIA Grade 3 Circuit',
    type: categoriesIds[107],
    basics: { enable: true, description: 'Circuit certification for national championships, regional events, and testing activities under FIA oversight.', visibility: { show: true } },
    details: { enable: true, definition: 'Circuit meeting FIA Grade 3 standards for basic safety infrastructure, medical facilities, and spectator protection for national-level competition.', criteria: 'Circuits must provide minimum safety barriers, medical response capabilities, and pass national ASN inspection for domestic event hosting.', visibility: { show: true } },
    contexts: { enable: false, notes: null, visibility: { show: false } },
    seo: { title: 'Grade 3 Circuit Classification | AF Motorsport', description: 'FIA Grade 3 circuit certification standards for national racing venues', image: null },
    generateSlug: false,
    slug: 'fia-grade-3-circuit',
    categories: null,
    tags: null,
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
    updatedAt: '2026-02-21T18:00:00.000Z',
    createdAt: '2026-01-20T19:00:00.000Z'
  },
  {
    id: 14,
    name: 'FIA Safety Standard: Crash Testing',
    type: categoriesIds[126],
    basics: { enable: true, description: 'Mandatory crashworthiness testing protocols for racing vehicle survival cells and impact structures.', visibility: { show: true } },
    details: { enable: true, definition: 'Standardized impact testing procedures for frontal, side, rear, and roll structures to verify energy absorption and structural integrity under extreme loads.', criteria: 'Components must pass static and dynamic load tests at specified forces, demonstrate minimal deformation, and maintain survival cell integrity per FIA Technical Regulations.', visibility: { show: true } },
    contexts: { enable: false, notes: null, visibility: { show: false } },
    seo: { title: 'Crash Testing Safety Classification | AF Motorsport', description: 'FIA crash testing safety standards for racing vehicle certification', image: null },
    generateSlug: false,
    slug: 'fia-safety-crash-testing',
    categories: null,
    tags: null,
    visibility: { check_publish: true, check_featured: true, check_pinned: true },
    updatedAt: '2026-02-22T10:30:00.000Z',
    createdAt: '2026-01-21T20:00:00.000Z'
  },
  {
    id: 15,
    name: 'FIA Safety Standard: Fire Suppression',
    type: categoriesIds[41],
    basics: { enable: true, description: 'Mandatory fire suppression system specifications for cockpit and engine compartment protection in racing vehicles.', visibility: { show: true } },
    details: { enable: true, definition: 'Standardized fire extinguishing system requirements including agent capacity, nozzle placement, activation mechanisms, and system certification for racing applications.', criteria: 'Systems must use FIA-approved agents, provide specified discharge coverage, incorporate dual activation methods, and pass pressure and flow testing per FIA Technical List 6.', visibility: { show: true } },
    contexts: { enable: false, notes: null, visibility: { show: false } },
    seo: { title: 'Fire Suppression Safety Classification | AF Motorsport', description: 'FIA fire suppression safety standards for racing vehicle certification', image: null },
    generateSlug: false,
    slug: 'fia-safety-fire-suppression',
    categories: null,
    tags: null,
    visibility: { check_publish: true, check_featured: true, check_pinned: true },
    updatedAt: '2026-02-22T11:00:00.000Z',
    createdAt: '2026-01-22T21:00:00.000Z'
  },
  {
    id: 16,
    name: 'FIA Safety Standard: Fuel Cell',
    type: categoriesIds[9],
    basics: { enable: true, description: 'Mandatory fuel cell construction and safety specifications for puncture resistance and fire prevention in racing vehicles.', visibility: { show: true } },
    details: { enable: true, definition: 'Standardized fuel tank construction requirements including bladder materials, foam filling, crash testing protocols, and certification procedures for racing applications.', criteria: 'Cells must use FIA-approved bladder materials, incorporate anti-explosion foam, pass puncture and impact testing per FIA Technical List 2, and maintain integrity under extreme conditions.', visibility: { show: true } },
    contexts: { enable: false, notes: null, visibility: { show: false } },
    seo: { title: 'Fuel Cell Safety Classification | AF Motorsport', description: 'FIA fuel cell safety standards for racing vehicle certification', image: null },
    generateSlug: false,
    slug: 'fia-safety-fuel-cell',
    categories: null,
    tags: null,
    visibility: { check_publish: true, check_featured: true, check_pinned: true },
    updatedAt: '2026-02-22T11:30:00.000Z',
    createdAt: '2026-01-23T22:00:00.000Z'
  },
  {
    id: 17,
    name: 'FIA Technical Directive: Aerodynamics',
    type: categoriesIds[105],
    basics: { enable: true, description: 'Technical regulations governing aerodynamic device design, dimensions, and usage in championship competition.', visibility: { show: true } },
    details: { enable: true, definition: 'Standardized rules for wing dimensions, movable aerodynamic devices, airflow management systems, and flex testing requirements for competitive vehicles.', criteria: 'Components must conform to dimensional tolerances, pass deflection testing, comply with DRS activation zones, and meet flexibility regulations per championship technical directives.', visibility: { show: true } },
    contexts: { enable: false, notes: null, visibility: { show: false } },
    seo: { title: 'Aerodynamics Technical Directive | AF Motorsport', description: 'FIA aerodynamic technical regulations for racing vehicle certification', image: null },
    generateSlug: false,
    slug: 'fia-technical-aerodynamics',
    categories: null,
    tags: null,
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
    updatedAt: '2026-02-21T18:30:00.000Z',
    createdAt: '2026-01-24T23:00:00.000Z'
  },
  {
    id: 18,
    name: 'FIA Technical Directive: Powertrain',
    type: categoriesIds[118],
    basics: { enable: true, description: 'Technical regulations governing engine specifications, hybrid systems, and power unit integration in championship competition.', visibility: { show: true } },
    details: { enable: true, definition: 'Standardized rules for engine displacement, hybrid energy recovery, fuel flow limits, deployment windows, and component homologation requirements.', criteria: 'Power units must conform to displacement limits, incorporate spec hybrid components, comply with fuel flow regulations, and pass dyno verification per championship technical directives.', visibility: { show: true } },
    contexts: { enable: false, notes: null, visibility: { show: false } },
    seo: { title: 'Powertrain Technical Directive | AF Motorsport', description: 'FIA powertrain technical regulations for racing vehicle certification', image: null },
    generateSlug: false,
    slug: 'fia-technical-powertrain',
    categories: null,
    tags: null,
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
    updatedAt: '2026-02-21T19:00:00.000Z',
    createdAt: '2026-01-25T00:00:00.000Z'
  },
  {
    id: 19,
    name: 'Balance of Performance: Weight',
    type: categoriesIds[27],
    basics: { enable: true, description: 'Weight adjustment parameters for competitive parity between different vehicle designs in multi-manufacturer racing series.', visibility: { show: true } },
    details: { enable: true, definition: 'Standardized weight penalties or allowances applied to vehicles to balance performance differentials based on lap time analysis and competitive equity assessment.', criteria: 'Adjustments must be based on verified performance data, applied uniformly within class, and reviewed periodically per series sporting regulations.', visibility: { show: true } },
    contexts: { enable: false, notes: null, visibility: { show: false } },
    seo: { title: 'BoP Weight Classification | AF Motorsport', description: 'Balance of Performance weight adjustment standards for competitive racing', image: null },
    generateSlug: false,
    slug: 'bop-weight',
    categories: null,
    tags: null,
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
    updatedAt: '2026-02-20T14:30:00.000Z',
    createdAt: '2026-01-26T01:00:00.000Z'
  },
  {
    id: 20,
    name: 'Balance of Performance: Power',
    type: categoriesIds[166],
    basics: { enable: true, description: 'Power output adjustment parameters for competitive parity between different vehicle designs in multi-manufacturer racing series.', visibility: { show: true } },
    details: { enable: true, definition: 'Standardized power restrictions or allowances applied via engine mapping, turbo boost limits, or hybrid deployment windows to balance performance differentials.', criteria: 'Adjustments must be based on dyno testing and race performance data, applied uniformly within class, and reviewed periodically per series sporting regulations.', visibility: { show: true } },
    contexts: { enable: false, notes: null, visibility: { show: false } },
    seo: { title: 'BoP Power Classification | AF Motorsport', description: 'Balance of Performance power adjustment standards for competitive racing', image: null },
    generateSlug: false,
    slug: 'bop-power',
    categories: null,
    tags: null,
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
    updatedAt: '2026-02-20T15:00:00.000Z',
    createdAt: '2026-01-27T02:00:00.000Z'
  },
  {
    id: 21,
    name: 'Balance of Performance: Aerodynamics',
    type: categoriesIds[84],
    basics: { enable: true, description: 'Aerodynamic adjustment parameters for competitive parity between different vehicle designs in multi-manufacturer racing series.', visibility: { show: true } },
    details: { enable: true, definition: 'Standardized aerodynamic restrictions or allowances applied via wing dimensions, diffuser specifications, or underbody regulations to balance performance differentials.', criteria: 'Adjustments must be based on wind tunnel data and on-track performance analysis, applied uniformly within class, and reviewed periodically per series sporting regulations.', visibility: { show: true } },
    contexts: { enable: false, notes: null, visibility: { show: false } },
    seo: { title: 'BoP Aerodynamics Classification | AF Motorsport', description: 'Balance of Performance aerodynamic adjustment standards for competitive racing', image: null },
    generateSlug: false,
    slug: 'bop-aerodynamics',
    categories: null,
    tags: null,
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
    updatedAt: '2026-02-20T15:30:00.000Z',
    createdAt: '2026-01-28T03:00:00.000Z'
  },
  {
    id: 22,
    name: 'Pro Class',
    type: categoriesIds[48],
    basics: { enable: true, description: 'Professional driver classification for elite-level competitors with championship experience and FIA licensing.', visibility: { show: true } },
    details: { enable: true, definition: 'Driver classification for fully professional competitors holding FIA Platinum, Gold, or Silver licenses with prior championship results.', criteria: 'Drivers must hold appropriate FIA license grade, demonstrate prior professional racing results, and meet age and experience requirements per series regulations.', visibility: { show: true } },
    contexts: { enable: false, notes: null, visibility: { show: false } },
    seo: { title: 'Pro Class Driver Classification | AF Motorsport', description: 'Professional driver classification standards for elite motorsport competition', image: null },
    generateSlug: false,
    slug: 'pro-class',
    categories: null,
    tags: null,
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
    updatedAt: '2026-02-21T19:30:00.000Z',
    createdAt: '2026-01-29T04:00:00.000Z'
  },
  {
    id: 23,
    name: 'Pro-Am Class',
    type: categoriesIds[109],
    basics: { enable: true, description: 'Mixed professional and amateur driver classification for balanced team competition in endurance and GT racing.', visibility: { show: true } },
    details: { enable: true, definition: 'Driver pairing classification requiring specific ratios of professional and amateur drivers per entry to ensure balanced team competition.', criteria: 'Entries must include mandated Pro/Am driver combinations, individual drivers must hold appropriate license grades, and teams must comply with performance balancing measures.', visibility: { show: true } },
    contexts: { enable: false, notes: null, visibility: { show: false } },
    seo: { title: 'Pro-Am Class Driver Classification | AF Motorsport', description: 'Pro-Am driver classification standards for balanced motorsport competition', image: null },
    generateSlug: false,
    slug: 'pro-am-class',
    categories: null,
    tags: null,
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
    updatedAt: '2026-02-21T20:00:00.000Z',
    createdAt: '2026-01-30T05:00:00.000Z'
  },
  {
    id: 24,
    name: 'Am Class',
    type: categoriesIds[110],
    basics: { enable: true, description: 'Amateur driver classification for gentleman racers with limited professional racing experience.', visibility: { show: true } },
    details: { enable: true, definition: 'Driver classification for amateur competitors holding FIA Bronze or Silver licenses with restricted professional racing history.', criteria: 'Drivers must hold appropriate amateur license grade, demonstrate limited professional racing history, and meet age requirements per series regulations.', visibility: { show: true } },
    contexts: { enable: false, notes: null, visibility: { show: false } },
    seo: { title: 'Am Class Driver Classification | AF Motorsport', description: 'Amateur driver classification standards for gentleman racer competition', image: null },
    generateSlug: false,
    slug: 'am-class',
    categories: null,
    tags: null,
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
    updatedAt: '2026-02-21T20:30:00.000Z',
    createdAt: '2026-01-31T06:00:00.000Z'
  },
  {
    id: 25,
    name: 'Rookie Class',
    type: categoriesIds[147],
    basics: { enable: true, description: 'First-year competitor classification for emerging talent in their debut championship season.', visibility: { show: true } },
    details: { enable: true, definition: 'Driver classification for competitors in their first season of a specific championship category with no prior points-earning experience.', criteria: 'Drivers must have no prior championship points in category, meet age limits, and participate in designated development programs where applicable.', visibility: { show: true } },
    contexts: { enable: false, notes: null, visibility: { show: false } },
    seo: { title: 'Rookie Class Driver Classification | AF Motorsport', description: 'Rookie driver classification standards for emerging motorsport talent', image: null },
    generateSlug: false,
    slug: 'rookie-class',
    categories: null,
    tags: null,
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
    updatedAt: '2026-02-21T21:00:00.000Z',
    createdAt: '2026-02-01T07:00:00.000Z'
  },
  {
    id: 26,
    name: 'Electric Powertrain',
    type: categoriesIds[211],
    basics: { enable: true, description: 'Fully electric propulsion system classification for zero-emission racing vehicles.', visibility: { show: true } },
    details: { enable: true, definition: 'Vehicles powered exclusively by electric motors and battery energy storage systems with no internal combustion components.', criteria: 'Vehicles must use FIA-approved battery systems, comply with power and energy limits, meet safety standards for high-voltage systems, and pass homologation per electric racing regulations.', visibility: { show: true } },
    contexts: { enable: false, notes: null, visibility: { show: false } },
    seo: { title: 'Electric Powertrain Classification | AF Motorsport', description: 'Electric powertrain technical classification for zero-emission racing', image: null },
    generateSlug: false,
    slug: 'electric-powertrain',
    categories: null,
    tags: null,
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
    updatedAt: '2026-02-21T21:30:00.000Z',
    createdAt: '2026-02-02T08:00:00.000Z'
  },
  {
    id: 27,
    name: 'Hybrid Powertrain',
    type: categoriesIds[34],
    basics: { enable: true, description: 'Combined internal combustion and electric propulsion system classification for advanced racing vehicles.', visibility: { show: true } },
    details: { enable: true, definition: 'Vehicles utilizing both internal combustion engines and electric motor systems with energy recovery and deployment capabilities.', criteria: 'Power units must conform to hybrid system specifications, comply with energy recovery and deployment limits, meet safety standards for high-voltage components, and pass homologation per hybrid racing regulations.', visibility: { show: true } },
    contexts: { enable: false, notes: null, visibility: { show: false } },
    seo: { title: 'Hybrid Powertrain Classification | AF Motorsport', description: 'Hybrid powertrain technical classification for advanced racing propulsion', image: null },
    generateSlug: false,
    slug: 'hybrid-powertrain',
    categories: null,
    tags: null,
    visibility: { check_publish: true, check_featured: true, check_pinned: false },
    updatedAt: '2026-02-21T22:00:00.000Z',
    createdAt: '2026-02-03T09:00:00.000Z'
  }
] as const
