export const dictionary = {
  host: { en: 'Report', es: 'Informe', pt: 'Relatório' },
  hostPlural: { en: 'Reports', es: 'Informes', pt: 'Relatórios' },
  essential: {
    name: {
      label: { en: 'Name', es: 'Nombre', pt: 'Nome' },
      placeholder: { en: 'e.g. Q1 2024 Performance Report', es: 'e.g. Informe Rendimiento T1 2024', pt: 'e.g. Relatório de Desempenho T1 2024' },
    },
    alias: {
      label: { en: 'Alias', es: 'Alias', pt: 'Alias' },
      placeholder: { en: 'e.g. PERF_Q1_24', es: 'e.g. REND_T1_24', pt: 'e.g. DESE_T1_24' },
    },
  },
  tabs: {
    basics: {
      tagline: {
        label: { en: 'Tagline', es: 'Lema', pt: 'Lema' },
        placeholder: { en: 'e.g. Key Insights', es: 'e.g. Ideas Clave', pt: 'e.g. Principais Insights' },
      },
      description: {
        label: { en: 'Description', es: 'Descripción', pt: 'Descrição' },
        placeholder: { en: 'Enter description', es: 'Ingrese descripción', pt: 'Insira a descrição' },
      },
      executive_summary: {
        label: { en: 'Executive Summary', es: 'Resumen Ejecutivo', pt: 'Resumo Executivo' },
        placeholder: { en: 'High-level summary', es: 'Resumen de alto nivel', pt: 'Resumo de alto nível' },
      },
    },
    details: {
      type: { label: { en: 'Type', es: 'Tipo', pt: 'Tipo' } },
      format: { label: { en: 'Format', es: 'Formato', pt: 'Formato' } },
      status: { label: { en: 'Status', es: 'Estado', pt: 'Status' } },
      generated_by: { label: { en: 'Generated By', es: 'Generado Por', pt: 'Gerado Por' } },
      generated_on: { label: { en: 'Generated On', es: 'Generado El', pt: 'Gerado Em' } },
      period_start: { label: { en: 'Period Start', es: 'Inicio del Periodo', pt: 'Início do Período' } },
      period_end: { label: { en: 'Period End', es: 'Fin del Periodo', pt: 'Fim do Período' } },
      scope: { label: { en: 'Scope', es: 'Alcance', pt: 'Escopo' } },
      approved_by: { label: { en: 'Approved By', es: 'Aprobado Por', pt: 'Aprovado Por' } },
      approved_on: { label: { en: 'Approved On', es: 'Aprobado El', pt: 'Aprovado Em' } },
      notes: { label: { en: 'Notes', es: 'Notas', pt: 'Notas' } },
    },
    traits: {
      // Labels handled in groupFactory directly for arrays
    },
    assets: {
      attachments: { label: { en: 'Attachments', es: 'Adjuntos', pt: 'Anexos' } },
      thumbnail: { label: { en: 'Thumbnail', es: 'Miniatura', pt: 'Miniatura' } },
      cover: { label: { en: 'Cover', es: 'Portada', pt: 'Capa' } },
      documents: { label: { en: 'Documents', es: 'Documentos', pt: 'Documentos' } },
    },
  },
} as const
