// FILE: src/collections/Operations/Meetup/seeders/preload.ts
export const PRELOAD_MEETUP = (categoriesIds: number[], narrativesIds: number[]) => [
  {
    name: 'Pre-Race Technical Briefing',
    toggle: 'advanced',
    type: categoriesIds[185],
    basics: { enable: true, description: 'Mandatory technical briefing for drivers and engineers before competitive session.', date: '2026-03-15', location: 1, visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[14], features: [], visibility: { show: true } },
    traits: { enable: true, specifications: [], format: 'InPerson', access: 'Private', visibility: { show: true } },
    assets: { enable: true, primary: null, gallery: null, playlist: null, materials: [], visibility: { show: true } },
    contexts: { enable: true, hosts: [], attendees: [], schedules: [], references: [], notes: [], visibility: { show: true } },
    seo: { title: 'Pre-Race Technical Briefing | AF Motorsport', description: 'Mandatory technical briefing for competitive session preparation' },
    generateSlug: false, slug: 'pre-race-technical-briefing',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Driver Media Availability Session',
    toggle: 'advanced',
    type: categoriesIds[53],
    basics: { enable: true, description: 'Scheduled press conference for driver interviews and media engagement.', date: '2026-03-14', location: 1, visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[1], features: [], visibility: { show: true } },
    traits: { enable: true, specifications: [], format: 'Hybrid', access: 'Public', visibility: { show: true } },
    assets: { enable: true, primary: null, gallery: null, playlist: null, materials: [], visibility: { show: true } },
    contexts: { enable: true, hosts: [], attendees: [], schedules: [], references: [], notes: [], visibility: { show: true } },
    seo: { title: 'Driver Media Session | AF Motorsport', description: 'Scheduled press conference for driver media engagement' },
    generateSlug: false, slug: 'driver-media-availability-session',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Team Strategy Workshop',
    toggle: 'advanced',
    type: categoriesIds[146],
    basics: { enable: true, description: 'Collaborative workshop for race strategy development and scenario planning.', date: '2026-03-13', location: 15, visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[26], features: [], visibility: { show: true } },
    traits: { enable: true, specifications: [], format: 'InPerson', access: 'Private', visibility: { show: true } },
    assets: { enable: true, primary: null, gallery: null, playlist: null, materials: [], visibility: { show: true } },
    contexts: { enable: true, hosts: [], attendees: [], schedules: [], references: [], notes: [], visibility: { show: true } },
    seo: { title: 'Team Strategy Workshop | AF Motorsport', description: 'Collaborative workshop for race strategy development' },
    generateSlug: false, slug: 'team-strategy-workshop',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Fan Meet & Greet Experience',
    toggle: 'advanced',
    type: categoriesIds[123],
    basics: { enable: true, description: 'Interactive fan engagement session with drivers and team members.', date: '2026-03-16', location: 1, visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[20], features: [], visibility: { show: true } },
    traits: { enable: true, specifications: [], format: 'InPerson', access: 'Public', visibility: { show: true } },
    assets: { enable: true, primary: null, gallery: null, playlist: null, materials: [], visibility: { show: true } },
    contexts: { enable: true, hosts: [], attendees: [], schedules: [], references: [], notes: [], visibility: { show: true } },
    seo: { title: 'Fan Meet & Greet | AF Motorsport', description: 'Interactive fan engagement session with racing personalities' },
    generateSlug: false, slug: 'fan-meet-greet-experience',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Technical Innovation Symposium',
    toggle: 'advanced',
    type: categoriesIds[38],
    basics: { enable: true, description: 'Knowledge-sharing forum for engineering teams to discuss technical advancements.', date: '2026-04-10', location: 15, visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[34], features: [], visibility: { show: true } },
    traits: { enable: true, specifications: [], format: 'Hybrid', access: 'InviteOnly', visibility: { show: true } },
    assets: { enable: true, primary: null, gallery: null, playlist: null, materials: [], visibility: { show: true } },
    contexts: { enable: true, hosts: [], attendees: [], schedules: [], references: [], notes: [], visibility: { show: true } },
    seo: { title: 'Technical Innovation Symposium | AF Motorsport', description: 'Engineering knowledge-sharing forum for technical advancements' },
    generateSlug: false, slug: 'technical-innovation-symposium',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Safety Protocol Training Session',
    toggle: 'advanced',
    type: categoriesIds[122],
    basics: { enable: true, description: 'Mandatory safety training for all personnel before race weekend operations.', date: '2026-03-12', location: 1, visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[13], features: [], visibility: { show: true } },
    traits: { enable: true, specifications: [], format: 'InPerson', access: 'Private', visibility: { show: true } },
    assets: { enable: true, primary: null, gallery: null, playlist: null, materials: [], visibility: { show: true } },
    contexts: { enable: true, hosts: [], attendees: [], schedules: [], references: [], notes: [], visibility: { show: true } },
    seo: { title: 'Safety Protocol Training | AF Motorsport', description: 'Mandatory safety training for race weekend personnel' },
    generateSlug: false, slug: 'safety-protocol-training-session',
    visibility: { check_publish: true, check_featured: true, check_pinned: true }
  },
  {
    name: 'Sponsor Partnership Review',
    toggle: 'advanced',
    type: categoriesIds[17],
    basics: { enable: true, description: 'Strategic review meeting with commercial partners to assess activation performance.', date: '2026-05-20', location: 17, visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[19], features: [], visibility: { show: true } },
    traits: { enable: true, specifications: [], format: 'Hybrid', access: 'Exclusive', visibility: { show: true } },
    assets: { enable: true, primary: null, gallery: null, playlist: null, materials: [], visibility: { show: true } },
    contexts: { enable: true, hosts: [], attendees: [], schedules: [], references: [], notes: [], visibility: { show: true } },
    seo: { title: 'Sponsor Partnership Review | AF Motorsport', description: 'Strategic review meeting with commercial activation partners' },
    generateSlug: false, slug: 'sponsor-partnership-review',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Driver Fitness Assessment Clinic',
    toggle: 'advanced',
    type: categoriesIds[245],
    basics: { enable: true, description: 'Comprehensive physical and mental fitness evaluation for competing drivers.', date: '2026-03-10', location: 18, visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[48], features: [], visibility: { show: true } },
    traits: { enable: true, specifications: [], format: 'InPerson', access: 'Private', visibility: { show: true } },
    assets: { enable: true, primary: null, gallery: null, playlist: null, materials: [], visibility: { show: true } },
    contexts: { enable: true, hosts: [], attendees: [], schedules: [], references: [], notes: [], visibility: { show: true } },
    seo: { title: 'Driver Fitness Assessment | AF Motorsport', description: 'Comprehensive physical and mental fitness evaluation for drivers' },
    generateSlug: false, slug: 'driver-fitness-assessment-clinic',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Regulatory Compliance Briefing',
    toggle: 'advanced',
    type: categoriesIds[243],
    basics: { enable: true, description: 'Mandatory briefing on updated sporting and technical regulations for competition.', date: '2026-02-28', location: 11, visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[56], features: [], visibility: { show: true } },
    traits: { enable: true, specifications: [], format: 'Virtual', access: 'Private', visibility: { show: true } },
    assets: { enable: true, primary: null, gallery: null, playlist: null, materials: [], visibility: { show: true } },
    contexts: { enable: true, hosts: [], attendees: [], schedules: [], references: [], notes: [], visibility: { show: true } },
    seo: { title: 'Regulatory Compliance Briefing | AF Motorsport', description: 'Mandatory briefing on updated competition regulations' },
    generateSlug: false, slug: 'regulatory-compliance-briefing',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Post-Race Debrief Session',
    toggle: 'advanced',
    type: categoriesIds[52],
    basics: { enable: true, description: 'Structured debrief for performance analysis and lessons learned after competitive session.', date: '2026-03-17', location: 1, visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[23], features: [], visibility: { show: true } },
    traits: { enable: true, specifications: [], format: 'InPerson', access: 'Private', visibility: { show: true } },
    assets: { enable: true, primary: null, gallery: null, playlist: null, materials: [], visibility: { show: true } },
    contexts: { enable: true, hosts: [], attendees: [], schedules: [], references: [], notes: [], visibility: { show: true } },
    seo: { title: 'Post-Race Debrief | AF Motorsport', description: 'Structured performance analysis session after competitive events' },
    generateSlug: false, slug: 'post-race-debrief-session',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Youth Academy Talent Showcase',
    toggle: 'advanced',
    type: categoriesIds[215],
    basics: { enable: true, description: 'Showcase event for emerging driver talent to demonstrate skills to team evaluators.', date: '2026-06-15', location: 1, visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[12], features: [], visibility: { show: true } },
    traits: { enable: true, specifications: [], format: 'InPerson', access: 'InviteOnly', visibility: { show: true } },
    assets: { enable: true, primary: null, gallery: null, playlist: null, materials: [], visibility: { show: true } },
    contexts: { enable: true, hosts: [], attendees: [], schedules: [], references: [], notes: [], visibility: { show: true } },
    seo: { title: 'Youth Academy Showcase | AF Motorsport', description: 'Talent showcase event for emerging driver evaluation' },
    generateSlug: false, slug: 'youth-academy-talent-showcase',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Simulator Development Workshop',
    toggle: 'advanced',
    type: categoriesIds[232],
    basics: { enable: true, description: 'Collaborative session for refining simulation platforms and driver training tools.', date: '2026-04-22', location: 15, visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[7], features: [], visibility: { show: true } },
    traits: { enable: true, specifications: [], format: 'InPerson', access: 'Private', visibility: { show: true } },
    assets: { enable: true, primary: null, gallery: null, playlist: null, materials: [], visibility: { show: true } },
    contexts: { enable: true, hosts: [], attendees: [], schedules: [], references: [], notes: [], visibility: { show: true } },
    seo: { title: 'Simulator Development Workshop | AF Motorsport', description: 'Collaborative session for simulation platform refinement' },
    generateSlug: false, slug: 'simulator-development-workshop',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Sustainability Initiative Forum',
    toggle: 'advanced',
    type: categoriesIds[107],
    basics: { enable: true, description: 'Cross-organizational forum for advancing environmental responsibility in motorsport.', date: '2026-07-10', location: 11, visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[9], features: [], visibility: { show: true } },
    traits: { enable: true, specifications: [], format: 'Hybrid', access: 'Public', visibility: { show: true } },
    assets: { enable: true, primary: null, gallery: null, playlist: null, materials: [], visibility: { show: true } },
    contexts: { enable: true, hosts: [], attendees: [], schedules: [], references: [], notes: [], visibility: { show: true } },
    seo: { title: 'Sustainability Forum | AF Motorsport', description: 'Cross-organizational forum for environmental responsibility advancement' },
    generateSlug: false, slug: 'sustainability-initiative-forum',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Data Analytics Strategy Session',
    toggle: 'advanced',
    type: categoriesIds[126],
    basics: { enable: true, description: 'Strategic planning session for performance data utilization and insight generation.', date: '2026-05-05', location: 15, visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[6], features: [], visibility: { show: true } },
    traits: { enable: true, specifications: [], format: 'InPerson', access: 'Private', visibility: { show: true } },
    assets: { enable: true, primary: null, gallery: null, playlist: null, materials: [], visibility: { show: true } },
    contexts: { enable: true, hosts: [], attendees: [], schedules: [], references: [], notes: [], visibility: { show: true } },
    seo: { title: 'Data Analytics Strategy | AF Motorsport', description: 'Strategic planning for performance data utilization and insight generation' },
    generateSlug: false, slug: 'data-analytics-strategy-session',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Media Production Planning Meeting',
    toggle: 'advanced',
    type: categoriesIds[41],
    basics: { enable: true, description: 'Coordination session for broadcast content planning and distribution strategy.', date: '2026-03-20', location: 18, visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[42], features: [], visibility: { show: true } },
    traits: { enable: true, specifications: [], format: 'Hybrid', access: 'Private', visibility: { show: true } },
    assets: { enable: true, primary: null, gallery: null, playlist: null, materials: [], visibility: { show: true } },
    contexts: { enable: true, hosts: [], attendees: [], schedules: [], references: [], notes: [], visibility: { show: true } },
    seo: { title: 'Media Production Planning | AF Motorsport', description: 'Coordination session for broadcast content and distribution strategy' },
    generateSlug: false, slug: 'media-production-planning-meeting',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Logistics Coordination Briefing',
    toggle: 'advanced',
    type: categoriesIds[9],
    basics: { enable: true, description: 'Operational briefing for global freight planning and race weekend logistics.', date: '2026-03-08', location: 19, visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[22], features: [], visibility: { show: true } },
    traits: { enable: true, specifications: [], format: 'Virtual', access: 'Private', visibility: { show: true } },
    assets: { enable: true, primary: null, gallery: null, playlist: null, materials: [], visibility: { show: true } },
    contexts: { enable: true, hosts: [], attendees: [], schedules: [], references: [], notes: [], visibility: { show: true } },
    seo: { title: 'Logistics Coordination Briefing | AF Motorsport', description: 'Operational briefing for global freight and race weekend logistics' },
    generateSlug: false, slug: 'logistics-coordination-briefing',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Driver Development Feedback Session',
    toggle: 'advanced',
    type: categoriesIds[105],
    basics: { enable: true, description: 'Structured feedback session for emerging driver performance assessment and growth planning.', date: '2026-04-18', location: 1, visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[3], features: [], visibility: { show: true } },
    traits: { enable: true, specifications: [], format: 'InPerson', access: 'Private', visibility: { show: true } },
    assets: { enable: true, primary: null, gallery: null, playlist: null, materials: [], visibility: { show: true } },
    contexts: { enable: true, hosts: [], attendees: [], schedules: [], references: [], notes: [], visibility: { show: true } },
    seo: { title: 'Driver Development Feedback | AF Motorsport', description: 'Structured feedback session for emerging driver assessment' },
    generateSlug: false, slug: 'driver-development-feedback-session',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Technical Inspection Coordination',
    toggle: 'advanced',
    type: categoriesIds[118],
    basics: { enable: true, description: 'Pre-session coordination for vehicle technical compliance verification and scrutineering.', date: '2026-03-14', location: 1, visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[16], features: [], visibility: { show: true } },
    traits: { enable: true, specifications: [], format: 'InPerson', access: 'Private', visibility: { show: true } },
    assets: { enable: true, primary: null, gallery: null, playlist: null, materials: [], visibility: { show: true } },
    contexts: { enable: true, hosts: [], attendees: [], schedules: [], references: [], notes: [], visibility: { show: true } },
    seo: { title: 'Technical Inspection Coordination | AF Motorsport', description: 'Pre-session coordination for vehicle compliance verification' },
    generateSlug: false, slug: 'technical-inspection-coordination',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Community Engagement Town Hall',
    toggle: 'advanced',
    type: categoriesIds[27],
    basics: { enable: true, description: 'Open forum for community feedback and organizational transparency initiatives.', date: '2026-08-12', location: 1, visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[49], features: [], visibility: { show: true } },
    traits: { enable: true, specifications: [], format: 'Hybrid', access: 'Public', visibility: { show: true } },
    assets: { enable: true, primary: null, gallery: null, playlist: null, materials: [], visibility: { show: true } },
    contexts: { enable: true, hosts: [], attendees: [], schedules: [], references: [], notes: [], visibility: { show: true } },
    seo: { title: 'Community Town Hall | AF Motorsport', description: 'Open forum for community feedback and organizational transparency' },
    generateSlug: false, slug: 'community-engagement-town-hall',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Championship Strategy Summit',
    toggle: 'advanced',
    type: categoriesIds[166],
    basics: { enable: true, description: 'Executive-level strategic planning session for championship campaign optimization.', date: '2026-02-15', location: 15, visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[14], features: [], visibility: { show: true } },
    traits: { enable: true, specifications: [], format: 'InPerson', access: 'Exclusive', visibility: { show: true } },
    assets: { enable: true, primary: null, gallery: null, playlist: null, materials: [], visibility: { show: true } },
    contexts: { enable: true, hosts: [], attendees: [], schedules: [], references: [], notes: [], visibility: { show: true } },
    seo: { title: 'Championship Strategy Summit | AF Motorsport', description: 'Executive strategic planning for championship campaign optimization' },
    generateSlug: false, slug: 'championship-strategy-summit',
    visibility: { check_publish: true, check_featured: true, check_pinned: true }
  }
] as const;
