export const PRELOAD_PLAYLIST = (categoriesIds: number[]) => [
  {
    name: 'Monaco GP 2024: Onboard Lap Compilation - Qualifying Session',
    toggle: 'advanced',
    type: categoriesIds[185],
    details: {
      enable: true,
      visibility: { show: true },
    },
    traits: {
      enable: true,
      quality: '4K',
      format: 'Wide',
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'monaco-gp-2024-onboard-lap-compilation-qualifying',
    visibility: { check_publish: true, check_featured: true, check_pinned: true },
  },
  {
    name: 'Driver Interview Series: Championship Contenders 2024',
    toggle: 'advanced',
    type: categoriesIds[53],
    details: {
      enable: true,
      visibility: { show: true },
    },
    traits: {
      enable: true,
      quality: '4K',
      format: 'Wide',
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'driver-interview-series-championship-contenders-2024',
    visibility: { check_publish: true, check_featured: true, check_pinned: false },
  },
  {
    name: 'Silverstone Overtake Highlights Reel - Race Day',
    toggle: 'advanced',
    type: categoriesIds[146],
    details: {
      enable: true,
      visibility: { show: true },
    },
    traits: {
      enable: true,
      quality: '4K',
      format: 'Wide',
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'silverstone-overtake-highlights-reel-race-day',
    visibility: { check_publish: true, check_featured: true, check_pinned: false },
  },
  {
    name: 'Behind The Scenes: Factory Build Documentary Series',
    toggle: 'advanced',
    type: categoriesIds[123],
    details: {
      enable: true,
      visibility: { show: true },
    },
    traits: {
      enable: true,
      quality: '4K',
      format: 'Wide',
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'behind-scenes-factory-build-documentary-series',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    name: 'Pit Crew Training: Sub-2.5 Second Stop Technique',
    toggle: 'advanced',
    type: categoriesIds[38],
    details: {
      enable: true,
      visibility: { show: true },
    },
    traits: {
      enable: true,
      quality: 'HD',
      format: 'Wide',
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'pit-crew-training-sub-2-5-second-stop-technique',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    name: 'Season Launch Promotional Video Campaign',
    toggle: 'advanced',
    type: categoriesIds[122],
    details: {
      enable: true,
      visibility: { show: true },
    },
    traits: {
      enable: true,
      quality: '4K',
      format: 'Square',
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'season-launch-promotional-video-campaign',
    visibility: { check_publish: true, check_featured: true, check_pinned: false },
  },
  {
    name: 'WEC Le Mans 24h: Night Running Onboard Footage',
    toggle: 'advanced',
    type: categoriesIds[17],
    details: {
      enable: true,
      visibility: { show: true },
    },
    traits: {
      enable: true,
      quality: '4K',
      format: 'Wide',
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'wec-le-mans-24h-night-running-onboard-footage',
    visibility: { check_publish: true, check_featured: true, check_pinned: false },
  },
  {
    name: 'Team Principal Press Conference Archive 2024',
    toggle: 'advanced',
    type: categoriesIds[245],
    details: {
      enable: true,
      visibility: { show: true },
    },
    traits: {
      enable: true,
      quality: 'HD',
      format: 'Wide',
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'team-principal-press-conference-archive-2024',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    name: 'Championship Victory Celebration Highlights',
    toggle: 'advanced',
    type: categoriesIds[243],
    details: {
      enable: true,
      visibility: { show: true },
    },
    traits: {
      enable: true,
      quality: '4K',
      format: 'Wide',
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'championship-victory-celebration-highlights',
    visibility: { check_publish: true, check_featured: true, check_pinned: true },
  },
  {
    name: 'Engineering Deep Dive: Aerodynamic Development Documentary',
    toggle: 'advanced',
    type: categoriesIds[52],
    details: {
      enable: true,
      visibility: { show: true },
    },
    traits: {
      enable: true,
      quality: '4K',
      format: 'Wide',
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'engineering-deep-dive-aerodynamic-development-documentary',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    name: 'Garage Operations: Race Weekend Behind The Scenes',
    toggle: 'advanced',
    type: categoriesIds[215],
    details: {
      enable: true,
      visibility: { show: true },
    },
    traits: {
      enable: true,
      quality: 'HD',
      format: 'Wide',
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'garage-operations-race-weekend-behind-scenes',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    name: 'Sponsor Activation Promotional Video Series',
    toggle: 'advanced',
    type: categoriesIds[232],
    details: {
      enable: true,
      visibility: { show: true },
    },
    traits: {
      enable: true,
      quality: '4K',
      format: 'Vertical',
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'sponsor-activation-promotional-video-series',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    name: 'WRC Rally Stage Onboard: Gravel Surface Mastery',
    toggle: 'advanced',
    type: categoriesIds[107],
    details: {
      enable: true,
      visibility: { show: true },
    },
    traits: {
      enable: true,
      quality: '4K',
      format: 'Wide',
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'wrc-rally-stage-onboard-gravel-surface-mastery',
    visibility: { check_publish: true, check_featured: true, check_pinned: false },
  },
  {
    name: 'Driver Fitness Training Documentary Series',
    toggle: 'advanced',
    type: categoriesIds[126],
    details: {
      enable: true,
      visibility: { show: true },
    },
    traits: {
      enable: true,
      quality: 'HD',
      format: 'Wide',
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'driver-fitness-training-documentary-series',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    name: 'Qualifying Session Grid Walk Highlights',
    toggle: 'advanced',
    type: categoriesIds[41],
    details: {
      enable: true,
      visibility: { show: true },
    },
    traits: {
      enable: true,
      quality: '4K',
      format: 'Wide',
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'qualifying-session-grid-walk-highlights',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    name: 'Historic Monaco GP Archive Footage 1950-1999',
    toggle: 'advanced',
    type: categoriesIds[9],
    details: {
      enable: true,
      visibility: { show: true },
    },
    traits: {
      enable: true,
      quality: 'SD',
      format: 'Wide',
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'historic-monaco-gp-archive-footage-1950-1999',
    visibility: { check_publish: true, check_featured: true, check_pinned: false },
  },
  {
    name: 'Fan Engagement Social Media Video Compilation',
    toggle: 'advanced',
    type: categoriesIds[105],
    details: {
      enable: true,
      visibility: { show: true },
    },
    traits: {
      enable: true,
      quality: 'HD',
      format: 'Vertical',
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'fan-engagement-social-media-video-compilation',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    name: 'Race Start Launch Control Action Sequence',
    toggle: 'advanced',
    type: categoriesIds[118],
    details: {
      enable: true,
      visibility: { show: true },
    },
    traits: {
      enable: true,
      quality: '4K',
      format: 'Wide',
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'race-start-launch-control-action-sequence',
    visibility: { check_publish: true, check_featured: true, check_pinned: false },
  },
  {
    name: 'Technical Briefing: Hybrid Powertrain Strategy Session',
    toggle: 'advanced',
    type: categoriesIds[27],
    details: {
      enable: true,
      visibility: { show: true },
    },
    traits: {
      enable: true,
      quality: 'HD',
      format: 'Wide',
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'technical-briefing-hybrid-powertrain-strategy-session',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    name: 'Podium Ceremony Celebration Video Archive',
    toggle: 'advanced',
    type: categoriesIds[166],
    details: {
      enable: true,
      visibility: { show: true },
    },
    traits: {
      enable: true,
      quality: '4K',
      format: 'Wide',
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'podium-ceremony-celebration-video-archive',
    visibility: { check_publish: true, check_featured: true, check_pinned: false },
  },
] as const
