// FILE: src/collections/Competition/Series/seeders/preload.ts
export const PRELOAD_SERIES = (categoriesIds: number[]) => [
  {
    name: 'Formula 1 World Championship Series',
    alias: 'F1',
    toggle: 'advanced',
    type: categoriesIds[185],
    basics: { enable: true, description: 'The pinnacle of single-seater open-wheel motorsport competition.', identifiers: { code: 'F1-WC', abbreviation: 'F1' }, tagline: 'Where legends are made', status: 'Active', visibility: { show: true } },
    details: { enable: true, visibility: { show: true } },
    traits: { enable: true, heritage: {}, schedule: 1, visibility: { show: true } },
    metrics: { enable: true, counts: { seasons: 75, events: 24, participants: 20 }, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Formula 1 World Championship | AF Motorsport', description: 'The pinnacle of single-seater motorsport competition' },
    generateSlug: false, slug: 'formula-1-world-championship',
    visibility: { check_publish: true, check_featured: true, check_pinned: true }
  },
  {
    name: 'World Endurance Championship Series',
    alias: 'WEC',
    toggle: 'advanced',
    type: categoriesIds[53],
    basics: { enable: true, description: 'Premier global endurance racing championship featuring prototype and GT categories.', identifiers: { code: 'WEC-FIA', abbreviation: 'WEC' }, tagline: 'Endurance redefined', status: 'Active', visibility: { show: true } },
    details: { enable: true, visibility: { show: true } },
    traits: { enable: true, heritage: {}, schedule: 2, visibility: { show: true } },
    metrics: { enable: true, counts: { seasons: 12, events: 8, participants: 38 }, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'World Endurance Championship | AF Motorsport', description: 'Global endurance racing championship with prototype and GT competition' },
    generateSlug: false, slug: 'world-endurance-championship',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'IndyCar Series Championship',
    alias: 'INDYCAR',
    toggle: 'advanced',
    type: categoriesIds[146],
    basics: { enable: true, description: 'Premier North American open-wheel racing series featuring oval and road courses.', identifiers: { code: 'INDY-S', abbreviation: 'INDY' }, tagline: 'The greatest spectacle in racing', status: 'Active', visibility: { show: true } },
    details: { enable: true, visibility: { show: true } },
    traits: { enable: true, heritage: {}, schedule: 3, visibility: { show: true } },
    metrics: { enable: true, counts: { seasons: 28, events: 17, participants: 26 }, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'IndyCar Series | AF Motorsport', description: 'North American open-wheel racing championship with oval and road competition' },
    generateSlug: false, slug: 'indycar-series-championship',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'GT World Challenge Series',
    alias: 'GTWC',
    toggle: 'advanced',
    type: categoriesIds[123],
    basics: { enable: true, description: 'Global GT3 racing championship with sprint and endurance formats.', identifiers: { code: 'GTWC-S', abbreviation: 'GTWC' }, tagline: 'GT racing at its finest', status: 'Active', visibility: { show: true } },
    details: { enable: true, visibility: { show: true } },
    traits: { enable: true, heritage: {}, schedule: 4, visibility: { show: true } },
    metrics: { enable: true, counts: { seasons: 8, events: 10, participants: 45 }, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'GT World Challenge | AF Motorsport', description: 'Global GT3 racing championship with sprint and endurance competition' },
    generateSlug: false, slug: 'gt-world-challenge-series',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Formula E World Championship Series',
    alias: 'FE',
    toggle: 'advanced',
    type: categoriesIds[38],
    basics: { enable: true, description: 'All-electric single-seater racing championship on urban street circuits.', identifiers: { code: 'FE-WC', abbreviation: 'FE' }, tagline: 'Electric racing reimagined', status: 'Active', visibility: { show: true } },
    details: { enable: true, visibility: { show: true } },
    traits: { enable: true, heritage: {}, schedule: 5, visibility: { show: true } },
    metrics: { enable: true, counts: { seasons: 10, events: 16, participants: 22 }, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Formula E World Championship | AF Motorsport', description: 'All-electric racing championship on urban street circuits worldwide' },
    generateSlug: false, slug: 'formula-e-world-championship',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'World Rally Championship Series',
    alias: 'WRC',
    toggle: 'advanced',
    type: categoriesIds[122],
    basics: { enable: true, description: 'Premier global rally championship featuring diverse terrain and conditions.', identifiers: { code: 'WRC-FIA', abbreviation: 'WRC' }, tagline: 'Rally racing at the limit', status: 'Active', visibility: { show: true } },
    details: { enable: true, visibility: { show: true } },
    traits: { enable: true, heritage: {}, schedule: 6, visibility: { show: true } },
    metrics: { enable: true, counts: { seasons: 52, events: 13, participants: 18 }, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'World Rally Championship | AF Motorsport', description: 'Global rally championship featuring diverse terrain and conditions' },
    generateSlug: false, slug: 'world-rally-championship-series',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'NASCAR Cup Series Championship',
    alias: 'NASCAR',
    toggle: 'advanced',
    type: categoriesIds[17],
    basics: { enable: true, description: 'Premier American stock car racing championship with playoff format.', identifiers: { code: 'NCS-C', abbreviation: 'NASCAR' }, tagline: 'Stock car racing excellence', status: 'Active', visibility: { show: true } },
    details: { enable: true, visibility: { show: true } },
    traits: { enable: true, heritage: {}, schedule: 7, visibility: { show: true } },
    metrics: { enable: true, counts: { seasons: 76, events: 36, participants: 36 }, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'NASCAR Cup Series | AF Motorsport', description: 'Premier American stock car racing championship with playoff format' },
    generateSlug: false, slug: 'nascar-cup-series-championship',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'MotoGP World Championship Series',
    alias: 'MotoGP',
    toggle: 'advanced',
    type: categoriesIds[245],
    basics: { enable: true, description: 'Premier motorcycle road racing championship with sprint and main race format.', identifiers: { code: 'MGP-WC', abbreviation: 'MotoGP' }, tagline: 'Two wheels, one dream', status: 'Active', visibility: { show: true } },
    details: { enable: true, visibility: { show: true } },
    traits: { enable: true, heritage: {}, schedule: 8, visibility: { show: true } },
    metrics: { enable: true, counts: { seasons: 76, events: 20, participants: 24 }, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'MotoGP World Championship | AF Motorsport', description: 'Premier motorcycle road racing championship with sprint format' },
    generateSlug: false, slug: 'motogp-world-championship-series',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Formula 2 Championship Series',
    alias: 'F2',
    toggle: 'advanced',
    type: categoriesIds[243],
    basics: { enable: true, description: 'Primary feeder series for Formula 1 driver development.', identifiers: { code: 'F2-C', abbreviation: 'F2' }, tagline: 'Road to F1', status: 'Active', visibility: { show: true } },
    details: { enable: true, visibility: { show: true } },
    traits: { enable: true, heritage: {}, schedule: 9, visibility: { show: true } },
    metrics: { enable: true, counts: { seasons: 8, events: 14, participants: 22 }, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Formula 2 Championship | AF Motorsport', description: 'Primary feeder series for Formula 1 driver development' },
    generateSlug: false, slug: 'formula-2-championship-series',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Formula 3 Championship Series',
    alias: 'F3',
    toggle: 'advanced',
    type: categoriesIds[52],
    basics: { enable: true, description: 'Entry-level international single-seater championship for emerging talent.', identifiers: { code: 'F3-C', abbreviation: 'F3' }, tagline: 'Future champions start here', status: 'Active', visibility: { show: true } },
    details: { enable: true, visibility: { show: true } },
    traits: { enable: true, heritage: {}, schedule: 10, visibility: { show: true } },
    metrics: { enable: true, counts: { seasons: 6, events: 10, participants: 30 }, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Formula 3 Championship | AF Motorsport', description: 'Entry-level international single-seater championship for emerging talent' },
    generateSlug: false, slug: 'formula-3-championship-series',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'IMSA WeatherTech SportsCar Championship Series',
    alias: 'IMSA',
    toggle: 'advanced',
    type: categoriesIds[215],
    basics: { enable: true, description: 'Premier North American sports car endurance racing championship.', identifiers: { code: 'IMSA-WT', abbreviation: 'IMSA' }, tagline: 'Where legends race', status: 'Active', visibility: { show: true } },
    details: { enable: true, visibility: { show: true } },
    traits: { enable: true, heritage: {}, schedule: 11, visibility: { show: true } },
    metrics: { enable: true, counts: { seasons: 54, events: 11, participants: 42 }, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'IMSA WeatherTech Championship | AF Motorsport', description: 'Premier North American sports car endurance racing championship' },
    generateSlug: false, slug: 'imsa-weathertech-sportscar-series',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'DTM Championship Series',
    alias: 'DTM',
    toggle: 'advanced',
    type: categoriesIds[232],
    basics: { enable: true, description: 'Premium touring car racing series featuring GT3 regulations.', identifiers: { code: 'DTM-C', abbreviation: 'DTM' }, tagline: 'Touring car excellence', status: 'Active', visibility: { show: true } },
    details: { enable: true, visibility: { show: true } },
    traits: { enable: true, heritage: {}, schedule: 12, visibility: { show: true } },
    metrics: { enable: true, counts: { seasons: 38, events: 8, participants: 26 }, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'DTM Championship | AF Motorsport', description: 'Premium touring car racing series with GT3 regulations' },
    generateSlug: false, slug: 'dtm-championship-series',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Supercars Championship Series',
    alias: 'Supercars',
    toggle: 'advanced',
    type: categoriesIds[107],
    basics: { enable: true, description: 'Premier Australian touring car racing championship.', identifiers: { code: 'SC-C', abbreviation: 'SC' }, tagline: 'V8 thunder down under', status: 'Active', visibility: { show: true } },
    details: { enable: true, visibility: { show: true } },
    traits: { enable: true, heritage: {}, schedule: 13, visibility: { show: true } },
    metrics: { enable: true, counts: { seasons: 26, events: 12, participants: 24 }, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Supercars Championship | AF Motorsport', description: 'Premier Australian touring car racing championship' },
    generateSlug: false, slug: 'supercars-championship-series',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'World Touring Car Cup Series',
    alias: 'WTCR',
    toggle: 'advanced',
    type: categoriesIds[126],
    basics: { enable: true, description: 'Global touring car racing championship with balance of performance regulations.', identifiers: { code: 'WTCR-C', abbreviation: 'WTCR' }, tagline: 'Touring cars worldwide', status: 'Active', visibility: { show: true } },
    details: { enable: true, visibility: { show: true } },
    traits: { enable: true, heritage: {}, schedule: 14, visibility: { show: true } },
    metrics: { enable: true, counts: { seasons: 6, events: 8, participants: 28 }, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'World Touring Car Cup | AF Motorsport', description: 'Global touring car racing championship with balance of performance' },
    generateSlug: false, slug: 'world-touring-car-cup-series',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Extreme E Championship Series',
    alias: 'Extreme E',
    toggle: 'advanced',
    type: categoriesIds[41],
    basics: { enable: true, description: 'Electric off-road racing series highlighting climate awareness.', identifiers: { code: 'EXE-C', abbreviation: 'EXE' }, tagline: 'Racing for the planet', status: 'Active', visibility: { show: true } },
    details: { enable: true, visibility: { show: true } },
    traits: { enable: true, heritage: {}, schedule: 15, visibility: { show: true } },
    metrics: { enable: true, counts: { seasons: 4, events: 5, participants: 18 }, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Extreme E Championship | AF Motorsport', description: 'Electric off-road racing series highlighting climate awareness' },
    generateSlug: false, slug: 'extreme-e-championship-series',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Historic Grand Prix Series',
    alias: 'HGP',
    toggle: 'advanced',
    type: categoriesIds[9],
    basics: { enable: true, description: 'Celebration of historic Formula 1 and single-seater racing heritage.', identifiers: { code: 'HGP-S', abbreviation: 'HGP' }, tagline: 'Honoring racing heritage', status: 'Active', visibility: { show: true } },
    details: { enable: true, visibility: { show: true } },
    traits: { enable: true, heritage: {}, schedule: 16, visibility: { show: true } },
    metrics: { enable: true, counts: { seasons: 15, events: 6, participants: 40 }, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Historic Grand Prix Series | AF Motorsport', description: 'Celebration of historic Formula 1 and single-seater racing heritage' },
    generateSlug: false, slug: 'historic-grand-prix-series',
    visibility: { check_publish: true, check_featured: false, check_pinned: true }
  },
  {
    name: 'Esports Racing Championship Series',
    alias: 'Esports',
    toggle: 'advanced',
    type: categoriesIds[105],
    basics: { enable: true, description: 'Virtual racing championship conducted through simulation platforms.', identifiers: { code: 'ESP-C', abbreviation: 'ESP' }, tagline: 'Virtual speed, real competition', status: 'Active', visibility: { show: true } },
    details: { enable: true, visibility: { show: true } },
    traits: { enable: true, heritage: {}, schedule: 17, visibility: { show: true } },
    metrics: { enable: true, counts: { seasons: 5, events: 18, participants: 40 }, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Esports Racing Championship | AF Motorsport', description: 'Virtual racing championship through simulation platforms' },
    generateSlug: false, slug: 'esports-racing-championship-series',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Pro-Am Endurance Trophy Series',
    alias: 'Pro-Am',
    toggle: 'advanced',
    type: categoriesIds[118],
    basics: { enable: true, description: 'Mixed professional-amateur endurance racing series promoting driver development.', identifiers: { code: 'PAM-T', abbreviation: 'ProAm' }, tagline: 'Developing tomorrow\'s champions', status: 'Active', visibility: { show: true } },
    details: { enable: true, visibility: { show: true } },
    traits: { enable: true, heritage: {}, schedule: 18, visibility: { show: true } },
    metrics: { enable: true, counts: { seasons: 7, events: 6, participants: 32 }, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Pro-Am Endurance Trophy | AF Motorsport', description: 'Mixed professional-amateur endurance racing series for driver development' },
    generateSlug: false, slug: 'pro-am-endurance-trophy-series',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Winter Development Series',
    alias: 'Winter Dev',
    toggle: 'advanced',
    type: categoriesIds[27],
    basics: { enable: true, description: 'Off-season testing and development series for skill maintenance.', identifiers: { code: 'WDS-C', abbreviation: 'WDS' }, tagline: 'Prepare for the season ahead', status: 'Active', visibility: { show: true } },
    details: { enable: true, visibility: { show: true } },
    traits: { enable: true, heritage: {}, schedule: 19, visibility: { show: true } },
    metrics: { enable: true, counts: { seasons: 4, events: 4, participants: 18 }, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Winter Development Series | AF Motorsport', description: 'Off-season testing and development series for skill maintenance' },
    generateSlug: false, slug: 'winter-development-series',
    visibility: { check_publish: true, check_featured: false, check_pinned: false }
  },
  {
    name: 'Invitational Masters Trophy Series',
    alias: 'Masters',
    toggle: 'advanced',
    type: categoriesIds[166],
    basics: { enable: true, description: 'Elite invitation-only series for legendary drivers and special entries.', identifiers: { code: 'IMT-S', abbreviation: 'Masters' }, tagline: 'Legends unite', status: 'Active', visibility: { show: true } },
    details: { enable: true, visibility: { show: true } },
    traits: { enable: true, heritage: {}, schedule: 20, visibility: { show: true } },
    metrics: { enable: true, counts: { seasons: 3, events: 3, participants: 12 }, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Invitational Masters Trophy | AF Motorsport', description: 'Elite invitation-only series for legendary drivers and special entries' },
    generateSlug: false, slug: 'invitational-masters-trophy-series',
    visibility: { check_publish: true, check_featured: true, check_pinned: true }
  }
] as const;
