// FILE: src/collections/Operations/Celebration/seeders/preload.ts
export const PRELOAD_CELEBRATION = (categoriesIds: number[], narrativesIds: number[]) => [
  {
    name: 'Championship Victory Celebration',
    toggle: 'advanced',
    type: categoriesIds[185],
    basics: { enable: true, description: 'Official celebration marking championship title achievement with team, sponsors, and fans.', visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[14], expectations: [], stories: [], visibility: { show: true } },
    traits: { enable: true, prestige: 'Iconic', exclusivity: 'InviteOnly', visibility: { show: true } },
    assets: { enable: true, primary: null, gallery: null, playlist: null, visibility: { show: true } },
    contexts: { enable: true, beneficiaries: [], notes: [], visibility: { show: true } },
    seo: { title: 'Championship Victory Celebration | AF Motorsport', description: 'Official celebration of championship title achievement' },
    generateSlug: false, slug: 'championship-victory-celebration',
    visibility: { check_publish: true, check_featured: true, check_pinned: true }
  },
  {
    name: 'Race Win Podium Celebration',
    toggle: 'advanced',
    type: categoriesIds[53],
    basics: { enable: true, description: 'Podium ceremony celebration following race victory with trophy presentation and champagne tradition.', visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[1], expectations: [], stories: [], visibility: { show: true } },
    traits: { enable: true, prestige: 'Prestigious', exclusivity: 'Public', visibility: { show: true } },
    assets: { enable: true, primary: null, gallery: null, playlist: null, visibility: { show: true } },
    contexts: { enable: true, beneficiaries: [], notes: [], visibility: { show: true } },
    seo: { title: 'Race Win Podium Celebration | AF Motorsport', description: 'Podium ceremony celebration following race victory' },
    generateSlug: false, slug: 'race-win-podium-celebration',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Career Milestone Anniversary',
    toggle: 'advanced',
    type: categoriesIds[146],
    basics: { enable: true, description: 'Commemorative celebration marking significant career milestone or anniversary achievement.', visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[26], expectations: [], stories: [], visibility: { show: true } },
    traits: { enable: true, prestige: 'Notable', exclusivity: 'Private', visibility: { show: true } },
    assets: { enable: true, primary: null, gallery: null, playlist: null, visibility: { show: true } },
    contexts: { enable: true, beneficiaries: [], notes: [], visibility: { show: true } },
    seo: { title: 'Career Milestone Anniversary | AF Motorsport', description: 'Commemorative celebration of significant career milestone' },
    generateSlug: false, slug: 'career-milestone-anniversary',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Retirement Tribute Celebration',
    toggle: 'advanced',
    type: categoriesIds[123],
    basics: { enable: true, description: 'Honorary celebration honoring legendary competitor\'s retirement from active competition.', visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[20], expectations: [], stories: [], visibility: { show: true } },
    traits: { enable: true, prestige: 'Iconic', exclusivity: 'InviteOnly', visibility: { show: true } },
    assets: { enable: true, primary: null, gallery: null, playlist: null, visibility: { show: true } },
    contexts: { enable: true, beneficiaries: [], notes: [], visibility: { show: true } },
    seo: { title: 'Retirement Tribute Celebration | AF Motorsport', description: 'Honorary celebration honoring legendary competitor retirement' },
    generateSlug: false, slug: 'retirement-tribute-celebration',
    visibility: { check_publish: true, check_featured: true, check_pinned: true }
  },
  {
    name: 'New Car Launch Celebration',
    toggle: 'advanced',
    type: categoriesIds[38],
    basics: { enable: true, description: 'Official unveiling celebration for new race car or technical development program.', visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[34], expectations: [], stories: [], visibility: { show: true } },
    traits: { enable: true, prestige: 'Prestigious', exclusivity: 'InviteOnly', visibility: { show: true } },
    assets: { enable: true, primary: null, gallery: null, playlist: null, visibility: { show: true } },
    contexts: { enable: true, beneficiaries: [], notes: [], visibility: { show: true } },
    seo: { title: 'New Car Launch Celebration | AF Motorsport', description: 'Official unveiling celebration for new race car development' },
    generateSlug: false, slug: 'new-car-launch-celebration',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Technical Innovation Award Ceremony',
    toggle: 'advanced',
    type: categoriesIds[122],
    basics: { enable: true, description: 'Recognition celebration for outstanding technical achievement or engineering breakthrough.', visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[13], expectations: [], stories: [], visibility: { show: true } },
    traits: { enable: true, prestige: 'Prestigious', exclusivity: 'Private', visibility: { show: true } },
    assets: { enable: true, primary: null, gallery: null, playlist: null, visibility: { show: true } },
    contexts: { enable: true, beneficiaries: [], notes: [], visibility: { show: true } },
    seo: { title: 'Technical Innovation Award | AF Motorsport', description: 'Recognition celebration for outstanding technical achievement' },
    generateSlug: false, slug: 'technical-innovation-award-ceremony',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Team Achievement Milestone',
    toggle: 'advanced',
    type: categoriesIds[17],
    basics: { enable: true, description: 'Internal celebration marking organizational milestone or collective team achievement.', visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[19], expectations: [], stories: [], visibility: { show: true } },
    traits: { enable: true, prestige: 'Notable', exclusivity: 'TeamOnly', visibility: { show: true } },
    assets: { enable: true, primary: null, gallery: null, playlist: null, visibility: { show: true } },
    contexts: { enable: true, beneficiaries: [], notes: [], visibility: { show: true } },
    seo: { title: 'Team Achievement Milestone | AF Motorsport', description: 'Internal celebration marking organizational milestone achievement' },
    generateSlug: false, slug: 'team-achievement-milestone',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Homecoming Welcome Celebration',
    toggle: 'advanced',
    type: categoriesIds[245],
    basics: { enable: true, description: 'Community welcome celebration for competitor returning home after championship success.', visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[48], expectations: [], stories: [], visibility: { show: true } },
    traits: { enable: true, prestige: 'Notable', exclusivity: 'Public', visibility: { show: true } },
    assets: { enable: true, primary: null, gallery: null, playlist: null, visibility: { show: true } },
    contexts: { enable: true, beneficiaries: [], notes: [], visibility: { show: true } },
    seo: { title: 'Homecoming Welcome Celebration | AF Motorsport', description: 'Community welcome celebration for championship competitor return' },
    generateSlug: false, slug: 'homecoming-welcome-celebration',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Hall of Fame Induction Ceremony',
    toggle: 'advanced',
    type: categoriesIds[243],
    basics: { enable: true, description: 'Formal induction celebration honoring legendary contributor to motorsport heritage.', visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[56], expectations: [], stories: [], visibility: { show: true } },
    traits: { enable: true, prestige: 'Iconic', exclusivity: 'InviteOnly', visibility: { show: true } },
    assets: { enable: true, primary: null, gallery: null, playlist: null, visibility: { show: true } },
    contexts: { enable: true, beneficiaries: [], notes: [], visibility: { show: true } },
    seo: { title: 'Hall of Fame Induction | AF Motorsport', description: 'Formal induction ceremony honoring legendary motorsport contributor' },
    generateSlug: false, slug: 'hall-of-fame-induction-ceremony',
    visibility: { check_publish: true, check_featured: true, check_pinned: true }
  },
  {
    name: 'Lifetime Achievement Recognition',
    toggle: 'advanced',
    type: categoriesIds[52],
    basics: { enable: true, description: 'Special recognition celebration honoring sustained excellence and enduring contribution to the sport.', visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[23], expectations: [], stories: [], visibility: { show: true } },
    traits: { enable: true, prestige: 'Iconic', exclusivity: 'InviteOnly', visibility: { show: true } },
    assets: { enable: true, primary: null, gallery: null, playlist: null, visibility: { show: true } },
    contexts: { enable: true, beneficiaries: [], notes: [], visibility: { show: true } },
    seo: { title: 'Lifetime Achievement Recognition | AF Motorsport', description: 'Special recognition for sustained excellence and enduring contribution' },
    generateSlug: false, slug: 'lifetime-achievement-recognition',
    visibility: { check_publish: true, check_featured: true, check_pinned: true }
  },
  {
    name: 'Team of the Year Award',
    toggle: 'advanced',
    type: categoriesIds[215],
    basics: { enable: true, description: 'Annual recognition celebration honoring outstanding collective team performance and achievement.', visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[12], expectations: [], stories: [], visibility: { show: true } },
    traits: { enable: true, prestige: 'Prestigious', exclusivity: 'InviteOnly', visibility: { show: true } },
    assets: { enable: true, primary: null, gallery: null, playlist: null, visibility: { show: true } },
    contexts: { enable: true, beneficiaries: [], notes: [], visibility: { show: true } },
    seo: { title: 'Team of the Year Award | AF Motorsport', description: 'Annual recognition for outstanding collective team performance' },
    generateSlug: false, slug: 'team-of-the-year-award',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Employee Excellence Recognition',
    toggle: 'advanced',
    type: categoriesIds[232],
    basics: { enable: true, description: 'Internal celebration honoring exceptional individual contribution to organizational success.', visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[7], expectations: [], stories: [], visibility: { show: true } },
    traits: { enable: true, prestige: 'Notable', exclusivity: 'TeamOnly', visibility: { show: true } },
    assets: { enable: true, primary: null, gallery: null, playlist: null, visibility: { show: true } },
    contexts: { enable: true, beneficiaries: [], notes: [], visibility: { show: true } },
    seo: { title: 'Employee Excellence Recognition | AF Motorsport', description: 'Internal celebration honoring exceptional individual contribution' },
    generateSlug: false, slug: 'employee-excellence-recognition',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Long Service Appreciation',
    toggle: 'advanced',
    type: categoriesIds[107],
    basics: { enable: true, description: 'Recognition celebration honoring dedicated long-term service and loyalty to organization.', visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[9], expectations: [], stories: [], visibility: { show: true } },
    traits: { enable: true, prestige: 'Notable', exclusivity: 'Private', visibility: { show: true } },
    assets: { enable: true, primary: null, gallery: null, playlist: null, visibility: { show: true } },
    contexts: { enable: true, beneficiaries: [], notes: [], visibility: { show: true } },
    seo: { title: 'Long Service Appreciation | AF Motorsport', description: 'Recognition for dedicated long-term service and organizational loyalty' },
    generateSlug: false, slug: 'long-service-appreciation',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Fan Favorite Award Ceremony',
    toggle: 'advanced',
    type: categoriesIds[126],
    basics: { enable: true, description: 'Public celebration honoring competitor or team most admired by global fan community.', visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[6], expectations: [], stories: [], visibility: { show: true } },
    traits: { enable: true, prestige: 'Notable', exclusivity: 'Public', visibility: { show: true } },
    assets: { enable: true, primary: null, gallery: null, playlist: null, visibility: { show: true } },
    contexts: { enable: true, beneficiaries: [], notes: [], visibility: { show: true } },
    seo: { title: 'Fan Favorite Award | AF Motorsport', description: 'Public celebration honoring most admired competitor by fan community' },
    generateSlug: false, slug: 'fan-favorite-award-ceremony',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Moment of the Season Celebration',
    toggle: 'advanced',
    type: categoriesIds[41],
    basics: { enable: true, description: 'Annual recognition celebrating most memorable or impactful competitive moment of the season.', visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[42], expectations: [], stories: [], visibility: { show: true } },
    traits: { enable: true, prestige: 'Prestigious', exclusivity: 'Public', visibility: { show: true } },
    assets: { enable: true, primary: null, gallery: null, playlist: null, visibility: { show: true } },
    contexts: { enable: true, beneficiaries: [], notes: [], visibility: { show: true } },
    seo: { title: 'Moment of the Season | AF Motorsport', description: 'Annual recognition of most memorable competitive moment' },
    generateSlug: false, slug: 'moment-of-the-season-celebration',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Overtake of the Year Award',
    toggle: 'advanced',
    type: categoriesIds[9],
    basics: { enable: true, description: 'Recognition celebration honoring most spectacular or skillful overtaking maneuver of the season.', visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[22], expectations: [], stories: [], visibility: { show: true } },
    traits: { enable: true, prestige: 'Notable', exclusivity: 'Public', visibility: { show: true } },
    assets: { enable: true, primary: null, gallery: null, playlist: null, visibility: { show: true } },
    contexts: { enable: true, beneficiaries: [], notes: [], visibility: { show: true } },
    seo: { title: 'Overtake of the Year | AF Motorsport', description: 'Recognition for most spectacular overtaking maneuver of the season' },
    generateSlug: false, slug: 'overtake-of-the-year-award',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Photograph of the Year Exhibition',
    toggle: 'advanced',
    type: categoriesIds[105],
    basics: { enable: true, description: 'Curated celebration showcasing most iconic or emotionally resonant motorsport photography.', visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[3], expectations: [], stories: [], visibility: { show: true } },
    traits: { enable: true, prestige: 'Prestigious', exclusivity: 'InviteOnly', visibility: { show: true } },
    assets: { enable: true, primary: null, gallery: null, playlist: null, visibility: { show: true } },
    contexts: { enable: true, beneficiaries: [], notes: [], visibility: { show: true } },
    seo: { title: 'Photograph of the Year | AF Motorsport', description: 'Curated exhibition showcasing iconic motorsport photography' },
    generateSlug: false, slug: 'photograph-of-the-year-exhibition',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Safety Innovation Recognition',
    toggle: 'advanced',
    type: categoriesIds[118],
    basics: { enable: true, description: 'Special celebration honoring breakthrough safety technology or protocol saving lives.', visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[16], expectations: [], stories: [], visibility: { show: true } },
    traits: { enable: true, prestige: 'Iconic', exclusivity: 'InviteOnly', visibility: { show: true } },
    assets: { enable: true, primary: null, gallery: null, playlist: null, visibility: { show: true } },
    contexts: { enable: true, beneficiaries: [], notes: [], visibility: { show: true } },
    seo: { title: 'Safety Innovation Recognition | AF Motorsport', description: 'Special celebration honoring life-saving safety technology breakthrough' },
    generateSlug: false, slug: 'safety-innovation-recognition',
    visibility: { check_publish: true, check_featured: true, check_pinned: true }
  },
  {
    name: 'Environmental Leadership Award',
    toggle: 'advanced',
    type: categoriesIds[27],
    basics: { enable: true, description: 'Recognition celebration honoring outstanding sustainability initiative or environmental contribution.', visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[49], expectations: [], stories: [], visibility: { show: true } },
    traits: { enable: true, prestige: 'Prestigious', exclusivity: 'InviteOnly', visibility: { show: true } },
    assets: { enable: true, primary: null, gallery: null, playlist: null, visibility: { show: true } },
    contexts: { enable: true, beneficiaries: [], notes: [], visibility: { show: true } },
    seo: { title: 'Environmental Leadership Award | AF Motorsport', description: 'Recognition for outstanding sustainability initiative or environmental contribution' },
    generateSlug: false, slug: 'environmental-leadership-award',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Community Impact Celebration',
    toggle: 'advanced',
    type: categoriesIds[166],
    basics: { enable: true, description: 'Public celebration honoring meaningful community engagement or charitable contribution by motorsport entity.', visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[14], expectations: [], stories: [], visibility: { show: true } },
    traits: { enable: true, prestige: 'Notable', exclusivity: 'Public', visibility: { show: true } },
    assets: { enable: true, primary: null, gallery: null, playlist: null, visibility: { show: true } },
    contexts: { enable: true, beneficiaries: [], notes: [], visibility: { show: true } },
    seo: { title: 'Community Impact Celebration | AF Motorsport', description: 'Public celebration honoring meaningful community engagement or charitable contribution' },
    generateSlug: false, slug: 'community-impact-celebration',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  }
] as const;
