// FILE: src/collections/Competition/Entry/seeders/preload.ts
export const PRELOAD_ENTRY = (categoriesIds: number[]) => [
  {
    name: 'Entry 1 - Red Bull Racing',
    toggle: 'advanced',
    type: categoriesIds[185],
    basics: { enable: true, description: 'Defending championship works entry with title contender.', identifiers: { number: '1', plate: 'NLD' }, status: 'Confirmed', visibility: { show: true } },
    details: { enable: true, session: 1, drivers: 1, car: 1, visibility: { show: true } },
    traits: { enable: true, role: 'Primary', eligibility: { license: 'FIA Platinum' }, visibility: { show: true } },
    metrics: { enable: true, positions: { grid: 1, start: 1, finish: 1, laps: 58 }, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Entry 1 Red Bull Racing | AF Motorsport', description: 'Championship defending works entry' },
    generateSlug: false, slug: 'entry-1-red-bull-racing',
    visibility: { check_publish: true, check_featured: true, check_pinned: true }
  },
  {
    name: 'Entry 11 - Red Bull Racing',
    toggle: 'advanced',
    type: categoriesIds[53],
    basics: { enable: true, description: 'Secondary works entry supporting championship campaign.', identifiers: { number: '11', plate: 'MEX' }, status: 'Confirmed', visibility: { show: true } },
    details: { enable: true, session: 1, drivers: 2, car: 2, visibility: { show: true } },
    traits: { enable: true, role: 'Primary', eligibility: { license: 'FIA Platinum' }, visibility: { show: true } },
    metrics: { enable: true, positions: { grid: 2, start: 2, finish: 2, laps: 58 }, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Entry 11 Red Bull Racing | AF Motorsport', description: 'Secondary works entry for championship contention' },
    generateSlug: false, slug: 'entry-11-red-bull-racing',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Entry 44 - Mercedes-AMG Petronas',
    toggle: 'advanced',
    type: categoriesIds[146],
    basics: { enable: true, description: 'Seven-time world champion leading Mercedes resurgence.', identifiers: { number: '44', plate: 'GBR' }, status: 'Confirmed', visibility: { show: true } },
    details: { enable: true, session: 1, drivers: 3, car: 3, visibility: { show: true } },
    traits: { enable: true, role: 'Primary', eligibility: { license: 'FIA Platinum' }, visibility: { show: true } },
    metrics: { enable: true, positions: { grid: 3, start: 3, finish: 3, laps: 58 }, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Entry 44 Mercedes | AF Motorsport', description: 'Mercedes works entry with legendary driver' },
    generateSlug: false, slug: 'entry-44-mercedes-amg-petronas',
    visibility: { check_publish: true, check_featured: true, check_pinned: true }
  },
  {
    name: 'Entry 63 - Mercedes-AMG Petronas',
    toggle: 'advanced',
    type: categoriesIds[123],
    basics: { enable: true, description: 'Rising star driver in Mercedes factory program.', identifiers: { number: '63', plate: 'GBR' }, status: 'Confirmed', visibility: { show: true } },
    details: { enable: true, session: 1, drivers: 4, car: 4, visibility: { show: true } },
    traits: { enable: true, role: 'Primary', eligibility: { license: 'FIA Platinum' }, visibility: { show: true } },
    metrics: { enable: true, positions: { grid: 4, start: 4, finish: 4, laps: 58 }, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Entry 63 Mercedes | AF Motorsport', description: 'Mercedes works entry with emerging talent' },
    generateSlug: false, slug: 'entry-63-mercedes-amg-petronas',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Entry 16 - Scuderia Ferrari',
    toggle: 'advanced',
    type: categoriesIds[38],
    basics: { enable: true, description: 'Ferrari factory entry carrying Italian racing heritage.', identifiers: { number: '16', plate: 'MCO' }, status: 'Confirmed', visibility: { show: true } },
    details: { enable: true, session: 1, drivers: 5, car: 5, visibility: { show: true } },
    traits: { enable: true, role: 'Primary', eligibility: { license: 'FIA Platinum' }, visibility: { show: true } },
    metrics: { enable: true, positions: { grid: 5, start: 5, finish: 5, laps: 58 }, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Entry 16 Ferrari | AF Motorsport', description: 'Ferrari works entry with championship aspirations' },
    generateSlug: false, slug: 'entry-16-scuderia-ferrari',
    visibility: { check_publish: true, check_featured: true, check_pinned: true }
  },
  {
    name: 'Entry 55 - Scuderia Ferrari',
    toggle: 'advanced',
    type: categoriesIds[122],
    basics: { enable: true, description: 'Ferrari factory entry with consistent podium contender.', identifiers: { number: '55', plate: 'ESP' }, status: 'Confirmed', visibility: { show: true } },
    details: { enable: true, session: 1, drivers: 6, car: 6, visibility: { show: true } },
    traits: { enable: true, role: 'Primary', eligibility: { license: 'FIA Platinum' }, visibility: { show: true } },
    metrics: { enable: true, positions: { grid: 6, start: 6, finish: 6, laps: 58 }, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Entry 55 Ferrari | AF Motorsport', description: 'Ferrari works entry with race-winning potential' },
    generateSlug: false, slug: 'entry-55-scuderia-ferrari',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Entry 4 - McLaren F1 Team',
    toggle: 'advanced',
    type: categoriesIds[17],
    basics: { enable: true, description: 'McLaren factory entry with aggressive development program.', identifiers: { number: '4', plate: 'GBR' }, status: 'Confirmed', visibility: { show: true } },
    details: { enable: true, session: 1, drivers: 7, car: 7, visibility: { show: true } },
    traits: { enable: true, role: 'Primary', eligibility: { license: 'FIA Platinum' }, visibility: { show: true } },
    metrics: { enable: true, positions: { grid: 7, start: 7, finish: 7, laps: 58 }, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Entry 4 McLaren | AF Motorsport', description: 'McLaren works entry with championship development focus' },
    generateSlug: false, slug: 'entry-4-mclaren-f1-team',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Entry 81 - McLaren F1 Team',
    toggle: 'advanced',
    type: categoriesIds[245],
    basics: { enable: true, description: 'McLaren factory entry with breakthrough performance trajectory.', identifiers: { number: '81', plate: 'AUS' }, status: 'Confirmed', visibility: { show: true } },
    details: { enable: true, session: 1, drivers: 8, car: 8, visibility: { show: true } },
    traits: { enable: true, role: 'Primary', eligibility: { license: 'FIA Platinum' }, visibility: { show: true } },
    metrics: { enable: true, positions: { grid: 8, start: 8, finish: 8, laps: 58 }, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Entry 81 McLaren | AF Motorsport', description: 'McLaren works entry with rising competitive performance' },
    generateSlug: false, slug: 'entry-81-mclaren-f1-team',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Entry 14 - Aston Martin Aramco',
    toggle: 'advanced',
    type: categoriesIds[243],
    basics: { enable: true, description: 'Aston Martin factory entry with strategic investment backing.', identifiers: { number: '14', plate: 'ESP' }, status: 'Confirmed', visibility: { show: true } },
    details: { enable: true, session: 1, drivers: 9, car: 9, visibility: { show: true } },
    traits: { enable: true, role: 'Primary', eligibility: { license: 'FIA Platinum' }, visibility: { show: true } },
    metrics: { enable: true, positions: { grid: 9, start: 9, finish: 9, laps: 58 }, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Entry 14 Aston Martin | AF Motorsport', description: 'Aston Martin works entry with championship development program' },
    generateSlug: false, slug: 'entry-14-aston-martin-aramco',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Entry 18 - Aston Martin Aramco',
    toggle: 'advanced',
    type: categoriesIds[52],
    basics: { enable: true, description: 'Aston Martin factory entry with experienced racecraft.', identifiers: { number: '18', plate: 'CAN' }, status: 'Confirmed', visibility: { show: true } },
    details: { enable: true, session: 1, drivers: 10, car: 10, visibility: { show: true } },
    traits: { enable: true, role: 'Primary', eligibility: { license: 'FIA Platinum' }, visibility: { show: true } },
    metrics: { enable: true, positions: { grid: 10, start: 10, finish: 10, laps: 58 }, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Entry 18 Aston Martin | AF Motorsport', description: 'Aston Martin works entry with veteran driver leadership' },
    generateSlug: false, slug: 'entry-18-aston-martin-aramco',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Entry 22 - Visa Cash App RB',
    toggle: 'advanced',
    type: categoriesIds[215],
    basics: { enable: true, description: 'Independent customer entry with Red Bull powertrain supply.', identifiers: { number: '22', plate: 'JPN' }, status: 'Confirmed', visibility: { show: true } },
    details: { enable: true, session: 1, drivers: 11, car: 11, visibility: { show: true } },
    traits: { enable: true, role: 'Primary', eligibility: { license: 'FIA Platinum' }, visibility: { show: true } },
    metrics: { enable: true, positions: { grid: 11, start: 11, finish: 11, laps: 58 }, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Entry 22 RB F1 Team | AF Motorsport', description: 'Customer entry with Red Bull technical partnership' },
    generateSlug: false, slug: 'entry-22-visa-cash-app-rb',
    visibility: { check_publish: true, check_featured: false, check_pinned: false }
  },
  {
    name: 'Entry 3 - Visa Cash App RB',
    toggle: 'advanced',
    type: categoriesIds[232],
    basics: { enable: true, description: 'Independent customer entry developing young talent.', identifiers: { number: '3', plate: 'AUS' }, status: 'Confirmed', visibility: { show: true } },
    details: { enable: true, session: 1, drivers: 12, car: 12, visibility: { show: true } },
    traits: { enable: true, role: 'Primary', eligibility: { license: 'FIA Platinum' }, visibility: { show: true } },
    metrics: { enable: true, positions: { grid: 12, start: 12, finish: 12, laps: 58 }, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Entry 3 RB F1 Team | AF Motorsport', description: 'Customer entry focused on driver development program' },
    generateSlug: false, slug: 'entry-3-visa-cash-app-rb',
    visibility: { check_publish: true, check_featured: false, check_pinned: false }
  },
  {
    name: 'Entry 27 - Haas F1 Team',
    toggle: 'advanced',
    type: categoriesIds[107],
    basics: { enable: true, description: 'American customer entry with Ferrari technical alliance.', identifiers: { number: '27', plate: 'DEU' }, status: 'Confirmed', visibility: { show: true } },
    details: { enable: true, session: 1, drivers: 13, car: 13, visibility: { show: true } },
    traits: { enable: true, role: 'Primary', eligibility: { license: 'FIA Platinum' }, visibility: { show: true } },
    metrics: { enable: true, positions: { grid: 13, start: 13, finish: 13, laps: 58 }, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Entry 27 Haas F1 | AF Motorsport', description: 'Customer entry with Ferrari powertrain and technical support' },
    generateSlug: false, slug: 'entry-27-haas-f1-team',
    visibility: { check_publish: true, check_featured: false, check_pinned: false }
  },
  {
    name: 'Entry 20 - Haas F1 Team',
    toggle: 'advanced',
    type: categoriesIds[126],
    basics: { enable: true, description: 'American customer entry with consistent midfield performance.', identifiers: { number: '20', plate: 'DNK' }, status: 'Confirmed', visibility: { show: true } },
    details: { enable: true, session: 1, drivers: 14, car: 14, visibility: { show: true } },
    traits: { enable: true, role: 'Primary', eligibility: { license: 'FIA Platinum' }, visibility: { show: true } },
    metrics: { enable: true, positions: { grid: 14, start: 14, finish: 14, laps: 58 }, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Entry 20 Haas F1 | AF Motorsport', description: 'Customer entry with reliable midfield competitiveness' },
    generateSlug: false, slug: 'entry-20-haas-f1-team',
    visibility: { check_publish: true, check_featured: false, check_pinned: false }
  },
  {
    name: 'Entry 31 - BWT Alpine F1 Team',
    toggle: 'advanced',
    type: categoriesIds[41],
    basics: { enable: true, description: 'French factory entry with Renault powertrain development.', identifiers: { number: '31', plate: 'FRA' }, status: 'Confirmed', visibility: { show: true } },
    details: { enable: true, session: 1, drivers: 15, car: 15, visibility: { show: true } },
    traits: { enable: true, role: 'Primary', eligibility: { license: 'FIA Platinum' }, visibility: { show: true } },
    metrics: { enable: true, positions: { grid: 15, start: 15, finish: 15, laps: 58 }, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Entry 31 Alpine F1 | AF Motorsport', description: 'Alpine works entry with French motorsport heritage' },
    generateSlug: false, slug: 'entry-31-bwt-alpine-f1-team',
    visibility: { check_publish: true, check_featured: false, check_pinned: false }
  },
  {
    name: 'Entry 10 - BWT Alpine F1 Team',
    toggle: 'advanced',
    type: categoriesIds[9],
    basics: { enable: true, description: 'French factory entry with strategic technical partnerships.', identifiers: { number: '10', plate: 'FRA' }, status: 'Confirmed', visibility: { show: true } },
    details: { enable: true, session: 1, drivers: 16, car: 16, visibility: { show: true } },
    traits: { enable: true, role: 'Primary', eligibility: { license: 'FIA Platinum' }, visibility: { show: true } },
    metrics: { enable: true, positions: { grid: 16, start: 16, finish: 16, laps: 58 }, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Entry 10 Alpine F1 | AF Motorsport', description: 'Alpine works entry with championship development focus' },
    generateSlug: false, slug: 'entry-10-bwt-alpine-f1-team',
    visibility: { check_publish: true, check_featured: false, check_pinned: false }
  },
  {
    name: 'Entry 23 - Williams Racing',
    toggle: 'advanced',
    type: categoriesIds[105],
    basics: { enable: true, description: 'Historic British factory entry with rebuild program.', identifiers: { number: '23', plate: 'THA' }, status: 'Confirmed', visibility: { show: true } },
    details: { enable: true, session: 1, drivers: 17, car: 17, visibility: { show: true } },
    traits: { enable: true, role: 'Primary', eligibility: { license: 'FIA Platinum' }, visibility: { show: true } },
    metrics: { enable: true, positions: { grid: 17, start: 17, finish: 17, laps: 58 }, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Entry 23 Williams Racing | AF Motorsport', description: 'Williams works entry with historic championship legacy' },
    generateSlug: false, slug: 'entry-23-williams-racing',
    visibility: { check_publish: true, check_featured: false, check_pinned: false }
  },
  {
    name: 'Entry 2 - Williams Racing',
    toggle: 'advanced',
    type: categoriesIds[118],
    basics: { enable: true, description: 'Historic British factory entry with emerging talent program.', identifiers: { number: '2', plate: 'USA' }, status: 'Confirmed', visibility: { show: true } },
    details: { enable: true, session: 1, drivers: 18, car: 18, visibility: { show: true } },
    traits: { enable: true, role: 'Primary', eligibility: { license: 'FIA Platinum' }, visibility: { show: true } },
    metrics: { enable: true, positions: { grid: 18, start: 18, finish: 18, laps: 58 }, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Entry 2 Williams Racing | AF Motorsport', description: 'Williams works entry with driver academy development' },
    generateSlug: false, slug: 'entry-2-williams-racing',
    visibility: { check_publish: true, check_featured: false, check_pinned: false }
  },
  {
    name: 'Entry 77 - Stake F1 Team Kick Sauber',
    toggle: 'advanced',
    type: categoriesIds[27],
    basics: { enable: true, description: 'Customer entry with Ferrari powertrain and technical support.', identifiers: { number: '77', plate: 'FIN' }, status: 'Confirmed', visibility: { show: true } },
    details: { enable: true, session: 1, drivers: 19, car: 19, visibility: { show: true } },
    traits: { enable: true, role: 'Primary', eligibility: { license: 'FIA Platinum' }, visibility: { show: true } },
    metrics: { enable: true, positions: { grid: 19, start: 19, finish: 19, laps: 58 }, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Entry 77 Stake Sauber | AF Motorsport', description: 'Customer entry with Ferrari technical partnership' },
    generateSlug: false, slug: 'entry-77-stake-f1-team-kick-sauber',
    visibility: { check_publish: true, check_featured: false, check_pinned: false }
  },
  {
    name: 'Entry 24 - Stake F1 Team Kick Sauber',
    toggle: 'advanced',
    type: categoriesIds[166],
    basics: { enable: true, description: 'Customer entry developing next-generation racing talent.', identifiers: { number: '24', plate: 'CHN' }, status: 'Confirmed', visibility: { show: true } },
    details: { enable: true, session: 1, drivers: 20, car: 20, visibility: { show: true } },
    traits: { enable: true, role: 'Primary', eligibility: { license: 'FIA Platinum' }, visibility: { show: true } },
    metrics: { enable: true, positions: { grid: 20, start: 20, finish: 20, laps: 58 }, visibility: { show: true } },
    assets: { enable: true, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Entry 24 Stake Sauber | AF Motorsport', description: 'Customer entry with driver development and technical growth focus' },
    generateSlug: false, slug: 'entry-24-stake-f1-team-kick-sauber',
    visibility: { check_publish: true, check_featured: false, check_pinned: false }
  }
] as const;
