export const PRELOAD_TRAINING = (categoriesIds: number[], narrativesIds: number[]) => [
  {
    name: 'F1 Driver Simulator Track Familiarization - Monaco GP',
    toggle: 'advanced',
    type: categoriesIds[185],
    basics: {
      enable: true,
      description: 'Immersive simulator session for drivers to master Monaco circuit nuances including elevation changes, barrier proximity, and qualifying lap optimization under pressure conditions.',
      visibility: { show: true },
    },
    details: {
      enable: true,
      narrative: narrativesIds[14],
      visibility: { show: true },
    },
    traits: {
      enable: true,
      intensity: 'High',
      format: 'Simulated',
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'f1-simulator-track-familiarization-monaco',
    visibility: { check_publish: true, check_featured: true, check_pinned: false },
  },
  {
    name: 'WEC Endurance Driver Stint Management Training',
    toggle: 'advanced',
    type: categoriesIds[53],
    basics: {
      enable: true,
      description: 'Comprehensive program teaching endurance drivers fuel conservation, tire management, traffic navigation, and driver change procedures for 24-hour race conditions.',
      visibility: { show: true },
    },
    details: {
      enable: true,
      narrative: narrativesIds[1],
      visibility: { show: true },
    },
    traits: {
      enable: true,
      intensity: 'Extreme',
      format: 'HandsOn',
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'wec-endurance-stint-management-training',
    visibility: { check_publish: true, check_featured: true, check_pinned: false },
  },
  {
    name: 'MotoGP Cornering Technique Workshop - Sepang',
    toggle: 'advanced',
    type: categoriesIds[146],
    basics: {
      enable: true,
      description: 'Track-side workshop focusing on tropical condition cornering, lean angle optimization, brake modulation, and overtaking maneuvers specific to Sepang International Circuit.',
      visibility: { show: true },
    },
    details: {
      enable: true,
      narrative: narrativesIds[26],
      visibility: { show: true },
    },
    traits: {
      enable: true,
      intensity: 'High',
      format: 'HandsOn',
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'motogp-cornering-technique-workshop-sepang',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    name: 'Rally Co-Driver Pace Note Certification',
    toggle: 'advanced',
    type: categoriesIds[123],
    basics: {
      enable: true,
      description: 'Official certification program for co-drivers covering pace note syntax, recce methodology, weather adaptation, and real-time communication protocols for WRC competition.',
      visibility: { show: true },
    },
    details: {
      enable: true,
      narrative: narrativesIds[20],
      visibility: { show: true },
    },
    traits: {
      enable: true,
      intensity: 'Medium',
      format: 'Classroom',
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'rally-co-driver-pace-note-certification',
    visibility: { check_publish: true, check_featured: true, check_pinned: false },
  },
  {
    name: 'Pit Crew Tire Change Speed Drill',
    toggle: 'advanced',
    type: categoriesIds[38],
    basics: {
      enable: true,
      description: 'High-repetition drill program for pit crew members to achieve sub-2.5 second tire changes with perfect choreography, tool handling, and safety compliance under race pressure.',
      visibility: { show: true },
    },
    details: {
      enable: true,
      narrative: narrativesIds[34],
      visibility: { show: true },
    },
    traits: {
      enable: true,
      intensity: 'Extreme',
      format: 'HandsOn',
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'pit-crew-tire-change-speed-drill',
    visibility: { check_publish: true, check_featured: true, check_pinned: true },
  },
  {
    name: 'Race Engineer Data Analysis Masterclass',
    toggle: 'advanced',
    type: categoriesIds[122],
    basics: {
      enable: true,
      description: 'Advanced training for race engineers on telemetry interpretation, performance delta analysis, setup correlation, and real-time decision support using proprietary data platforms.',
      visibility: { show: true },
    },
    details: {
      enable: true,
      narrative: narrativesIds[13],
      visibility: { show: true },
    },
    traits: {
      enable: true,
      intensity: 'High',
      format: 'Lecture',
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'race-engineer-data-analysis-masterclass',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    name: 'Motorsport Leadership & Decision-Making Seminar',
    toggle: 'advanced',
    type: categoriesIds[17],
    basics: {
      enable: true,
      description: 'Executive seminar for team principals and department heads on crisis management, strategic prioritization, personnel leadership, and high-stakes decision frameworks in racing environments.',
      visibility: { show: true },
    },
    details: {
      enable: true,
      narrative: narrativesIds[19],
      visibility: { show: true },
    },
    traits: {
      enable: true,
      intensity: 'Medium',
      format: 'Group',
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'motorsport-leadership-decision-making-seminar',
    visibility: { check_publish: true, check_featured: true, check_pinned: false },
  },
  {
    name: 'Emergency Medical Response Trackside Training',
    toggle: 'advanced',
    type: categoriesIds[245],
    basics: {
      enable: true,
      description: 'FIA-certified emergency response training for medical delegates, marshals, and extraction teams covering trauma assessment, extrication protocols, and rapid transport procedures.',
      visibility: { show: true },
    },
    details: {
      enable: true,
      narrative: narrativesIds[48],
      visibility: { show: true },
    },
    traits: {
      enable: true,
      intensity: 'Extreme',
      format: 'HandsOn',
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'emergency-medical-response-trackside-training',
    visibility: { check_publish: true, check_featured: true, check_pinned: true },
  },
  {
    name: 'Hybrid Powertrain Technical Briefing Workshop',
    toggle: 'advanced',
    type: categoriesIds[243],
    basics: {
      enable: true,
      description: 'Technical workshop for engineers and technicians on MGU-K/MGU-H deployment strategies, energy recovery optimization, thermal management, and regulatory compliance for hybrid racing systems.',
      visibility: { show: true },
    },
    details: {
      enable: true,
      narrative: narrativesIds[56],
      visibility: { show: true },
    },
    traits: {
      enable: true,
      intensity: 'High',
      format: 'Lecture',
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'hybrid-powertrain-technical-briefing-workshop',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    name: 'Aerodynamic Setup Optimization Classroom',
    toggle: 'advanced',
    type: categoriesIds[52],
    basics: {
      enable: true,
      description: 'Classroom-based training on CFD correlation, wind tunnel data interpretation, downforce/drag trade-offs, and setup adjustments for varying circuit characteristics and weather conditions.',
      visibility: { show: true },
    },
    details: {
      enable: true,
      narrative: narrativesIds[23],
      visibility: { show: true },
    },
    traits: {
      enable: true,
      intensity: 'Medium',
      format: 'Lecture',
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'aerodynamic-setup-optimization-classroom',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    name: 'Media Interview & Press Conference Training',
    toggle: 'advanced',
    type: categoriesIds[215],
    basics: {
      enable: true,
      description: 'Professional media training for drivers and team personnel covering message discipline, crisis communication, social media protocol, and brand representation during high-pressure interview scenarios.',
      visibility: { show: true },
    },
    details: {
      enable: true,
      narrative: narrativesIds[12],
      visibility: { show: true },
    },
    traits: {
      enable: true,
      intensity: 'Low',
      format: 'Group',
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'media-interview-press-conference-training',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    name: 'Fitness & Reaction Time Conditioning Program',
    toggle: 'advanced',
    type: categoriesIds[232],
    basics: {
      enable: true,
      description: 'Specialized physical conditioning program for drivers focusing on neck strength, cardiovascular endurance, reaction time drills, and G-force tolerance training for competition readiness.',
      visibility: { show: true },
    },
    details: {
      enable: true,
      narrative: narrativesIds[7],
      visibility: { show: true },
    },
    traits: {
      enable: true,
      intensity: 'High',
      format: 'Individual',
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'fitness-reaction-time-conditioning-program',
    visibility: { check_publish: true, check_featured: true, check_pinned: false },
  },
  {
    name: 'Strategy Simulation: Race Day Scenario Planning',
    toggle: 'advanced',
    type: categoriesIds[107],
    basics: {
      enable: true,
      description: 'Interactive simulation training for strategists covering tire compound selection, pit window optimization, weather contingency planning, and competitor response modeling for dynamic race conditions.',
      visibility: { show: true },
    },
    details: {
      enable: true,
      narrative: narrativesIds[9],
      visibility: { show: true },
    },
    traits: {
      enable: true,
      intensity: 'High',
      format: 'Simulated',
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'strategy-simulation-race-day-scenario-planning',
    visibility: { check_publish: true, check_featured: true, check_pinned: false },
  },
  {
    name: 'New Driver Onboarding: Team Protocols & Systems',
    toggle: 'advanced',
    type: categoriesIds[126],
    basics: {
      enable: true,
      description: 'Comprehensive onboarding program for new drivers covering team culture, communication protocols, technical briefings, simulator access, and performance expectation frameworks.',
      visibility: { show: true },
    },
    details: {
      enable: true,
      narrative: narrativesIds[6],
      visibility: { show: true },
    },
    traits: {
      enable: true,
      intensity: 'Medium',
      format: 'Group',
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'new-driver-onboarding-team-protocols-systems',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    name: 'Advanced Telemetry Interpretation Workshop',
    toggle: 'advanced',
    type: categoriesIds[41],
    basics: {
      enable: true,
      description: 'Hands-on workshop for performance engineers on real-time telemetry analysis, sector comparison, driver input correlation, and setup feedback loops using live data acquisition systems.',
      visibility: { show: true },
    },
    details: {
      enable: true,
      narrative: narrativesIds[42],
      visibility: { show: true },
    },
    traits: {
      enable: true,
      intensity: 'High',
      format: 'HandsOn',
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'advanced-telemetry-interpretation-workshop',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    name: 'Safety Car & Virtual Safety Car Procedure Training',
    toggle: 'advanced',
    type: categoriesIds[9],
    basics: {
      enable: true,
      description: 'Refresher training for all competition personnel on SC/VSC deployment protocols, gap management, pit lane procedures, and restart coordination under FIA regulatory frameworks.',
      visibility: { show: true },
    },
    details: {
      enable: true,
      narrative: narrativesIds[22],
      visibility: { show: true },
    },
    traits: {
      enable: true,
      intensity: 'Medium',
      format: 'Classroom',
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'safety-car-vsc-procedure-training',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    name: 'Tire Compound Selection Strategy Session',
    toggle: 'advanced',
    type: categoriesIds[105],
    basics: {
      enable: true,
      description: 'Strategic seminar with tire suppliers and engineers on compound characteristics, degradation modeling, temperature windows, and race strategy implications for multi-compound regulations.',
      visibility: { show: true },
    },
    details: {
      enable: true,
      narrative: narrativesIds[3],
      visibility: { show: true },
    },
    traits: {
      enable: true,
      intensity: 'Medium',
      format: 'Group',
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'tire-compound-selection-strategy-session',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    name: 'Wet Weather Driving Technique Masterclass',
    toggle: 'advanced',
    type: categoriesIds[118],
    basics: {
      enable: true,
      description: 'Elite driver training on wet track car control, aquaplaning recovery, brake modulation, visibility management, and risk assessment for variable weather racing conditions.',
      visibility: { show: true },
    },
    details: {
      enable: true,
      narrative: narrativesIds[16],
      visibility: { show: true },
    },
    traits: {
      enable: true,
      intensity: 'Extreme',
      format: 'HandsOn',
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'wet-weather-driving-technique-masterclass',
    visibility: { check_publish: true, check_featured: true, check_pinned: false },
  },
  {
    name: 'Team Communication & Radio Protocol Training',
    toggle: 'advanced',
    type: categoriesIds[27],
    basics: {
      enable: true,
      description: 'Team-building program focused on clear radio communication, terminology standardization, urgency prioritization, and information flow optimization between driver, engineer, and pit wall.',
      visibility: { show: true },
    },
    details: {
      enable: true,
      narrative: narrativesIds[49],
      visibility: { show: true },
    },
    traits: {
      enable: true,
      intensity: 'Low',
      format: 'Group',
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'team-communication-radio-protocol-training',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    name: 'Carbon Fiber Repair & Composite Workshop',
    toggle: 'advanced',
    type: categoriesIds[166],
    basics: {
      enable: true,
      description: 'Technical workshop for composite technicians on damage assessment, repair methodologies, curing processes, quality verification, and structural integrity testing for carbon fiber racing components.',
      visibility: { show: true },
    },
    details: {
      enable: true,
      narrative: narrativesIds[14],
      visibility: { show: true },
    },
    traits: {
      enable: true,
      intensity: 'Medium',
      format: 'HandsOn',
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'carbon-fiber-repair-composite-workshop',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
] as const
