export const PRELOAD_GALLERY = (categoriesIds: number[], mediaIds: number[]) => [
  {
    name: 'Monaco GP 2024 Podium Ceremony Collection',
    toggle: 'advanced',
    type: categoriesIds[185],
    details: {
      enable: true,
      images: [mediaIds[0], mediaIds[1], mediaIds[2], mediaIds[3], mediaIds[4]],
      narrative: null,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'monaco-gp-2024-podium-ceremony-collection',
    visibility: { check_publish: true, check_featured: true, check_pinned: true },
  },
  {
    name: 'F1 Driver Portrait Session - 2024 Season',
    toggle: 'advanced',
    type: categoriesIds[53],
    details: {
      enable: true,
      images: [mediaIds[0], mediaIds[1], mediaIds[2]],
      narrative: null,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'f1-driver-portrait-session-2024-season',
    visibility: { check_publish: true, check_featured: true, check_pinned: false },
  },
  {
    name: 'Silverstone Overtake Action Sequence 2024',
    toggle: 'advanced',
    type: categoriesIds[146],
    details: {
      enable: true,
      images: [mediaIds[1], mediaIds[2], mediaIds[3]],
      narrative: null,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'silverstone-overtake-action-sequence-2024',
    visibility: { check_publish: true, check_featured: true, check_pinned: false },
  },
  {
    name: 'Garage Behind The Scenes - Race Weekend Operations',
    toggle: 'advanced',
    type: categoriesIds[123],
    details: {
      enable: true,
      images: [mediaIds[2], mediaIds[3], mediaIds[4]],
      narrative: null,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'garage-behind-scenes-race-weekend-operations',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    name: 'Historic F1 Championship Cars Museum Archive',
    toggle: 'advanced',
    type: categoriesIds[38],
    details: {
      enable: true,
      images: [mediaIds[0], mediaIds[2], mediaIds[4]],
      narrative: null,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'historic-f1-championship-cars-museum-archive',
    visibility: { check_publish: true, check_featured: true, check_pinned: false },
  },
  {
    name: '2024 Season Launch Promotional Photography',
    toggle: 'advanced',
    type: categoriesIds[122],
    details: {
      enable: true,
      images: [mediaIds[0], mediaIds[1], mediaIds[2]],
      narrative: null,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: '2024-season-launch-promotional-photography',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    name: 'WEC Le Mans 24h Night Racing Action Shots',
    toggle: 'advanced',
    type: categoriesIds[17],
    details: {
      enable: true,
      images: [mediaIds[1], mediaIds[3], mediaIds[4]],
      narrative: null,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'wec-le-mans-24h-night-racing-action-shots',
    visibility: { check_publish: true, check_featured: true, check_pinned: false },
  },
  {
    name: 'WRC Rally Stage Recce Behind The Scenes',
    toggle: 'advanced',
    type: categoriesIds[245],
    details: {
      enable: true,
      images: [mediaIds[0], mediaIds[1], mediaIds[4]],
      narrative: null,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'wrc-rally-stage-recce-behind-scenes',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    name: 'Championship Trophy Presentation Ceremony',
    toggle: 'advanced',
    type: categoriesIds[243],
    details: {
      enable: true,
      images: [mediaIds[0], mediaIds[1], mediaIds[2], mediaIds[3], mediaIds[4]],
      narrative: null,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'championship-trophy-presentation-ceremony',
    visibility: { check_publish: true, check_featured: true, check_pinned: true },
  },
  {
    name: 'Team Principal Press Conference Portrait Series',
    toggle: 'advanced',
    type: categoriesIds[52],
    details: {
      enable: true,
      images: [mediaIds[0], mediaIds[1], mediaIds[2]],
      narrative: null,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'team-principal-press-conference-portrait-series',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    name: 'Pit Stop Action Sequence - Sub-2.5 Second Execution',
    toggle: 'advanced',
    type: categoriesIds[215],
    details: {
      enable: true,
      images: [mediaIds[2], mediaIds[3], mediaIds[4]],
      narrative: null,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'pit-stop-action-sequence-sub-2-5-second-execution',
    visibility: { check_publish: true, check_featured: true, check_pinned: false },
  },
  {
    name: 'Factory Tour Historical Archive Collection',
    toggle: 'advanced',
    type: categoriesIds[232],
    details: {
      enable: true,
      images: [mediaIds[1], mediaIds[3], mediaIds[4]],
      narrative: null,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'factory-tour-historical-archive-collection',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    name: 'Sponsor Activation Promotional Campaign Assets',
    toggle: 'advanced',
    type: categoriesIds[107],
    details: {
      enable: true,
      images: [mediaIds[0], mediaIds[1], mediaIds[2], mediaIds[3]],
      narrative: null,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'sponsor-activation-promotional-campaign-assets',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    name: 'Driver Helmet Close-up Portrait Collection',
    toggle: 'advanced',
    type: categoriesIds[126],
    details: {
      enable: true,
      images: [mediaIds[0], mediaIds[2], mediaIds[4]],
      narrative: null,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'driver-helmet-close-up-portrait-collection',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    name: 'Wet Weather Racing Drama - Interlagos 2024',
    toggle: 'advanced',
    type: categoriesIds[41],
    details: {
      enable: true,
      images: [mediaIds[1], mediaIds[2], mediaIds[3]],
      narrative: null,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'wet-weather-racing-drama-interlagos-2024',
    visibility: { check_publish: true, check_featured: true, check_pinned: false },
  },
  {
    name: 'Vintage Racing Heritage Gallery - Classic Era',
    toggle: 'advanced',
    type: categoriesIds[9],
    details: {
      enable: true,
      images: [mediaIds[0], mediaIds[1], mediaIds[4]],
      narrative: null,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'vintage-racing-heritage-gallery-classic-era',
    visibility: { check_publish: true, check_featured: true, check_pinned: false },
  },
  {
    name: 'Car Reveal Event Promotional Photography',
    toggle: 'advanced',
    type: categoriesIds[105],
    details: {
      enable: true,
      images: [mediaIds[0], mediaIds[1], mediaIds[2], mediaIds[3], mediaIds[4]],
      narrative: null,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'car-reveal-event-promotional-photography',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    name: 'Podium Celebration Moments - Championship Victory',
    toggle: 'advanced',
    type: categoriesIds[118],
    details: {
      enable: true,
      images: [mediaIds[0], mediaIds[1], mediaIds[2], mediaIds[3], mediaIds[4]],
      narrative: null,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'podium-celebration-moments-championship-victory',
    visibility: { check_publish: true, check_featured: true, check_pinned: false },
  },
  {
    name: 'Engineering Workshop Behind The Scenes',
    toggle: 'advanced',
    type: categoriesIds[27],
    details: {
      enable: true,
      images: [mediaIds[0], mediaIds[2], mediaIds[4]],
      narrative: null,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'engineering-workshop-behind-scenes',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    name: 'Driver Fitness Training Portrait Series',
    toggle: 'advanced',
    type: categoriesIds[166],
    details: {
      enable: true,
      images: [mediaIds[1], mediaIds[3], mediaIds[4]],
      narrative: null,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'driver-fitness-training-portrait-series',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    name: 'Qualifying Session Grid Walk Action',
    toggle: 'advanced',
    type: categoriesIds[84],
    details: {
      enable: true,
      images: [mediaIds[0], mediaIds[1], mediaIds[2]],
      narrative: null,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'qualifying-session-grid-walk-action',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    name: 'Historic Monaco GP Archive 1950-1999',
    toggle: 'advanced',
    type: categoriesIds[48],
    details: {
      enable: true,
      images: [mediaIds[0], mediaIds[2], mediaIds[3]],
      narrative: null,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'historic-monaco-gp-archive-1950-1999',
    visibility: { check_publish: true, check_featured: true, check_pinned: false },
  },
  {
    name: 'Brand Partnership Promotional Campaign',
    toggle: 'advanced',
    type: categoriesIds[109],
    details: {
      enable: true,
      images: [mediaIds[0], mediaIds[1], mediaIds[2], mediaIds[3]],
      narrative: null,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'brand-partnership-promotional-campaign',
    visibility: { check_publish: true, check_featured: false, check_pinned: false },
  },
  {
    name: 'Race Start Launch Control Action Sequence',
    toggle: 'advanced',
    type: categoriesIds[110],
    details: {
      enable: true,
      images: [mediaIds[1], mediaIds[2], mediaIds[3], mediaIds[4]],
      narrative: null,
      visibility: { show: true },
    },
    generateSlug: false,
    slug: 'race-start-launch-control-action-sequence',
    visibility: { check_publish: true, check_featured: true, check_pinned: false },
  },
] as const
