// FILE: src/collections/Competition/Point/seeders/preload.ts
export const PRELOAD_POINT = (categoriesIds: number[]) => [
  {
    name: 'Championship Position Points - First Place',
    toggle: 'advanced',
    type: categoriesIds[185],
    basics: { enable: true, description: 'Standard championship points awarded for first place classification in any sanctioned event.', value: 25, scale: 'Standard', visibility: { show: true } },
    details: { enable: true, result: 1, visibility: { show: true } },
    traits: { enable: true, ranking: { before: 2, after: 1, delta: 25 }, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'First Place Championship Points | AF Motorsport', description: 'Reusable point rule for first place championship classification' },
    generateSlug: false, slug: 'championship-position-points-first',
    visibility: { check_publish: true, check_featured: true, check_pinned: true }
  },
  {
    name: 'Championship Position Points - Second Place',
    toggle: 'advanced',
    type: categoriesIds[53],
    basics: { enable: true, description: 'Standard championship points awarded for second place classification in any sanctioned event.', value: 18, scale: 'Standard', visibility: { show: true } },
    details: { enable: true, result: 2, visibility: { show: true } },
    traits: { enable: true, ranking: { before: 3, after: 2, delta: 18 }, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Second Place Championship Points | AF Motorsport', description: 'Reusable point rule for second place championship classification' },
    generateSlug: false, slug: 'championship-position-points-second',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Championship Position Points - Third Place',
    toggle: 'advanced',
    type: categoriesIds[146],
    basics: { enable: true, description: 'Standard championship points awarded for third place classification in any sanctioned event.', value: 15, scale: 'Standard', visibility: { show: true } },
    details: { enable: true, result: 3, visibility: { show: true } },
    traits: { enable: true, ranking: { before: 4, after: 3, delta: 15 }, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Third Place Championship Points | AF Motorsport', description: 'Reusable point rule for third place championship classification' },
    generateSlug: false, slug: 'championship-position-points-third',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Championship Position Points - Top Ten Scale',
    toggle: 'advanced',
    type: categoriesIds[123],
    basics: { enable: true, description: 'Inverse scale championship points for positions 4-10 in any sanctioned event.', value: 12, scale: 'Inverse', visibility: { show: true } },
    details: { enable: true, result: 4, visibility: { show: true } },
    traits: { enable: true, ranking: { before: 5, after: 4, delta: 12 }, modifiers: [{ condition: 'Position 4-10', adjustment: -2, impact: 'Decreasing point value per position' }], visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Top Ten Points Scale | AF Motorsport', description: 'Reusable inverse scale point rule for positions 4-10' },
    generateSlug: false, slug: 'championship-position-points-top-ten',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Qualifying Pole Position Bonus',
    toggle: 'advanced',
    type: categoriesIds[38],
    basics: { enable: true, description: 'Fixed bonus points awarded for securing pole position in any qualifying session.', value: 1, scale: 'Fixed', visibility: { show: true } },
    details: { enable: true, result: 5, visibility: { show: true } },
    traits: { enable: true, ranking: { before: 0, after: 1, delta: 1 }, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Pole Position Bonus Points | AF Motorsport', description: 'Reusable bonus point rule for qualifying pole position' },
    generateSlug: false, slug: 'qualifying-pole-position-bonus',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Fastest Lap Performance Bonus',
    toggle: 'advanced',
    type: categoriesIds[122],
    basics: { enable: true, description: 'Fixed bonus points awarded for setting fastest lap while finishing in top ten of any race.', value: 1, scale: 'Fixed', visibility: { show: true } },
    details: { enable: true, result: 6, visibility: { show: true } },
    traits: { enable: true, ranking: { before: 0, after: 1, delta: 1 }, modifiers: [{ condition: 'Finish position <= 10', adjustment: 1, impact: 'Bonus eligibility constraint' }], visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Fastest Lap Bonus Points | AF Motorsport', description: 'Reusable bonus point rule for fastest lap achievement' },
    generateSlug: false, slug: 'fastest-lap-performance-bonus',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Sprint Race Points Structure',
    toggle: 'advanced',
    type: categoriesIds[17],
    basics: { enable: true, description: 'Standardized points distribution for sprint race classifications across any event.', value: 8, scale: 'Standard', visibility: { show: true } },
    details: { enable: true, result: 7, visibility: { show: true } },
    traits: { enable: true, ranking: { before: 2, after: 1, delta: 8 }, modifiers: [{ condition: 'Positions 1-8', adjustment: -1, impact: 'Decreasing value per position' }], visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Sprint Race Points | AF Motorsport', description: 'Reusable point structure for sprint race classifications' },
    generateSlug: false, slug: 'sprint-race-points-structure',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Endurance Race Multiplier Points',
    toggle: 'advanced',
    type: categoriesIds[245],
    basics: { enable: true, description: 'Multiplier-based points for endurance race classifications with extended duration.', value: 25, scale: 'Multiplier', visibility: { show: true } },
    details: { enable: true, result: 8, visibility: { show: true } },
    traits: { enable: true, ranking: { before: 2, after: 1, delta: 25 }, modifiers: [{ condition: 'Duration >= 6 hours', adjustment: 25, impact: 'Double points application' }], visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Endurance Race Multiplier Points | AF Motorsport', description: 'Reusable multiplier point rule for endurance race events' },
    generateSlug: false, slug: 'endurance-race-multiplier-points',
    visibility: { check_publish: true, check_featured: true, check_pinned: true }
  },
  {
    name: 'Class-Based Championship Points',
    toggle: 'advanced',
    type: categoriesIds[243],
    basics: { enable: true, description: 'Standard points awarded for class-winning classification within multi-class events.', value: 25, scale: 'Standard', visibility: { show: true } },
    details: { enable: true, result: 9, visibility: { show: true } },
    traits: { enable: true, ranking: { before: 2, after: 1, delta: 25 }, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Class Championship Points | AF Motorsport', description: 'Reusable point rule for class-based championship classifications' },
    generateSlug: false, slug: 'class-based-championship-points',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Rookie Classification Bonus',
    toggle: 'advanced',
    type: categoriesIds[52],
    basics: { enable: true, description: 'Fixed bonus points awarded to rookie-classified drivers for championship standings.', value: 2, scale: 'Fixed', visibility: { show: true } },
    details: { enable: true, result: 10, visibility: { show: true } },
    traits: { enable: true, ranking: { before: 0, after: 2, delta: 2 }, modifiers: [{ condition: 'Driver classification = Rookie', adjustment: 2, impact: 'Rookie eligibility bonus' }], visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Rookie Bonus Points | AF Motorsport', description: 'Reusable bonus point rule for rookie driver classifications' },
    generateSlug: false, slug: 'rookie-classification-bonus',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Constructors Championship Allocation',
    toggle: 'advanced',
    type: categoriesIds[215],
    basics: { enable: true, description: 'Points allocated to constructor championship based on combined driver results in any event.', value: 25, scale: 'Standard', visibility: { show: true } },
    details: { enable: true, result: 11, visibility: { show: true } },
    traits: { enable: true, ranking: { before: 2, after: 1, delta: 25 }, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Constructors Points Allocation | AF Motorsport', description: 'Reusable point rule for constructor championship allocations' },
    generateSlug: false, slug: 'constructors-championship-allocation',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Did Not Finish Classification Points',
    toggle: 'advanced',
    type: categoriesIds[232],
    basics: { enable: true, description: 'Zero-point allocation for classified Did Not Finish results in any event.', value: 0, scale: 'Fixed', visibility: { show: true } },
    details: { enable: true, result: 12, visibility: { show: true } },
    traits: { enable: true, ranking: { before: 0, after: 0, delta: 0 }, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'DNF Classification Points | AF Motorsport', description: 'Reusable zero-point rule for classified DNF results' },
    generateSlug: false, slug: 'dnf-classification-points',
    visibility: { check_publish: true, check_featured: false, check_pinned: false }
  },
  {
    name: 'Penalty Point Deduction Template',
    toggle: 'advanced',
    type: categoriesIds[107],
    basics: { enable: true, description: 'Configurable penalty point deduction for regulatory infractions in any classification.', value: -5, scale: 'Custom', visibility: { show: true } },
    details: { enable: true, result: 13, visibility: { show: true } },
    traits: { enable: true, ranking: { before: 3, after: 4, delta: -5 }, modifiers: [{ condition: 'Post-race penalty', adjustment: -5, impact: 'Championship standing reduction' }], visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Penalty Point Deduction | AF Motorsport', description: 'Reusable penalty point rule for regulatory infractions' },
    generateSlug: false, slug: 'penalty-point-deduction-template',
    visibility: { check_publish: true, check_featured: false, check_pinned: false }
  },
  {
    name: 'Championship Adjustment Points',
    toggle: 'advanced',
    type: categoriesIds[126],
    basics: { enable: true, description: 'Post-event points adjustment for corrected classifications or steward decisions.', value: 0, scale: 'Custom', visibility: { show: true } },
    details: { enable: true, result: 14, visibility: { show: true } },
    traits: { enable: true, ranking: { before: 0, after: 0, delta: 0 }, modifiers: [{ condition: 'Steward decision', adjustment: 0, impact: 'Dynamic adjustment based on ruling' }], visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Championship Adjustment Points | AF Motorsport', description: 'Reusable adjustment point rule for post-event corrections' },
    generateSlug: false, slug: 'championship-adjustment-points',
    visibility: { check_publish: true, check_featured: false, check_pinned: false }
  },
  {
    name: 'Season Finale Bonus Multiplier',
    toggle: 'advanced',
    type: categoriesIds[41],
    basics: { enable: true, description: 'Bonus point multiplier applied to season-deciding final event classifications.', value: 5, scale: 'Multiplier', visibility: { show: true } },
    details: { enable: true, result: 15, visibility: { show: true } },
    traits: { enable: true, ranking: { before: 0, after: 5, delta: 5 }, modifiers: [{ condition: 'Event round = season finale', adjustment: 5, impact: 'Championship-deciding bonus' }], visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Season Finale Bonus Points | AF Motorsport', description: 'Reusable multiplier point rule for season finale events' },
    generateSlug: false, slug: 'season-finale-bonus-multiplier',
    visibility: { check_publish: true, check_featured: true, check_pinned: true }
  },
  {
    name: 'Qualifying Session Points Template',
    toggle: 'advanced',
    type: categoriesIds[9],
    basics: { enable: true, description: 'Standardized points for qualifying session classifications across any event format.', value: 8, scale: 'Standard', visibility: { show: true } },
    details: { enable: true, result: 16, visibility: { show: true } },
    traits: { enable: true, ranking: { before: 2, after: 1, delta: 8 }, modifiers: [{ condition: 'Top 8 qualifying', adjustment: -1, impact: 'Decreasing value per position' }], visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Qualifying Session Points | AF Motorsport', description: 'Reusable point template for qualifying session classifications' },
    generateSlug: false, slug: 'qualifying-session-points-template',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Logarithmic Scale Points Rule',
    toggle: 'advanced',
    type: categoriesIds[105],
    basics: { enable: true, description: 'Logarithmic point distribution for extended classification ranges in large-field events.', value: 25, scale: 'Logarithmic', visibility: { show: true } },
    details: { enable: true, result: 17, visibility: { show: true } },
    traits: { enable: true, ranking: { before: 2, after: 1, delta: 25 }, modifiers: [{ condition: 'Position > 10', adjustment: -3, impact: 'Logarithmic decay per position' }], visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Logarithmic Points Scale | AF Motorsport', description: 'Reusable logarithmic point rule for large-field classifications' },
    generateSlug: false, slug: 'logarithmic-scale-points-rule',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Custom Scale Points Definition',
    toggle: 'advanced',
    type: categoriesIds[118],
    basics: { enable: true, description: 'Configurable custom point scale for special event formats or exhibition competitions.', value: 0, scale: 'Custom', visibility: { show: true } },
    details: { enable: true, result: 18, visibility: { show: true } },
    traits: { enable: true, ranking: { before: 0, after: 0, delta: 0 }, modifiers: [{ condition: 'Event-specific rule', adjustment: 0, impact: 'Defined per event configuration' }], visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Custom Scale Points | AF Motorsport', description: 'Reusable custom point definition for special event formats' },
    generateSlug: false, slug: 'custom-scale-points-definition',
    visibility: { check_publish: true, check_featured: false, check_pinned: false }
  },
  {
    name: 'Withdrawal Classification Points',
    toggle: 'advanced',
    type: categoriesIds[27],
    basics: { enable: true, description: 'Zero-point allocation for withdrawn entries in any sanctioned event classification.', value: 0, scale: 'Fixed', visibility: { show: true } },
    details: { enable: true, result: 19, visibility: { show: true } },
    traits: { enable: true, ranking: { before: 0, after: 0, delta: 0 }, visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Withdrawal Classification Points | AF Motorsport', description: 'Reusable zero-point rule for withdrawn entry classifications' },
    generateSlug: false, slug: 'withdrawal-classification-points',
    visibility: { check_publish: true, check_featured: false, check_pinned: false }
  },
  {
    name: 'Provisional Result Points Hold',
    toggle: 'advanced',
    type: categoriesIds[166],
    basics: { enable: true, description: 'Temporary point allocation for provisional results pending official confirmation.', value: 0, scale: 'Standard', visibility: { show: true } },
    details: { enable: true, result: 20, visibility: { show: true } },
    traits: { enable: true, ranking: { before: 0, after: 0, delta: 0 }, modifiers: [{ condition: 'Result status = Provisional', adjustment: 0, impact: 'Points held pending confirmation' }], visibility: { show: true } },
    contexts: { enable: true, visibility: { show: true } },
    seo: { title: 'Provisional Result Points | AF Motorsport', description: 'Reusable hold point rule for provisional result classifications' },
    generateSlug: false, slug: 'provisional-result-points-hold',
    visibility: { check_publish: true, check_featured: false, check_pinned: false }
  }
] as const;
