// FILE: src/collections/Operations/Career/seeders/preload.ts
export const PRELOAD_CAREER = (categoriesIds: number[], narrativesIds: number[]) => [
  {
    name: 'Formula 1 Driver Championship Career',
    toggle: 'advanced',
    type: categoriesIds[185],
    basics: { enable: true, description: 'Professional racing career competing in Formula 1 World Championship with focus on championship contention and technical development.', visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[14], organization: 1, expectations: [], awards: [], visibility: { show: true } },
    traits: { enable: true, contract: 'FullTime', positions: [{ title: 'Race Driver', start: '2020-01-01', end: null }], visibility: { show: true } },
    contexts: { enable: true, entities: [], highlights: [], stories: [], visibility: { show: true } },
    seo: { title: 'F1 Driver Career Profile | AF Motorsport', description: 'Professional Formula 1 racing career documentation' },
    generateSlug: false, slug: 'formula-1-driver-championship-career',
    visibility: { check_publish: true, check_featured: true, check_pinned: true }
  },
  {
    name: 'Endurance Racing Specialist Career',
    toggle: 'advanced',
    type: categoriesIds[53],
    basics: { enable: true, description: 'Professional career focused on endurance racing competitions including Le Mans, WEC, and IMSA championships.', visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[1], organization: 2, expectations: [], awards: [], visibility: { show: true } },
    traits: { enable: true, contract: 'FullTime', positions: [{ title: 'Endurance Driver', start: '2018-01-01', end: null }], visibility: { show: true } },
    contexts: { enable: true, entities: [], highlights: [], stories: [], visibility: { show: true } },
    seo: { title: 'Endurance Racing Career Profile | AF Motorsport', description: 'Professional endurance racing career documentation' },
    generateSlug: false, slug: 'endurance-racing-specialist-career',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Technical Director Engineering Career',
    toggle: 'advanced',
    type: categoriesIds[146],
    basics: { enable: true, description: 'Senior engineering career leading technical development, aerodynamic programs, and vehicle performance optimization.', visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[26], organization: 1, expectations: [], awards: [], visibility: { show: true } },
    traits: { enable: true, contract: 'FullTime', positions: [{ title: 'Technical Director', start: '2017-03-01', end: null }], visibility: { show: true } },
    contexts: { enable: true, entities: [], highlights: [], stories: [], visibility: { show: true } },
    seo: { title: 'Technical Director Career Profile | AF Motorsport', description: 'Senior engineering leadership career documentation' },
    generateSlug: false, slug: 'technical-director-engineering-career',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Race Strategist Operations Career',
    toggle: 'advanced',
    type: categoriesIds[123],
    basics: { enable: true, description: 'Strategic operations career focused on race planning, in-race decision making, and competitive analysis.', visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[20], organization: 1, expectations: [], awards: [], visibility: { show: true } },
    traits: { enable: true, contract: 'FullTime', positions: [{ title: 'Chief Strategist', start: '2019-01-01', end: null }], visibility: { show: true } },
    contexts: { enable: true, entities: [], highlights: [], stories: [], visibility: { show: true } },
    seo: { title: 'Race Strategist Career Profile | AF Motorsport', description: 'Strategic operations career documentation for racing teams' },
    generateSlug: false, slug: 'race-strategist-operations-career',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Team Principal Leadership Career',
    toggle: 'advanced',
    type: categoriesIds[38],
    basics: { enable: true, description: 'Executive leadership career managing racing team operations, personnel, and championship strategy.', visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[34], organization: 1, expectations: [], awards: [], visibility: { show: true } },
    traits: { enable: true, contract: 'FullTime', positions: [{ title: 'Team Principal', start: '2013-01-01', end: null }], visibility: { show: true } },
    contexts: { enable: true, entities: [], highlights: [], stories: [], visibility: { show: true } },
    seo: { title: 'Team Principal Career Profile | AF Motorsport', description: 'Executive leadership career documentation for racing organizations' },
    generateSlug: false, slug: 'team-principal-leadership-career',
    visibility: { check_publish: true, check_featured: true, check_pinned: true }
  },
  {
    name: 'Performance Engineer Development Career',
    toggle: 'advanced',
    type: categoriesIds[122],
    basics: { enable: true, description: 'Technical engineering career specializing in vehicle dynamics, tire management, and performance optimization.', visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[13], organization: 1, expectations: [], awards: [], visibility: { show: true } },
    traits: { enable: true, contract: 'FullTime', positions: [{ title: 'Performance Engineer', start: '2015-01-01', end: null }], visibility: { show: true } },
    contexts: { enable: true, entities: [], highlights: [], stories: [], visibility: { show: true } },
    seo: { title: 'Performance Engineer Career Profile | AF Motorsport', description: 'Technical engineering career documentation for vehicle performance' },
    generateSlug: false, slug: 'performance-engineer-development-career',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Aerodynamics Specialist Career',
    toggle: 'advanced',
    type: categoriesIds[17],
    basics: { enable: true, description: 'Specialized engineering career focused on computational fluid dynamics, wind tunnel testing, and aerodynamic development.', visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[19], organization: 1, expectations: [], awards: [], visibility: { show: true } },
    traits: { enable: true, contract: 'FullTime', positions: [{ title: 'Aerodynamics Specialist', start: '2016-01-01', end: null }], visibility: { show: true } },
    contexts: { enable: true, entities: [], highlights: [], stories: [], visibility: { show: true } },
    seo: { title: 'Aerodynamics Specialist Career Profile | AF Motorsport', description: 'Specialized engineering career documentation for aerodynamic development' },
    generateSlug: false, slug: 'aerodynamics-specialist-career',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Pit Crew Chief Operations Career',
    toggle: 'advanced',
    type: categoriesIds[245],
    basics: { enable: true, description: 'Operational leadership career coordinating pit stop execution, crew training, and race weekend logistics.', visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[48], organization: 1, expectations: [], awards: [], visibility: { show: true } },
    traits: { enable: true, contract: 'FullTime', positions: [{ title: 'Pit Crew Chief', start: '2018-01-01', end: null }], visibility: { show: true } },
    contexts: { enable: true, entities: [], highlights: [], stories: [], visibility: { show: true } },
    seo: { title: 'Pit Crew Chief Career Profile | AF Motorsport', description: 'Operational leadership career documentation for pit crew management' },
    generateSlug: false, slug: 'pit-crew-chief-operations-career',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Data Engineer Analytics Career',
    toggle: 'advanced',
    type: categoriesIds[243],
    basics: { enable: true, description: 'Technical career specializing in telemetry analysis, performance modeling, and real-time data processing for racing operations.', visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[56], organization: 1, expectations: [], awards: [], visibility: { show: true } },
    traits: { enable: true, contract: 'FullTime', positions: [{ title: 'Lead Data Engineer', start: '2017-01-01', end: null }], visibility: { show: true } },
    contexts: { enable: true, entities: [], highlights: [], stories: [], visibility: { show: true } },
    seo: { title: 'Data Engineer Career Profile | AF Motorsport', description: 'Technical analytics career documentation for racing data systems' },
    generateSlug: false, slug: 'data-engineer-analytics-career',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Mechanical Technician Maintenance Career',
    toggle: 'advanced',
    type: categoriesIds[52],
    basics: { enable: true, description: 'Technical maintenance career focused on powertrain assembly, reliability optimization, and component fabrication.', visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[23], organization: 1, expectations: [], awards: [], visibility: { show: true } },
    traits: { enable: true, contract: 'FullTime', positions: [{ title: 'Lead Mechanic', start: '2014-01-01', end: null }], visibility: { show: true } },
    contexts: { enable: true, entities: [], highlights: [], stories: [], visibility: { show: true } },
    seo: { title: 'Mechanical Technician Career Profile | AF Motorsport', description: 'Technical maintenance career documentation for racing vehicle reliability' },
    generateSlug: false, slug: 'mechanical-technician-maintenance-career',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Logistics Coordinator Operations Career',
    toggle: 'advanced',
    type: categoriesIds[215],
    basics: { enable: true, description: 'Operational management career coordinating global freight, race weekend scheduling, and international travel logistics.', visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[12], organization: 1, expectations: [], awards: [], visibility: { show: true } },
    traits: { enable: true, contract: 'FullTime', positions: [{ title: 'Operations Coordinator', start: '2019-01-01', end: null }], visibility: { show: true } },
    contexts: { enable: true, entities: [], highlights: [], stories: [], visibility: { show: true } },
    seo: { title: 'Logistics Coordinator Career Profile | AF Motorsport', description: 'Operational management career documentation for racing logistics' },
    generateSlug: false, slug: 'logistics-coordinator-operations-career',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Safety Officer Compliance Career',
    toggle: 'advanced',
    type: categoriesIds[232],
    basics: { enable: true, description: 'Regulatory compliance career ensuring FIA safety standards, incident response protocols, and emergency preparedness.', visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[7], organization: 11, expectations: [], awards: [], visibility: { show: true } },
    traits: { enable: true, contract: 'FullTime', positions: [{ title: 'Safety Officer', start: '2016-01-01', end: null }], visibility: { show: true } },
    contexts: { enable: true, entities: [], highlights: [], stories: [], visibility: { show: true } },
    seo: { title: 'Safety Officer Career Profile | AF Motorsport', description: 'Regulatory compliance career documentation for racing safety standards' },
    generateSlug: false, slug: 'safety-officer-compliance-career',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Media Engineer Production Career',
    toggle: 'advanced',
    type: categoriesIds[107],
    basics: { enable: true, description: 'Technical production career managing broadcast systems, content distribution, and digital media infrastructure for global audiences.', visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[9], organization: 12, expectations: [], awards: [], visibility: { show: true } },
    traits: { enable: true, contract: 'FullTime', positions: [{ title: 'Media Engineer', start: '2018-01-01', end: null }], visibility: { show: true } },
    contexts: { enable: true, entities: [], highlights: [], stories: [], visibility: { show: true } },
    seo: { title: 'Media Engineer Career Profile | AF Motorsport', description: 'Technical production career documentation for racing media systems' },
    generateSlug: false, slug: 'media-engineer-production-career',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Human Resources Development Career',
    toggle: 'advanced',
    type: categoriesIds[126],
    basics: { enable: true, description: 'Organizational development career managing talent acquisition, training programs, and team welfare initiatives.', visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[6], organization: 1, expectations: [], awards: [], visibility: { show: true } },
    traits: { enable: true, contract: 'FullTime', positions: [{ title: 'HR Coordinator', start: '2017-01-01', end: null }], visibility: { show: true } },
    contexts: { enable: true, entities: [], highlights: [], stories: [], visibility: { show: true } },
    seo: { title: 'HR Development Career Profile | AF Motorsport', description: 'Organizational development career documentation for racing team personnel' },
    generateSlug: false, slug: 'human-resources-development-career',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Simulation Engineer Development Career',
    toggle: 'advanced',
    type: categoriesIds[41],
    basics: { enable: true, description: 'Technical development career creating driver training platforms, setup correlation tools, and real-time simulation systems.', visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[42], organization: 1, expectations: [], awards: [], visibility: { show: true } },
    traits: { enable: true, contract: 'FullTime', positions: [{ title: 'Simulation Engineer', start: '2020-01-01', end: null }], visibility: { show: true } },
    contexts: { enable: true, entities: [], highlights: [], stories: [], visibility: { show: true } },
    seo: { title: 'Simulation Engineer Career Profile | AF Motorsport', description: 'Technical development career documentation for racing simulation systems' },
    generateSlug: false, slug: 'simulation-engineer-development-career',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Fabrication Specialist Manufacturing Career',
    toggle: 'advanced',
    type: categoriesIds[9],
    basics: { enable: true, description: 'Specialized manufacturing career leading composite fabrication, rapid prototyping, and component quality control.', visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[22], organization: 1, expectations: [], awards: [], visibility: { show: true } },
    traits: { enable: true, contract: 'FullTime', positions: [{ title: 'Fabrication Specialist', start: '2015-01-01', end: null }], visibility: { show: true } },
    contexts: { enable: true, entities: [], highlights: [], stories: [], visibility: { show: true } },
    seo: { title: 'Fabrication Specialist Career Profile | AF Motorsport', description: 'Specialized manufacturing career documentation for racing component production' },
    generateSlug: false, slug: 'fabrication-specialist-manufacturing-career',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Electronics Systems Integration Career',
    toggle: 'advanced',
    type: categoriesIds[105],
    basics: { enable: true, description: 'Technical integration career managing vehicle electrical architecture, sensor networks, and data acquisition systems.', visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[3], organization: 1, expectations: [], awards: [], visibility: { show: true } },
    traits: { enable: true, contract: 'FullTime', positions: [{ title: 'Electronics Specialist', start: '2016-01-01', end: null }], visibility: { show: true } },
    contexts: { enable: true, entities: [], highlights: [], stories: [], visibility: { show: true } },
    seo: { title: 'Electronics Systems Career Profile | AF Motorsport', description: 'Technical integration career documentation for racing electrical systems' },
    generateSlug: false, slug: 'electronics-systems-integration-career',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Paint & Livery Application Career',
    toggle: 'advanced',
    type: categoriesIds[118],
    basics: { enable: true, description: 'Specialized application career leading livery design implementation, surface finish quality, and branding execution.', visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[16], organization: 1, expectations: [], awards: [], visibility: { show: true } },
    traits: { enable: true, contract: 'FullTime', positions: [{ title: 'Paint Specialist', start: '2019-01-01', end: null }], visibility: { show: true } },
    contexts: { enable: true, entities: [], highlights: [], stories: [], visibility: { show: true } },
    seo: { title: 'Paint Specialist Career Profile | AF Motorsport', description: 'Specialized application career documentation for racing livery production' },
    generateSlug: false, slug: 'paint-livery-application-career',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Welding & Structural Integrity Career',
    toggle: 'advanced',
    type: categoriesIds[27],
    basics: { enable: true, description: 'Specialized fabrication career ensuring chassis structural integrity, safety component welding, and aerospace-grade joining techniques.', visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[49], organization: 1, expectations: [], awards: [], visibility: { show: true } },
    traits: { enable: true, contract: 'FullTime', positions: [{ title: 'Welding Specialist', start: '2014-01-01', end: null }], visibility: { show: true } },
    contexts: { enable: true, entities: [], highlights: [], stories: [], visibility: { show: true } },
    seo: { title: 'Welding Specialist Career Profile | AF Motorsport', description: 'Specialized fabrication career documentation for racing structural integrity' },
    generateSlug: false, slug: 'welding-structural-integrity-career',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Reserve Driver Development Career',
    toggle: 'advanced',
    type: categoriesIds[166],
    basics: { enable: true, description: 'Professional development career serving as reserve driver with focus on simulator work, testing programs, and race readiness.', visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[14], organization: 1, expectations: [], awards: [], visibility: { show: true } },
    traits: { enable: true, contract: 'Reserve', positions: [{ title: 'Reserve Driver', start: '2022-01-01', end: null }], visibility: { show: true } },
    contexts: { enable: true, entities: [], highlights: [], stories: [], visibility: { show: true } },
    seo: { title: 'Reserve Driver Career Profile | AF Motorsport', description: 'Professional development career documentation for reserve racing drivers' },
    generateSlug: false, slug: 'reserve-driver-development-career',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  }
] as const;
