// FILE: src/collections/Operations/Initiative/seeders/preload.ts
export const PRELOAD_INITIATIVE = (categoriesIds: number[], narrativesIds: number[]) => [
  {
    name: 'Sustainable Racing Technology Program',
    toggle: 'advanced',
    type: categoriesIds[185],
    basics: { enable: true, description: 'Strategic initiative advancing environmental responsibility through sustainable powertrain and materials innovation.', mission: 'Achieve carbon-neutral racing operations while maintaining competitive performance excellence.', visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[14], strategies: [], expectations: [], insights: [], visibility: { show: true } },
    traits: { enable: true, status: 'Active', visibility: { show: true } },
    assets: { enable: true, primary: null, gallery: null, document: [], visibility: { show: true } },
    contexts: { enable: true, classifications: null, entities: [], schedules: [], references: [], histories: [], visibility: { show: true } },
    seo: { title: 'Sustainable Racing Technology Initiative | AF Motorsport', description: 'Strategic program advancing environmental responsibility in motorsport' },
    generateSlug: false, slug: 'sustainable-racing-technology-program',
    visibility: { check_publish: true, check_featured: true, check_pinned: true }
  },
  {
    name: 'Driver Development Academy Initiative',
    toggle: 'advanced',
    type: categoriesIds[53],
    basics: { enable: true, description: 'Comprehensive talent identification and development program for emerging racing competitors.', mission: 'Nurture the next generation of championship-caliber drivers through structured training and mentorship.', visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[1], strategies: [], expectations: [], insights: [], visibility: { show: true } },
    traits: { enable: true, status: 'Active', visibility: { show: true } },
    assets: { enable: true, primary: null, gallery: null, document: [], visibility: { show: true } },
    contexts: { enable: true, classifications: null, entities: [], schedules: [], references: [], histories: [], visibility: { show: true } },
    seo: { title: 'Driver Development Academy Initiative | AF Motorsport', description: 'Talent identification and development program for emerging racing competitors' },
    generateSlug: false, slug: 'driver-development-academy-initiative',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Safety Innovation Research Campaign',
    toggle: 'advanced',
    type: categoriesIds[146],
    basics: { enable: true, description: 'Collaborative research initiative advancing driver protection and incident response technologies.', mission: 'Develop and validate next-generation safety systems that prevent injuries and save lives.', visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[26], strategies: [], expectations: [], insights: [], visibility: { show: true } },
    traits: { enable: true, status: 'Active', visibility: { show: true } },
    assets: { enable: true, primary: null, gallery: null, document: [], visibility: { show: true } },
    contexts: { enable: true, classifications: null, entities: [], schedules: [], references: [], histories: [], visibility: { show: true } },
    seo: { title: 'Safety Innovation Research Initiative | AF Motorsport', description: 'Collaborative research advancing driver protection and incident response' },
    generateSlug: false, slug: 'safety-innovation-research-campaign',
    visibility: { check_publish: true, check_featured: true, check_pinned: true }
  },
  {
    name: 'Global Fan Engagement Movement',
    toggle: 'advanced',
    type: categoriesIds[123],
    basics: { enable: true, description: 'Strategic movement expanding authentic connection between motorsport and global audiences.', mission: 'Build inclusive, accessible, and meaningful fan experiences across all digital and physical touchpoints.', visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[20], strategies: [], expectations: [], insights: [], visibility: { show: true } },
    traits: { enable: true, status: 'Active', visibility: { show: true } },
    assets: { enable: true, primary: null, gallery: null, document: [], visibility: { show: true } },
    contexts: { enable: true, classifications: null, entities: [], schedules: [], references: [], histories: [], visibility: { show: true } },
    seo: { title: 'Global Fan Engagement Initiative | AF Motorsport', description: 'Strategic movement expanding authentic connection with global motorsport audiences' },
    generateSlug: false, slug: 'global-fan-engagement-movement',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Technical Excellence Certification Program',
    toggle: 'advanced',
    type: categoriesIds[38],
    basics: { enable: true, description: 'Professional development program establishing industry standards for technical competency.', mission: 'Elevate organizational capability through standardized training, assessment, and certification pathways.', visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[34], strategies: [], expectations: [], insights: [], visibility: { show: true } },
    traits: { enable: true, status: 'Active', visibility: { show: true } },
    assets: { enable: true, primary: null, gallery: null, document: [], visibility: { show: true } },
    contexts: { enable: true, classifications: null, entities: [], schedules: [], references: [], histories: [], visibility: { show: true } },
    seo: { title: 'Technical Excellence Certification | AF Motorsport', description: 'Professional development program establishing technical competency standards' },
    generateSlug: false, slug: 'technical-excellence-certification-program',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Diversity & Inclusion Advocacy Campaign',
    toggle: 'advanced',
    type: categoriesIds[122],
    basics: { enable: true, description: 'Advocacy campaign promoting equitable access and representation across all motorsport disciplines.', mission: 'Remove barriers and create pathways for underrepresented groups to participate and lead in motorsport.', visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[13], strategies: [], expectations: [], insights: [], visibility: { show: true } },
    traits: { enable: true, status: 'Active', visibility: { show: true } },
    assets: { enable: true, primary: null, gallery: null, document: [], visibility: { show: true } },
    contexts: { enable: true, classifications: null, entities: [], schedules: [], references: [], histories: [], visibility: { show: true } },
    seo: { title: 'Diversity & Inclusion Advocacy | AF Motorsport', description: 'Campaign promoting equitable access and representation in motorsport' },
    generateSlug: false, slug: 'diversity-inclusion-advocacy-campaign',
    visibility: { check_publish: true, check_featured: true, check_pinned: true }
  },
  {
    name: 'Digital Transformation Action Plan',
    toggle: 'advanced',
    type: categoriesIds[17],
    basics: { enable: true, description: 'Strategic action plan modernizing organizational systems through digital technology adoption.', mission: 'Enable data-driven decision making, operational efficiency, and enhanced fan experiences through digital innovation.', visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[19], strategies: [], expectations: [], insights: [], visibility: { show: true } },
    traits: { enable: true, status: 'Active', visibility: { show: true } },
    assets: { enable: true, primary: null, gallery: null, document: [], visibility: { show: true } },
    contexts: { enable: true, classifications: null, entities: [], schedules: [], references: [], histories: [], visibility: { show: true } },
    seo: { title: 'Digital Transformation Initiative | AF Motorsport', description: 'Strategic action plan modernizing systems through digital technology adoption' },
    generateSlug: false, slug: 'digital-transformation-action-plan',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Community Outreach Fundraiser',
    toggle: 'advanced',
    type: categoriesIds[245],
    basics: { enable: true, description: 'Fundraising initiative supporting local community development through motorsport engagement.', mission: 'Generate resources for education, infrastructure, and youth programs in host communities.', visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[48], strategies: [], expectations: [], insights: [], visibility: { show: true } },
    traits: { enable: true, status: 'Active', visibility: { show: true } },
    assets: { enable: true, primary: null, gallery: null, document: [], visibility: { show: true } },
    contexts: { enable: true, classifications: null, entities: [], schedules: [], references: [], histories: [], visibility: { show: true } },
    seo: { title: 'Community Outreach Fundraiser | AF Motorsport', description: 'Fundraising initiative supporting local community development through motorsport' },
    generateSlug: false, slug: 'community-outreach-fundraiser',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Regulatory Compliance Research Expedition',
    toggle: 'advanced',
    type: categoriesIds[243],
    basics: { enable: true, description: 'Research expedition analyzing global regulatory frameworks for competitive optimization.', mission: 'Identify opportunities for regulatory innovation that enhance safety, competition, and sustainability.', visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[56], strategies: [], expectations: [], insights: [], visibility: { show: true } },
    traits: { enable: true, status: 'Proposed', visibility: { show: true } },
    assets: { enable: true, primary: null, gallery: null, document: [], visibility: { show: true } },
    contexts: { enable: true, classifications: null, entities: [], schedules: [], references: [], histories: [], visibility: { show: true } },
    seo: { title: 'Regulatory Compliance Research | AF Motorsport', description: 'Research expedition analyzing global regulatory frameworks for optimization' },
    generateSlug: false, slug: 'regulatory-compliance-research-expedition',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Youth STEM Education Movement',
    toggle: 'advanced',
    type: categoriesIds[52],
    basics: { enable: true, description: 'Educational movement inspiring young people through motorsport-based STEM learning.', mission: 'Ignite passion for science, technology, engineering, and mathematics through hands-on racing experiences.', visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[23], strategies: [], expectations: [], insights: [], visibility: { show: true } },
    traits: { enable: true, status: 'Active', visibility: { show: true } },
    assets: { enable: true, primary: null, gallery: null, document: [], visibility: { show: true } },
    contexts: { enable: true, classifications: null, entities: [], schedules: [], references: [], histories: [], visibility: { show: true } },
    seo: { title: 'Youth STEM Education Initiative | AF Motorsport', description: 'Educational movement inspiring young people through motorsport-based STEM learning' },
    generateSlug: false, slug: 'youth-stem-education-movement',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Performance Analytics Innovation Program',
    toggle: 'advanced',
    type: categoriesIds[215],
    basics: { enable: true, description: 'Innovation program advancing data science capabilities for competitive performance optimization.', mission: 'Develop proprietary analytics tools that transform raw data into actionable competitive intelligence.', visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[12], strategies: [], expectations: [], insights: [], visibility: { show: true } },
    traits: { enable: true, status: 'Active', visibility: { show: true } },
    assets: { enable: true, primary: null, gallery: null, document: [], visibility: { show: true } },
    contexts: { enable: true, classifications: null, entities: [], schedules: [], references: [], histories: [], visibility: { show: true } },
    seo: { title: 'Performance Analytics Innovation | AF Motorsport', description: 'Innovation program advancing data science for competitive performance optimization' },
    generateSlug: false, slug: 'performance-analytics-innovation-program',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Mental Health Support Campaign',
    toggle: 'advanced',
    type: categoriesIds[232],
    basics: { enable: true, description: 'Advocacy campaign promoting mental wellness resources for competitors and team members.', mission: 'Destigmatize mental health challenges and provide accessible support for high-pressure environments.', visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[7], strategies: [], expectations: [], insights: [], visibility: { show: true } },
    traits: { enable: true, status: 'Active', visibility: { show: true } },
    assets: { enable: true, primary: null, gallery: null, document: [], visibility: { show: true } },
    contexts: { enable: true, classifications: null, entities: [], schedules: [], references: [], histories: [], visibility: { show: true } },
    seo: { title: 'Mental Health Support Campaign | AF Motorsport', description: 'Advocacy campaign promoting mental wellness resources for motorsport professionals' },
    generateSlug: false, slug: 'mental-health-support-campaign',
    visibility: { check_publish: true, check_featured: true, check_pinned: true }
  },
  {
    name: 'Heritage Preservation Action',
    toggle: 'advanced',
    type: categoriesIds[107],
    basics: { enable: true, description: 'Action initiative documenting and conserving motorsport historical artifacts and narratives.', mission: 'Preserve racing heritage for future generations through archival, restoration, and educational programs.', visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[9], strategies: [], expectations: [], insights: [], visibility: { show: true } },
    traits: { enable: true, status: 'Active', visibility: { show: true } },
    assets: { enable: true, primary: null, gallery: null, document: [], visibility: { show: true } },
    contexts: { enable: true, classifications: null, entities: [], schedules: [], references: [], histories: [], visibility: { show: true } },
    seo: { title: 'Heritage Preservation Initiative | AF Motorsport', description: 'Action initiative documenting and conserving motorsport historical artifacts' },
    generateSlug: false, slug: 'heritage-preservation-action',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Women in Motorsport Leadership Program',
    toggle: 'advanced',
    type: categoriesIds[126],
    basics: { enable: true, description: 'Leadership development program advancing female representation in motorsport executive roles.', mission: 'Equip women with skills, networks, and opportunities to lead at the highest levels of motorsport.', visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[6], strategies: [], expectations: [], insights: [], visibility: { show: true } },
    traits: { enable: true, status: 'Active', visibility: { show: true } },
    assets: { enable: true, primary: null, gallery: null, document: [], visibility: { show: true } },
    contexts: { enable: true, classifications: null, entities: [], schedules: [], references: [], histories: [], visibility: { show: true } },
    seo: { title: 'Women in Motorsport Leadership | AF Motorsport', description: 'Leadership development program advancing female representation in motorsport' },
    generateSlug: false, slug: 'women-motorsport-leadership-program',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Circular Economy Materials Research',
    toggle: 'advanced',
    type: categoriesIds[41],
    basics: { enable: true, description: 'Research initiative developing sustainable materials through circular economy principles.', mission: 'Create high-performance racing components from recycled and renewable materials without compromising safety.', visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[42], strategies: [], expectations: [], insights: [], visibility: { show: true } },
    traits: { enable: true, status: 'Proposed', visibility: { show: true } },
    assets: { enable: true, primary: null, gallery: null, document: [], visibility: { show: true } },
    contexts: { enable: true, classifications: null, entities: [], schedules: [], references: [], histories: [], visibility: { show: true } },
    seo: { title: 'Circular Economy Materials Research | AF Motorsport', description: 'Research developing sustainable materials through circular economy principles' },
    generateSlug: false, slug: 'circular-economy-materials-research',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Fan Safety Education Campaign',
    toggle: 'advanced',
    type: categoriesIds[9],
    basics: { enable: true, description: 'Educational campaign promoting spectator safety awareness at motorsport events.', mission: 'Empower fans with knowledge and protocols to enjoy racing safely and responsibly.', visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[22], strategies: [], expectations: [], insights: [], visibility: { show: true } },
    traits: { enable: true, status: 'Active', visibility: { show: true } },
    assets: { enable: true, primary: null, gallery: null, document: [], visibility: { show: true } },
    contexts: { enable: true, classifications: null, entities: [], schedules: [], references: [], histories: [], visibility: { show: true } },
    seo: { title: 'Fan Safety Education Campaign | AF Motorsport', description: 'Educational campaign promoting spectator safety awareness at motorsport events' },
    generateSlug: false, slug: 'fan-safety-education-campaign',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Emerging Market Expansion Initiative',
    toggle: 'advanced',
    type: categoriesIds[105],
    basics: { enable: true, description: 'Strategic initiative expanding motorsport presence in high-growth international markets.', mission: 'Build sustainable fan bases, commercial partnerships, and competitive pathways in emerging regions.', visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[3], strategies: [], expectations: [], insights: [], visibility: { show: true } },
    traits: { enable: true, status: 'Active', visibility: { show: true } },
    assets: { enable: true, primary: null, gallery: null, document: [], visibility: { show: true } },
    contexts: { enable: true, classifications: null, entities: [], schedules: [], references: [], histories: [], visibility: { show: true } },
    seo: { title: 'Emerging Market Expansion | AF Motorsport', description: 'Strategic initiative expanding motorsport presence in high-growth international markets' },
    generateSlug: false, slug: 'emerging-market-expansion-initiative',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Veteran Transition Support Program',
    toggle: 'advanced',
    type: categoriesIds[118],
    basics: { enable: true, description: 'Support program assisting retired competitors in transitioning to post-racing careers.', mission: 'Provide resources, mentorship, and opportunities for former drivers to thrive beyond active competition.', visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[16], strategies: [], expectations: [], insights: [], visibility: { show: true } },
    traits: { enable: true, status: 'Active', visibility: { show: true } },
    assets: { enable: true, primary: null, gallery: null, document: [], visibility: { show: true } },
    contexts: { enable: true, classifications: null, entities: [], schedules: [], references: [], histories: [], visibility: { show: true } },
    seo: { title: 'Veteran Transition Support | AF Motorsport', description: 'Support program assisting retired competitors in post-racing career transitions' },
    generateSlug: false, slug: 'veteran-transition-support-program',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Carbon Footprint Reduction Action',
    toggle: 'advanced',
    type: categoriesIds[27],
    basics: { enable: true, description: 'Action initiative reducing organizational carbon emissions through operational optimization.', mission: 'Achieve measurable carbon reduction across logistics, facilities, and event operations.', visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[49], strategies: [], expectations: [], insights: [], visibility: { show: true } },
    traits: { enable: true, status: 'Active', visibility: { show: true } },
    assets: { enable: true, primary: null, gallery: null, document: [], visibility: { show: true } },
    contexts: { enable: true, classifications: null, entities: [], schedules: [], references: [], histories: [], visibility: { show: true } },
    seo: { title: 'Carbon Footprint Reduction | AF Motorsport', description: 'Action initiative reducing organizational carbon emissions through operational optimization' },
    generateSlug: false, slug: 'carbon-footprint-reduction-action',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  },
  {
    name: 'Cross-Discipline Knowledge Exchange',
    toggle: 'advanced',
    type: categoriesIds[166],
    basics: { enable: true, description: 'Knowledge exchange program facilitating collaboration across motorsport disciplines.', mission: 'Accelerate innovation through shared learning between Formula 1, endurance, rally, and emerging racing categories.', visibility: { show: true } },
    details: { enable: true, narrative: narrativesIds[14], strategies: [], expectations: [], insights: [], visibility: { show: true } },
    traits: { enable: true, status: 'Active', visibility: { show: true } },
    assets: { enable: true, primary: null, gallery: null, document: [], visibility: { show: true } },
    contexts: { enable: true, classifications: null, entities: [], schedules: [], references: [], histories: [], visibility: { show: true } },
    seo: { title: 'Cross-Discipline Knowledge Exchange | AF Motorsport', description: 'Knowledge exchange program facilitating collaboration across motorsport disciplines' },
    generateSlug: false, slug: 'cross-discipline-knowledge-exchange',
    visibility: { check_publish: true, check_featured: true, check_pinned: false }
  }
] as const;
